### ISSUE TITLE
同步企业微信后，用户没有把部门关联起来

### ISSUE THREAD

**Issue by lemsn** [eryajf/go-ldap-admin#100]
目前有三个问题：
1、手机为空的时候，添加LDAP会出错，手机号能否改为非必填？
2、部门转拼音的时候有问题，如下图1
3、用户和部门没有关联起来。如下图2

![图片](https://user-images.githubusercontent.com/9290824/182502825-819de16b-54f5-465e-8c99-56ccf9a1d040.png)

![图片](https://user-images.githubusercontent.com/9290824/182503085-323c3b5b-7336-475d-a47c-ab74b42d20e0.png)

**Comment by eryajf** [comment]
您好 @lemsn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lemsn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
问题1，我稍后兼容一下
问题2，是个已知问题，目前针对中英文混合的名字，还没想到什么比较好的处理方案，就暂时保持原样了
问题3，你的操作步骤是否是先同步分组，再同步用户，如果是这样，按说不会有这个问题

**Comment by eryajf** [comment]
问题1已兼容修复，问题2针对你的这个情况做了一些兼容处理，不过这个地方情况变化太多，未必能满足所有的场景需要。问题3也已经修复。

你可以拉取最新的后端代码进行重试！

**Comment by lemsn** [comment]
好的，我把老的dokcer镜像删除，然后试试

**Comment by lemsn** [comment]
同步分组拼音的问题解决了，现在是同步用户直接报500错误 ，没有返回具体原因

![图片](https://user-images.githubusercontent.com/9290824/182838136-51cb9dbb-a870-407b-99a1-40cc4973e1a5.png)

**Comment by eryajf** [comment]
看下后端服务状态，估计是有什么特殊情况

**Comment by eryajf** [comment]
如果你本地有go环境，建议你用这个工具 https://github.com/eryajf/third-tools 跑一下数据，然后打印一下用户名字，看看到底有哪些特殊情况

**Comment by lemsn** [comment]
这是我的日志

![图片](https://user-images.githubusercontent.com/9290824/183229985-29a737fe-f3e6-483b-9250-437314e13b6c.png)

**Comment by lemsn** [comment]
原来好好的，更新你这个最新版就出问题了

**Comment by eryajf** [comment]
昨天晚上又更新了一下这块儿逻辑，你再拉下最新版本，看看是否还会有这个问题

**Comment by lemsn** [comment]
> 问题1，我稍后兼容一下 问题2，是个已知问题，目前针对中英文混合的名字，还没想到什么比较好的处理方案，就暂时保持原样了 问题3，你的操作步骤是否是先同步分组，再同步用户，如果是这样，按说不会有这个问题

之前几百个员工都没有关联部门，一个个手动修改，麻烦的很

**Comment by eryajf** [comment]
> 之前几百个员工都没有关联部门，一个个手动修改，麻烦的很

如果还没有正式启用，可以先把用户全部清空，然后重新同步一次

**Comment by lemsn** [comment]
30%的人已经使用了

**Comment by lemsn** [comment]
SyncWeComUsers写入用户失败：添加用户: lixiaxia, 失败: AddUser向LDAP创建用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": mobile: value #0 invalid per syntax

**Comment by lemsn** [comment]
手机为空，这个问题还没兼容好吗

**Comment by lemsn** [comment]
还有一个怪事，如下图，工号的字段，我明明填写的userid,  但显示是手机号，显示手机号也就算了，但还不一样，还提示手机号为空，见图2


![图片](https://user-images.githubusercontent.com/9290824/183230502-c97d0328-cab7-43be-ab93-7f71b6af24af.png)


![图片](https://user-images.githubusercontent.com/9290824/183230537-fe291805-127c-4be0-9ee0-a98247eb76e1.png)

**Comment by eryajf** [comment]
> SyncWeComUsers写入用户失败：添加用户: lixiaxia, 失败: AddUser向LDAP创建用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": mobile: value #0 invalid per syntax

这个问题还会出现吗，最后你这个截图里第一个用户 该用户手机号为空  就是处理这个问题的，用这个来占位，按说不应该再报这个错误了

**Comment by eryajf** [comment]
> SyncWeComUsers写入用户失败：添加用户: lixiaxia, 失败: AddUser向LDAP创建用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": mobile: value #0 invalid per syntax

这个找到原因了，不然用中文直接这样占位，我再发个fix版本

**Comment by eryajf** [comment]
最新的后端镜像已经push

**Comment by lemsn** [comment]
好的，现在还有个问题

![图片](https://user-images.githubusercontent.com/9290824/183234381-95e53f0e-3fe5-4ba0-8d69-8895b77e4353.png)

**Comment by lemsn** [comment]
再兼容一下这个问题，应该就没问题了

**Comment by lemsn** [comment]
![图片](https://user-images.githubusercontent.com/9290824/183234583-3eb7c1c6-2978-4f41-be74-721d47db6cba.png)

**Comment by lemsn** [comment]
我用工具试了一下，有的员工，mobile字段为空，telephone字段是有号码的，所有mobile有时候是空的，可以兼容一下这个问题吗，如果 mobile就取telephone，如果都为空，那再再给他 emptyMobile.

**Comment by lemsn** [comment]
![图片](https://user-images.githubusercontent.com/9290824/183235197-9f84fd6d-4c43-4184-939c-94c05a8b3ff4.png)

**Comment by eryajf** [comment]
> 我用工具试了一下，有的员工，mobile字段为空，telephone字段是有号码的，所以mobile有时候是空的，可以兼容一下这个问题吗，如果 mobile为空就取telephone，如果都为空，那再再给他 emptyMobile.

通常来说，telephone地方填写了手机号码，应该属于管理人员配置错误的原因，应该把这个用户的手机号编辑到 mobile字段去才对，不然类似的错误用法以后还会出现，那这后端是兼容不过来的。

其实兼容当前这个并不难，难的是兼容不规范的用法，所以字段关系中既然已经配置了 手机号 关联 mobile字段，整套处理逻辑就已经会将这两个绑定上了，这也是后端的设计逻辑，从约定大约配置的角度来说，合理的做法应该是更改这个用户信息以符合约定。

**Comment by eryajf** [comment]
> 好的，现在还有个问题
> 
> ![图片](https://user-images.githubusercontent.com/9290824/183234381-95e53f0e-3fe5-4ba0-8d69-8895b77e4353.png)

这里是上午修复之前，没有对邮箱做非空判断，而ldap看起来是邮箱字段为空也没有出错，因此之前邮箱为空的也添加成功了。现在如果邮箱还为空，将会以  该用户邮箱为空 占位！

**Comment by lemsn** [comment]
你看一下，工号那一列，兼容做的不错，如果是空，就用手机号，如果手机空，就用用户名，挺好了，也不会有空，现在关键字段有空就出错，如果你再把mobile ，telephone 兼容一下就好了。

**Comment by eryajf** [comment]
> 工号那一列，兼容做的不错，如果是空，就用手机号

并非工号为空用了手机号，而是你再关系管理中配置了工号字段用远程的手机号字段，才关联上的。

**Comment by lemsn** [comment]
你看我工号配置的是用userid，但是这一列内容各种不一样，有的是id，有的是 mobile,有的是telephone ，有的是用户名。

![图片](https://user-images.githubusercontent.com/9290824/183253812-398b2850-18fd-4b19-a82b-3e7b17eb34d8.png)

**Comment by eryajf** [comment]
userid在企业微信当中，并不是一个自动生成的固定ID，而是管理员自定义填写的内容，因此不排除某个用户的userid本身就是用手机号填充的，或者用名字的拼音，或者用邮箱，这个你可以到后台看一看
