### ISSUE TITLE
如何将现有用户数据（excel、sql等形式的数据）导入到该项目中？

### ISSUE THREAD

**Issue by JinCheng666** [eryajf/go-ldap-admin#104]
感谢楼主提供的这么好的项目，已经疯狂star。这两天已经做了和公司业务的联调测试，拟在近期部署~~~
但目前还不清楚如何初始化用户库，前端没见到有批量导入的功能。直接在mysql的user表中导入用户数据可以吗？

#### 您使用的场景？ | 1. Your usage scenarios?
公司用户库初始化

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
将现有用户数据（excel、sql等形式的数据）导入到该项目中

目前公司还没有使用ldap，所有没有现成的ldap服务可以用，我直接用了本项目中docker-compose的openldap服务。

**Comment by eryajf** [comment]
您好 @JinCheng666👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @JinCheng666. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
感谢肯定。

如果想要批量导入，有一个建议是通过脚本调用后端接口进行批量导入，这样出来的效果以及功能都会是最完整的。

一个可用的测试请求如下：

```sh
curl --location --request POST 'http://localhost:8888/api/user/add' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIwODk2NTYsImlkZW50aXR5IjoxLCJvcmlnX2lhdCI6MTY0ODg4OTY1NiwidXNlciI6IntcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkNnFHOEVPLnZyUWxGckFVT3h6cE9QdXU5THJSWFNnWHQ5LkhOdEhjbE1LU3d4cTZYbVYyTjZcIixcIm1vYmlsZVwiOlwiMTg4ODg4ODg4ODhcIixcImF2YXRhclwiOlwiaHR0cHM6Ly93cGltZy53YWxsc3Rjbi5jb20vZjc3ODczOGMtZTRmOC00ODcwLWI2MzQtNTY3MDNiNGFjYWZlLmdpZlwiLFwibmlja25hbWVcIjpcIlwiLFwiaW50cm9kdWN0aW9uXCI6XCJcIixcInN0YXR1c1wiOjEsXCJjcmVhdG9yXCI6XCLns7vnu59cIixcInJvbGVzXCI6W3tcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJuYW1lXCI6XCLnrqHnkIblkZhcIixcImtleXdvcmRcIjpcImFkbWluXCIsXCJkZXNjXCI6XCJcIixcInN0YXR1c1wiOjEsXCJzb3J0XCI6MSxcImNyZWF0b3JcIjpcIuezu-e7n1wiLFwidXNlcnNcIjpudWxsLFwibWVudXNcIjpudWxsfV19In0.zuc7z6XPqCDUi4efgGb2FKlnUIEcOujqzps51w47Xuw' \
--header 'User-Agent: apifox/1.0.0 (https://www.apifox.cn)' \
--header 'Cookie: gowebmini-Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIwODk2NTYsImlkZW50aXR5IjoxLCJvcmlnX2lhdCI6MTY0ODg4OTY1NiwidXNlciI6IntcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkNnFHOEVPLnZyUWxGckFVT3h6cE9QdXU5THJSWFNnWHQ5LkhOdEhjbE1LU3d4cTZYbVYyTjZcIixcIm1vYmlsZVwiOlwiMTg4ODg4ODg4ODhcIixcImF2YXRhclwiOlwiaHR0cHM6Ly93cGltZy53YWxsc3Rjbi5jb20vZjc3ODczOGMtZTRmOC00ODcwLWI2MzQtNTY3MDNiNGFjYWZlLmdpZlwiLFwibmlja25hbWVcIjpcIlwiLFwiaW50cm9kdWN0aW9uXCI6XCJcIixcInN0YXR1c1wiOjEsXCJjcmVhdG9yXCI6XCLns7vnu59cIixcInJvbGVzXCI6W3tcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJuYW1lXCI6XCLnrqHnkIblkZhcIixcImtleXdvcmRcIjpcImFkbWluXCIsXCJkZXNjXCI6XCJcIixcInN0YXR1c1wiOjEsXCJzb3J0XCI6MSxcImNyZWF0b3JcIjpcIuezu-e7n1wiLFwidXNlcnNcIjpudWxsLFwibWVudXNcIjpudWxsfV19In0.zuc7z6XPqCDUi4efgGb2FKlnUIEcOujqzps51w47Xuw' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "test",
    "mail": "test@eryajf.net",
    "jobNumber": "56",
    "mobile": "13667766612",
    "nickname": "测试用户",
    "status": 1,
    "roleIds": [2],
    "departmentId": [],
    "departments": "",
    "introduction": "测试用户",
    "postalAddress": "河南省南阳市",
    "avatar": "http://dummyimage.com/100x100",
    "password": "",
    "givenName": "测试用户",
    "position": "测试"
}'
```

你可以将用户数据做一个遍历，然后请求接口进行批量导入！

**Comment by JinCheng666** [comment]
感谢楼主，已测试成功。祝万事如意！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eryajf/go-ldap-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月4日(星期四) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eryajf/go-ldap-admin] 如何将现有用户数据（excel、sql等形式的数据）导入到该项目中？ (Issue #104)





 
感谢肯定。
 
如果想要批量导入，有一个建议是通过脚本调用后端接口进行批量导入，这样出来的效果以及功能都会是最完整的。
 
一个可用的测试请求如下：
 curl --location --request POST 'http://localhost:8888/api/user/add' \ --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIwODk2NTYsImlkZW50aXR5IjoxLCJvcmlnX2lhdCI6MTY0ODg4OTY1NiwidXNlciI6IntcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkNnFHOEVPLnZyUWxGckFVT3h6cE9QdXU5THJSWFNnWHQ5LkhOdEhjbE1LU3d4cTZYbVYyTjZcIixcIm1vYmlsZVwiOlwiMTg4ODg4ODg4ODhcIixcImF2YXRhclwiOlwiaHR0cHM6Ly93cGltZy53YWxsc3Rjbi5jb20vZjc3ODczOGMtZTRmOC00ODcwLWI2MzQtNTY3MDNiNGFjYWZlLmdpZlwiLFwibmlja25hbWVcIjpcIlwiLFwiaW50cm9kdWN0aW9uXCI6XCJcIixcInN0YXR1c1wiOjEsXCJjcmVhdG9yXCI6XCLns7vnu59cIixcInJvbGVzXCI6W3tcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJuYW1lXCI6XCLnrqHnkIblkZhcIixcImtleXdvcmRcIjpcImFkbWluXCIsXCJkZXNjXCI6XCJcIixcInN0YXR1c1wiOjEsXCJzb3J0XCI6MSxcImNyZWF0b3JcIjpcIuezu-e7n1wiLFwidXNlcnNcIjpudWxsLFwibWVudXNcIjpudWxsfV19In0.zuc7z6XPqCDUi4efgGb2FKlnUIEcOujqzps51w47Xuw' \ --header 'User-Agent: apifox/1.0.0 (https://www.apifox.cn)' \ --header 'Cookie: gowebmini-Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTIwODk2NTYsImlkZW50aXR5IjoxLCJvcmlnX2lhdCI6MTY0ODg4OTY1NiwidXNlciI6IntcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS43NDUrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkNnFHOEVPLnZyUWxGckFVT3h6cE9QdXU5THJSWFNnWHQ5LkhOdEhjbE1LU3d4cTZYbVYyTjZcIixcIm1vYmlsZVwiOlwiMTg4ODg4ODg4ODhcIixcImF2YXRhclwiOlwiaHR0cHM6Ly93cGltZy53YWxsc3Rjbi5jb20vZjc3ODczOGMtZTRmOC00ODcwLWI2MzQtNTY3MDNiNGFjYWZlLmdpZlwiLFwibmlja25hbWVcIjpcIlwiLFwiaW50cm9kdWN0aW9uXCI6XCJcIixcInN0YXR1c1wiOjEsXCJjcmVhdG9yXCI6XCLns7vnu59cIixcInJvbGVzXCI6W3tcIklEXCI6MSxcIkNyZWF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIlVwZGF0ZWRBdFwiOlwiMjAyMi0wMy0zMVQwOTozODo0NS4zNDIrMDg6MDBcIixcIkRlbGV0ZWRBdFwiOm51bGwsXCJuYW1lXCI6XCLnrqHnkIblkZhcIixcImtleXdvcmRcIjpcImFkbWluXCIsXCJkZXNjXCI6XCJcIixcInN0YXR1c1wiOjEsXCJzb3J0XCI6MSxcImNyZWF0b3JcIjpcIuezu-e7n1wiLFwidXNlcnNcIjpudWxsLFwibWVudXNcIjpudWxsfV19In0.zuc7z6XPqCDUi4efgGb2FKlnUIEcOujqzps51w47Xuw' \ --header 'Content-Type: application/json' \ --data-raw '{     "username": "test",     "mail": ***@***.***",     "jobNumber": "56",     "mobile": "13667766612",     "nickname": "测试用户",     "status": 1,     "roleIds": [2],     "departmentId": [],     "departments": "",     "introduction": "测试用户",     "postalAddress": "河南省南阳市",     "avatar": "http://dummyimage.com/100x100",     "password": "",     "givenName": "测试用户",     "position": "测试" }'
 
你可以将用户数据做一个遍历，然后请求接口进行批量导入！

**Comment by eryajf** [comment]
谢谢
