### ISSUE TITLE
2022-08-11 18:06:13 DEBUG middleware/AuthMiddleware.go:113 github.com/eryajf/go-ldap-admin/middleware.unauthorized JWT认证失败, 错误码: 401, 错误信息: 密码错误🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#109]
### 你使用了哪个版本？ | Which version did you use?
使用docker部署的
使用镜像：
 docker.mirrors.sjtug.sjtu.edu.cn/eryajf/go-ldap-admin-server:latest

刚部署好的环境
admin账号无法登录
日志中提示：
`2022-08-11 18:06:13 DEBUG middleware/AuthMiddleware.go:113 github.com/eryajf/go-ldap-admin/middleware.unauthorized JWT认证失败, 错误码: 401, 错误信息: 密码错误

`
![image](https://user-images.githubusercontent.com/30789071/184111733-927932c9-5105-4981-849e-b2cfdd6eb565.png)
![image](https://user-images.githubusercontent.com/30789071/184111764-b51a9438-b316-4fab-9d68-f5c088edc1fc.png)

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by aosolao** [comment]
已解决，是被同事改了，请忽略
