### ISSUE TITLE
🐛 编辑用户失败

### ISSUE THREAD

**Issue by mmweiyin** [eryajf/go-ldap-admin#111]
#### 您使用的版本？ | Your usage version?
docker-compose部署的
#### 您遇到了什么问题？ | What are your problems?

1.编辑用户时弹出提示“更新用户失败在LDAP更新用户失败：LDAP Result Code 32 "No Such Object" 。未更新成功

2.新增用户时弹出提示“添加用户失败AddUser向LDAP创建用户失败：LDAP Result Code 32 "No Such Object":" 。 新增成功了。

**Comment by eryajf** [comment]
您好 @mmweiyin👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @mmweiyin. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 编辑用户时弹出提示“更新用户失败在LDAP更新用户失败：LDAP Result Code 32 "No Such Object"

猜测是这个用户在ldap里没有，你可以看下。



> 新增用户时弹出提示“添加用户失败AddUser向LDAP创建用户失败：LDAP Result Code 32 "No Such Object":" 。

这个报错怎么感觉是你的配置文件有问题

**Comment by eryajf** [comment]
> 还是同样的问题

是指添加用户的时候报上边的错误吗

**Comment by mamacmm** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by eryajf** [comment]
> 我也遇到了同样的问题，请问解决了吗

需要给出具体操作的上下文
