### ISSUE TITLE
🚀 一些功能。。。 | 

### ISSUE THREAD

**Issue by DylanBack** [eryajf/go-ldap-admin#112]
我想在你这个日志里增加一个trace id，标识每一次请求，请问该如何添加

**Comment by eryajf** [comment]
您好 @DylanBack👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @DylanBack. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
可以在中间当中添加

**Comment by DylanBack** [comment]
新手，不知道怎么加，就告知

**Comment by eryajf** [comment]
这个不是三言两语的事情，还是建议研究一下这块儿
