### ISSUE TITLE
🙋 问题交流。。。 | [Question] 关于配置文件中的  ldap用户OU 配置如何配置？

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#113]
## Question Report

关于配置文件中的 用户OU 配置不大理解。
 user-dn 如何配置？
是不是我应该事先创建好ou=people，然后才能创建用户？

初始密码在什么场景下会使用到？

```
  # ldap用户OU
  user-dn: "ou=people,dc=eryajf,dc=net"
  # ldap用户初始默认密码
  user-init-password: "123456"
```

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 是不是我应该事先创建好ou=people，然后才能创建用户？

是这样的，用户ou就是指定用户所在的组织，需要在配置文件中指定。

初始密码在创建用户时，如果没有填写密码，则默认密码会是这个。如果你有同步第三方平台用户的需求，那么用户同步过来之后，默认密码用的也是这个
