### ISSUE TITLE
🐛 一些问题。。。 | [Bug] 新建用户部门显示不正常

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#114]
#### 您使用的版本？ | Your usage version?
v0.5.3

docker镜像：
eryajf/go-ldap-admin-server:2022-08-06_03-23
eryajf/go-ldap-admin-ui:2022-07-28_08-35
#### 您使用的场景？ | Your usage scenarios?
在k8s中部署
#### 您做了什么操作？ | What did you do?
在”用户管理“页面，新建用户
#### 您遇到了什么问题？ | What are your problems?
新建用户的部门显示不正常，部门出现了两次，但对该用户点击编辑再保存后就正常了。
#### 您期望的结果是怎样的？ | What is your expected outcome?
![Snipaste_2022-08-22_16-06-32](https://user-images.githubusercontent.com/30789071/185872484-86e9ea2b-26d3-48d1-828d-454af05b8f5a.jpg)
![Snipaste_2022-08-22_16-06-14](https://user-images.githubusercontent.com/30789071/185872495-2b104bba-9d3b-4062-877f-f1a063fc653d.jpg)

请见截图，”ops_dev"变成了“ops+devops_dev"

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
看起来是个bug，我空的时候debug修复一下
