### ISSUE TITLE
🐛 docker-compose部署在公有云服务器，远程访问ui验证错误 | [Bug] 

### ISSUE THREAD

**Issue by frui85** [eryajf/go-ldap-admin#116]
#### 您使用的版本？ | Your usage version?
lastest

#### 您使用的场景？ | Your usage scenarios?
测试

#### 您做了什么操作？ | What did you do?
docker-compose部署，远端访问

#### 您遇到了什么问题？ | What are your problems?
非本机访问ui， ajax Post请求ip:ports, 报错
![Uploading image.png…]()

#### 您期望的结果是怎样的？ | What is your expected outcome?
前端ui可以配置 ip ，允许远端直接通过Ip:ports 访问测试。或者给出nginx配置代码

**Comment by eryajf** [comment]
您好 @frui85👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @frui85. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
参考： https://github.com/eryajf/go-ldap-admin/discussions/35
以及：http://ldapdoc.eryajf.net/pages/5769c4/#openresty%E9%85%8D%E7%BD%AE
