### ISSUE TITLE
🚀  希望能增加账号使用期限

### ISSUE THREAD

**Issue by lishiren-admin** [eryajf/go-ldap-admin#118]
#### 您使用的场景？ | 1. Your usage scenarios?
中小企业

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
希望能增加账号使用期限

**Comment by eryajf** [comment]
您好 @lishiren-admin👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lishiren-admin. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
