### ISSUE TITLE
JWT认证失败, 错误码: 401, 错误信息: 密码错误 🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by peytonyip** [eryajf/go-ldap-admin#121]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
k8s 部署，镜像：docker.mirrors.sjtug.sjtu.edu.cn/eryajf/go-ldap-admin-server 和 peytonyip/go-ldap-admin-ui
后端配置文件关于 jwt 配置 部分没有改动，前端按照 [修改配置](http://ldapdoc.eryajf.net/pages/5769c4/#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE) 把 Dockerfile 里面相关的部分改为了对应的域名，重新构建了镜像
### 预期行为 | Expected behavior
正常登录
### 实际行为 | Actual behavior
无法登录，后端日志显示：JWT认证失败, 错误码: 401, 错误信息: 密码错误

ps：顺便想问下，jwt key 部分是否可以自定义？

**Comment by eryajf** [comment]
您好 @peytonyip👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @peytonyip. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 无法登录，后端日志显示：JWT认证失败, 错误码: 401, 错误信息: 密码错误

登陆401就是密码错了，可以看下是不是配置文件的密码没有应用到容器当中。

我看了下，目前jwt key应该还没有用上，所以自定义的意义不大。

**Comment by peytonyip** [comment]
看漏了文档 [实操部分](http://ldapdoc.eryajf.net/pages/adb742/#%E5%AE%9E%E6%93%8D)，原来登录的密码是要用 LDAP 的 admin 密码，我一开始登录还是用了默认的 123456 。现在测试用镜像 docker.mirrors.sjtug.sjtu.edu.cn/eryajf/go-ldap-admin-ui 也没有问题了，谢谢。
