### ISSUE TITLE
🐛 修改邮箱的一个BUG

### ISSUE THREAD

**Issue by ForLina** [eryajf/go-ldap-admin#122]
最新版本  人员管理 -> 用户管理，修改用户信息，当修改用户信息提交返回失败后，再次点击修改用户信息，无法编辑字段，任何输入都不响应。

**Comment by eryajf** [comment]
您好 @ForLina👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ForLina. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
我这边没有复现这个问题呢，我也尝试做了一次失败的修改，报错之后，再次点击编辑也没有问题呢

**Comment by ForLina** [comment]
操作流程

**Comment by eryajf** [comment]
管理员邮箱的确无法修改，最新的版本已经支持自定义邮箱后缀，所以这里不需要修改了
