### ISSUE TITLE
同步飞书部门失败

### ISSUE THREAD

**Issue by ForLina** [eryajf/go-ldap-admin#124]
最新版本 使用thrid_tools校验飞书配置没问题，能看到部门人员 ，但是web同步的时候返回sql 错误
![image](https://user-images.githubusercontent.com/6121685/189262670-3505db70-6116-4711-ba83-8efc87159beb.png)
我没理解错误的话，应该是点击同步飞书部门会把全部飞书的部门创建出来？

**Comment by eryajf** [comment]
您好 @ForLina👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ForLina. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个并不是报错，只是判断这条记录是否存在。按说你应该已经能看到同步后的数据了吧。

**Comment by ForLina** [comment]
目前没看到 如果能看到的话 是在root 下，还是在飞书root下呢？目前两者都没有。

**Comment by eryajf** [comment]
如果同步成功，应该在feishu下，没有的话，再次点击同步，然后F12看看接口返回了什么错误

**Comment by ForLina** [comment]
![image](https://user-images.githubusercontent.com/6121685/189265213-62ca477c-cf24-4dde-80ca-e3f4086e5c53.png)

**Comment by ForLina** [comment]
![image](https://user-images.githubusercontent.com/6121685/189265444-f003e840-c921-49b8-84b2-2e233da8be41.png)
每次同步都这个错，我理解是否是飞书的请求结果没有成功写入数据库？

**Comment by eryajf** [comment]
看上边的截图，似乎没有出错。
看起来你的group_dn配置有点问题的样子。

**Comment by ForLina** [comment]
![image](https://user-images.githubusercontent.com/6121685/189265822-691302c6-011d-40fc-92c4-461fe441b0a7.png)
这个是默认的，没有修改过。还是说别的地方错了？

**Comment by eryajf** [comment]
你先手动创建一个分组，看看能不能创建成功

**Comment by ForLina** [comment]
![image](https://user-images.githubusercontent.com/6121685/189266470-422a022f-902a-40a2-afab-9ffb4b385bdb.png)
可以

**Comment by eryajf** [comment]
那奇怪了，没有报错，也没有执行，不太科学。感觉还是哪里不对

**Comment by baifuwa** [comment]
飞书部门同步后，部门名称是一串字符串。

**Comment by eryajf** [comment]
> 飞书部门同步后，部门名称是一串字符串。

通过调整 映射关系中的部门名称字段 进行调整
