### ISSUE TITLE
🙋 问题交流。企业微信同步不到手机号,邮箱,目前看文档从2022年6月20日之后不能这样获取信息

### ISSUE THREAD

**Issue by anke1938** [eryajf/go-ldap-admin#127]
## Question Report
企业微信同步问题,求问有解决办法吗

### 你使用了哪个版本？ | Which version did you use?
当前时间的latest docker-compose启动的

### 预期行为 | Expected behavior
获取到企业微信用户的所有信息

### 实际行为 | Actual behavior
只获取到了简单的信息

![企业微信20221111-170410](https://user-images.githubusercontent.com/26757566/201305399-65d13721-81ee-443c-9053-1865b6b566bc.png)

### 原因分析（如果可以） | Cause analysis (if possible)
官方限制... 从2022年6月20号20点开始，除通讯录同步以外的基础应用（如客户联系、微信客服、会话存档、日程等），以及新创建的自建应用与代开发应用，调用该接口时，不再返回以下字段：头像、性别、手机、邮箱、企业邮箱、员工个人二维码、地址，应用需要通过[oauth2手工授权](https://developer.work.weixin.qq.com/document/path/91335#15232)的方式获取管理员与员工本人授权的字段。

### 问题重现步骤 | Steps to reproduce the problem
nope

**Comment by eryajf** [comment]
您好 @anke1938👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @anke1938. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个问题我这边没有复现，邮箱，手机号之类的信息还是可以正常拿到的
你可以看下是不是应用的权限，可见范围设置的问题。

**Comment by anke1938** [comment]
这个您得用新的企业应用做这些才会复现,之前的应用不受影响...  我目前把手机号之类的字段映射为用户名解决..

**Comment by eryajf** [comment]
> 新的企业应用

新的企业应用是指我要新建一个是么

**Comment by eryajf** [comment]
问题复现了，额，怎么说呢，企业微信这升级，也是没谁了，我回头会抽空看看怎么解决这个问题，我看 https://github.com/wenerme/go-wecom/issues/3 这里作者还没有打算跟进更新

**Comment by eryajf** [comment]
> 会导致用户的cn变为中文名称

#128  这个PR已修复这个问题，我会打在下次版本中，你重新拉取latest镜像就OK了

**Comment by eryajf** [comment]
> 好的 感谢 这个PR是我逼着同事提的 hhhh

优秀
