### ISSUE TITLE
🚀 员工信息部门发生改变同不到goldapadmin平台

### ISSUE THREAD

**Issue by xueanguo** [eryajf/go-ldap-admin#130]
#### 您使用的场景？ | 1. Your usage scenarios?
员工的信息发生改变，比如员工号或者职务发生改变。
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
员工的信息发生改变，比如员工号或者职务发生改变，能够同步到goldapadmin平台以及后面的ldap

**Comment by eryajf** [comment]
您好 @xueanguo👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @xueanguo. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
