### ISSUE TITLE
同步企业微信部门（用户）成功？还是失败？

### ISSUE THREAD

**Issue by codeofxhb** [eryajf/go-ldap-admin#132]
> 同步企业微信部门（用户）时：
![image](https://user-images.githubusercontent.com/50572180/205859495-80d53e72-fca1-4143-ada1-d8c2ad19b2eb.png)
![image](https://user-images.githubusercontent.com/50572180/205859688-0eda067d-72b2-47de-aaf7-dee8e21f20c5.png)

*这应该是失败了吧，但是没有任何报错或者反馈日志；虽然提示成功了，post也是返回200，但是没有看到同步后的内容；*

> 这是我的平台企业微信配置
![image](https://user-images.githubusercontent.com/50572180/205860457-a491f2a5-e0d2-408e-808a-0e21b43b1814.png)

> 企业微信后台创建的应用也添加了可信IP
![image](https://user-images.githubusercontent.com/50572180/205861638-b89f93b7-a63d-4fff-93b7-8347391b288a.png)

> 我还想到一个文档中说的配置权限，在企业微信中，这个配置权限具体要配置什么。。

**Comment by eryajf** [comment]
您好 @codeofxhb👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @codeofxhb. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
好像最近企业微信接口有过改版，导致原来的接口拿不到完整的用户数据，这个问题需要底层依赖库解决，得等一等，如果那边不解决，我再看看怎么处理
