### ISSUE TITLE
简单使用后的一些bug反馈

### ISSUE THREAD

**Issue by WaterSunMount** [eryajf/go-ldap-admin#136]
#### 您使用的版本？ | Your usage version?
docker-compose部署的0.5.3

#### 您遇到了什么问题？ | What are your problems?
1. 后端msg信息,前端没有捕获,具体现象是
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/75781948/208007485-1fd131f9-c7fb-4d0f-a806-d852d07a412f.png">
2. 企业微信好像更新了,需要添加可信域名和ip
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/75781948/208007659-e3203079-d46e-4239-b5a3-63ea1b1b09b6.png">
新建应用那里也要添加
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/75781948/208007914-9d719a81-7716-449b-be9c-c3c59afe7b5c.png">
3. 不确定是不是微信更新了,引起的错误,手机号和邮箱不会同步,都是默认的,因为数据库手机号是唯一约束的,所以会同步失败
<img width="917" alt="image" src="https://user-images.githubusercontent.com/75781948/208008093-c53e7336-f21c-4fd4-9f97-474afbd806cd.png">
哦,对了,字段映射我也配置了
<img width="503" alt="image" src="https://user-images.githubusercontent.com/75781948/208008296-fcb067eb-d8b8-4032-9a99-7da2928be2bc.png">
4. 手机号正则匹配不正确,184开头的手机号不能匹配
<img width="672" alt="image" src="https://user-images.githubusercontent.com/75781948/208010418-c3c53278-06b9-421e-9683-aa483dc1d261.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/75781948/208010541-69b642bf-6c2d-4da4-96f2-fce4524526a6.png">

# 最后补充一句,微信的东西就是尼玛垃圾,天天更新,微信小程序,微信支付,他们随便更新,累死一堆程序员

**Comment by eryajf** [comment]
您好 @WaterSunMount👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @WaterSunMount. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
都是非常靠谱的反馈。
1，第一个是前端做的时候就没有加错误判断，这个最近我空了优先把这个处理一波。
2，这个应该是最近企业微信的更新，随后有空我再走下这块儿的流程。
3，确实是企业微信有更新，这两个字段之前的接口不给返回了，这个也是需要处理的。
4，关于手机号校验的问题，我刚刚又补充了一下知识，觉得使用宽松的校验更为合理，于是现在已经改成1开头的11位数字了。
你最后补充的那一句，我表示赞同。

**Comment by guanbear** [comment]
高质量反馈，赞一个！

**Comment by eryajf** [comment]
@WaterSunMount 
前端错误处理，已经全局加上了。手机号校验也都加上了。企业微信的同步，暂时没有精力做，希望能有小伙伴提PR
