### ISSUE TITLE
我在使用docker-compose 只部署了前后端 连接我之前的ldap 在初始化的时候显示可以连接到ldap 但是当我同步ldap信息的时候没有报错也没有同步到用户 看日志 也没有有用的信息 请问可以帮忙看看

### ISSUE THREAD

**Issue by lixiaokun777** [eryajf/go-ldap-admin#139]
![91e27ba3e020eba74d3b606276ebceb](https://user-images.githubusercontent.com/57617854/208386864-b43df7e0-e1c0-4257-87e1-e7436ea1ea89.png)
![a5e011ebdbe72a505a584d6c1000585](https://user-images.githubusercontent.com/57617854/208386863-b7fd3a25-ce10-4aef-8afa-e54b14692de5.png)
![b6299c943d2ed88752039b769351a00](https://user-images.githubusercontent.com/57617854/208386866-ce080a5f-8d13-4e08-922c-21be0d2fc652.png)

**Comment by eryajf** [comment]
您好 @lixiaokun777👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lixiaokun777. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by lixiaokun777** [comment]
![d62fa7f1cd75e3c4a241c0fd354bc63](https://user-images.githubusercontent.com/57617854/208387592-b59da141-4771-4946-a1bc-2e007ab95aa0.png)

**Comment by eryajf** [comment]
我的建议是你先compose拉起体验一下，然后再对接到自己的ldap，这样能知道配置中的信息都是什么意思。

另外 http://ldapdoc.eryajf.net/pages/adb742/  这篇文档讲了配置成自定义的域名的一些注意事项

**Comment by eryajf** [comment]
目前前端对错误处理有一些问题，你可以打开检查，然后再次请求，就能看到接口的错误信息了

**Comment by lixiaokun777** [comment]
我通过前端查看 返回的是200 也没有接口的一个错误信息。。
![1671442424950](https://user-images.githubusercontent.com/57617854/208392927-a384308d-eb92-4ca8-9aec-7242b7a94bf1.png)
