### ISSUE TITLE
🧐功能或BUG优先级，欢迎大家投票

### ISSUE THREAD

**Issue by eryajf** [eryajf/go-ldap-admin#14]
大家可以通过点红心的方式，我们也会以此作为功能优先级的参照，从而进行对应的开发安排！

**Comment by eryajf** [comment]
#9 新增或修改数据时，数据添加的时机问题

**Comment by eryajf** [comment]
#11 企业微信同步组织架构

**Comment by eryajf** [comment]
#12 飞书同步组织架构

**Comment by eryajf** [comment]
#13 依赖版本的安全问题

**Comment by eryajf** [comment]
#31   支持只同步钉钉架构里面的某些部门的员工

**Comment by eryajf** [comment]
#32  支持动态关联企业IM与平台之间的字段

**Comment by ilanni2460** [comment]
同步已有的ldap这个功能可以提前啊，哈哈😊

**Comment by eryajf** [comment]
> 同步已有的ldap这个功能可以提前啊，哈哈😊

该功能已支持，参考 #60

**Comment by panhaitao** [comment]
MFA 验证支持，我觉得这个安全需求应该很多吧

**Comment by 370569218** [comment]
希望添加有度同步功能，很多企业内部都使用私有化部署的有度https://youdu.im/

**Comment by eryajf** [comment]
> openldap直接使用mysql做为backend

我不太了解openLDAP是否有这个功能，目前go-ldap-admin平台的设计是旁路部署的MySQL，然后将数据双向同步

**Comment by eryajf** [comment]
> > > openldap直接使用mysql做为backend
> > 
> > 
> > 我不太了解openLDAP是否有这个功能，目前go-ldap-admin平台的设计是旁路部署的MySQL，然后将数据双向同步
> 
> 当我仔细把你代码翻了一遍，一个大写的WHAT ！和你首页上go-ldap-admin、OpenLdap同时连着一个MySQL的图片相差有点大哈～～ 。 不过你利用docker把 openldap和 phpldapadmin 启动起来，的确十分方便，帮我节省了大量的配置时间。 最后我参考你的思路，直接用JLDAP做了类型的一个功能 。（企业微信现在不支持同步通讯录电话、邮箱信息了，不然直接用go-ldap-admin） 这个项目很棒，THANK YOU！

哈哈，或许你可以再品品那张图，我感觉表达的也挺清楚的。我在官方文档里也专门对这张图做过介绍说明。

企微的这个变化，不少人反馈过，而我使用之前的应用测过，没有问题，也许是他对新的应用有调整。以后有时间了我再新建应用测试一下。

感谢肯定。

**Comment by AlongWY** [comment]
需要支持 PosixUesr

**Comment by apple524** [comment]
希望能支持微软AD域控同步

**Comment by johnny-jiang** [comment]
email配置里不支持ssl吗？改成ssl的端口会直接报 EOF 的错误

**Comment by TheWaveLab** [comment]
可以考虑增加主从同步和数据引用功能

**Comment by ccbuildpro** [comment]
> > 希望能支持微软AD域控同步
> 
> 真的希望有这个，能够从ad域控同步，或者能同步至ad域控。企业一般管理Windows相关首选都是ad。

bug还是挺多的，你可以fork一个自己改改
