### ISSUE TITLE
我在使用同步部门的时候 我发现他并没有完全的同步 少了一个主要的部门没有同步 然后我在同步ldap用户的时候 只能同步一到俩个用户 我很奇怪这是什么原因

### ISSUE THREAD

**Issue by lixiaokun777** [eryajf/go-ldap-admin#140]
![6ad107c73a397720671a5028b7b35fc](https://user-images.githubusercontent.com/57617854/208563045-861d5b5b-6c68-4362-b135-6852016347e7.png)
这是ldap所有的分组
![bfcf8c40372b92a56a1a4f027bb7a55](https://user-images.githubusercontent.com/57617854/208563083-5555d083-c342-4169-b04d-e4d2757e1f51.png)
同步分组少了一个people
![53ce18fedc7ae8fd968c0d22750a9e3](https://user-images.githubusercontent.com/57617854/208563132-95699b1d-c805-4975-9e6d-f8e1f329f6a6.png)
这个是s所有的用户
![ad6fb73de54c499b4c39829576bd4d1](https://user-images.githubusercontent.com/57617854/208563185-1a4e7514-5f6c-49e1-9a2a-8a60757897ee.png)
同步以后只有一到俩个用户  我把同步到的用户删除了 再次同步出现的还是一到俩个别的不同的用户
![4494ac34e0318412c5877ac99d68814](https://user-images.githubusercontent.com/57617854/208563276-e4c48fa3-7c1f-4a75-8fd4-37688e1e68ba.png)

**Comment by eryajf** [comment]
您好 @lixiaokun777👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lixiaokun777. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by lixiaokun777** [comment]
准确的说每次只能同步一个用户

**Comment by eryajf** [comment]
目前我阳之中，没法看这些问题，如果你能看懂代码，可以先自行排查一下
