### ISSUE TITLE
请问go-ldap-admin可与管理多个组吗 俩个组有相同的用户名

### ISSUE THREAD

**Issue by lixiaokun777** [eryajf/go-ldap-admin#142]
<img width="797" alt="1672710022" src="https://user-images.githubusercontent.com/57617854/210290336-4b9a0341-cfd2-44ed-ada5-dbda7f6e92b1.png">
比如这俩个组 里边有很多相同的用户名 是否可以使用一个go-ldap-admin 平台进行管理

<img width="827" alt="1672710178(1)" src="https://user-images.githubusercontent.com/57617854/210290450-6d2290e2-ad49-47a8-acae-1a146a9e34d7.png">
我在配置文件里只写了 ou=People

**Comment by eryajf** [comment]
您好 @lixiaokun777👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lixiaokun777. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这里管理思路是这样的，我大概描述一下：

- 固定的`ou=people,dc=eryajf,dc=net`，这里统一存放所有的用户，以inetOrgPerson作为objectCLass。
- 除此之外的，都可以被认为是ldap中的分组，而不同的分组存放同样的用户，我理解成应该是同一个用户，在不同的分组之下，这是支持的。
