### ISSUE TITLE
🚀 一些功能。。。 | [Feature]Some feature...

### ISSUE THREAD

**Issue by hacklinshell** [eryajf/go-ldap-admin#147]
#### 您使用的场景？ | 1. Your usage scenarios?
中小企业
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
希望增加当禁止admin用户登录后，能够恢复admin用户登录，

使用bug问题如下：
测试使用了一下，发现当直接在ldapadmin中进行用户添加创建时候，同步到UI的时候，如果已经删除了用户，UI界面就无法删除已经不存在的用户了。

**Comment by eryajf** [comment]
您好 @hacklinshell👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @hacklinshell. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by hacklinshell** [comment]
嗯，那可以理解，但是有一个新的需求，
在使用go-ldap-admin添加用户的时候，希望能够增加一个更多选项，来兼容go-ldap-admin本身没有的一些属性，比如ldapadmin添加用户的时候，指定home的路径，获取其他属性，可以自己选择增加用户什么属性

**Comment by hacklinshell** [comment]
> 

这个需求主要因为，go-ladp-admin创建的用户无法直接登录安装有ldap client 客户端的Linux服务器，  看了是是缺少posixAccount 和 shadowAccount Objectclass

**Comment by hacklinshell** [comment]
我是先使用go-ldap-admin 创建用户，然后再使用ldapadmin 创建一个用户，对比下，把缺少的自动都手动加上后，然后就可以登录了， 强烈建议增加上 shadowAccount  posixAccount top 的Objectclass，

**Comment by eryajf** [comment]
目前设计的用户属性全部在：inetOrgPerson，你提到的这两个，可能需要不少代码调整来适配，如果你了解go源码，可进行二次调整
