### ISSUE TITLE
🐛 钉钉同步用户问题 | [Bug] Some problem...

### ISSUE THREAD

**Issue by ericwong-gd** [eryajf/go-ldap-admin#151]
#### 您使用的版本？ | Your usage version?
latest
#### 您使用的场景？ | Your usage scenarios?
同步钉钉组织架构
#### 您做了什么操作？ | What did you do?
同步钉钉用户信息
#### 您遇到了什么问题？ | What are your problems?
![image](https://user-images.githubusercontent.com/34854048/218918751-ea3770a6-d9a6-4f34-9035-de742afdc53a.png)
钉钉删除了一个用户，同步钉钉用户信息显示此错误
做完操作后，检查用户还是正常状态，ldap也有此用户的存在

#### 您期望的结果是怎样的？ | What is your expected outcome?
钉钉删除用户后，同步用户信息，相关用户显示禁用

**Comment by eryajf** [comment]
您好 @ericwong-gd👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ericwong-gd. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
能否帮忙查看下， 这个用户在数据库中是否存在，如果存在，那么这个用户的  userDN 字段是多少，看看跟ldap里的DN是否一致

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/33259379/218921145-33091642-cae7-4d70-87e3-113952df04d5.png">

从这个步骤中来看，应该就是数据库中存的DN跟ldap里的DN不一致，导致删除失败，然后禁用的操作也就没再执行了

**Comment by ericwong-gd** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/34854048/218923835-e76fa891-835c-4784-ab69-a2e0352cb20b.png">

![image](https://user-images.githubusercontent.com/34854048/218923975-38b3f958-61a6-4fe2-a8a9-5b3567da9269.png)

数据库是存在这个用户的，DN和ldap是一样

**Comment by ericwong-gd** [comment]
找到问题了，之前手动禁用过用户

现在把禁用的用户重新启用，然后再同步就正常了

**Comment by eryajf** [comment]
OK
