### ISSUE TITLE
安装后使用admin登录web管理页面报错没有权限

### ISSUE THREAD

**Issue by xukrlong** [eryajf/go-ldap-admin#159]
按照http://ldapdoc.eryajf.net/pages/866885/#%E5%AE%89%E8%A3%85%E6%95%B0%E6%8D%AE%E5%BA%93该页面的教程，搭建完成后，能够打开web页面，但使用admin（确定密码无误）登录时报错“没有权限”，/usr/local/go-ldap-admin/logs下无日志输出。当故意使用错误的用户名或密码登录时，/usr/local/go-ldap-admin/logs下有报错日志

环境：
openldap-2.4.44-25.el7_9.x86_64
openldap-servers-2.4.44-25.el7_9.x86_64
CentOS Linux release 7.4.1708 (Core) 

![image](https://user-images.githubusercontent.com/126227409/222089332-212b95ac-4da1-43f5-8360-6fa4eb54b03c.png)

**Comment by eryajf** [comment]
您好 @xukrlong👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @xukrlong. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
最近还有一个同学参照这个文档没能走下去的，前期部署体验，我还是比较推荐通过docker-compose一键拉起进行体验。从你提供的信息来看，感觉应该就是数据初始化的问题，可能是有什么数据没有初始化到位。

因为这篇文档是一个项目参与者维护的，我这边目前也没有合适的环境验证，所以不太好回答参照这个文档部署之后遇到的问题。

**Comment by xukrlong** [comment]
好的，那我用docker重新装吧

**Comment by itweixiang** [comment]
文档写的牛头不对马嘴的，我也是遇到了相同的情况，用的是都是最新的镜像，但是外挂了数据库。

数据是mysql5.7的最新版，作为最常用的版本，理所应该不该有兼容性问题。

ldap连接成功，可以排除ldap服务的问题。
![图片](https://github.com/eryajf/go-ldap-admin/assets/40189074/340b13a1-ead5-478f-ac0f-dfd9ad2c9111)


问题1：账户密码不对。

外挂数据库之后，看着创建了一些ddl，但是只有少量的表有数据。最关键的是，系统账号users的这张表，没有生成数据。

既然都能够直接初始化ddl了，为什么不能再创建一下用户这张表的数据？导致一直没法登录，hello world直接卡死了。

如果不支持自动创建ddl、dml的话，那么在代码仓库里面提供一个sql初始化参考也是可以的。事实上你们也是这么做的。

但是你们初始化只初始化了一半。就会让用户以为，自己创建了ddl，哦哦哦，还挺高级的，能自动创建一些数据，哦哦哦那官方自己创建的应该没啥问题。。。但实际上就没法登录。。这就让问题很难排查了，我看了日志，原来是查了users这张表，看着没有数据，所以去代码仓库上找了sql自己执行。。。

问题2：账户没有权限。

![图片](https://github.com/eryajf/go-ldap-admin/assets/40189074/6b067344-f29b-4434-a720-0fef872f4594)


懒得查了，这项目就是让人花时间给所有者测试的，一点用都没有

**Comment by eryajf** [comment]
1，该篇文档开头我就已做过标注与说明，上边回复里也做了说明。

2，自动初始化是完整可用的，正常流程走完，肯定会有用户数据生成的，代码在此：

https://github.com/eryajf/go-ldap-admin/blob/02638f213e8a530c27bfb1f05a8d092dec08fe35/public/common/init_mysql_data.go#L232

3，你没有给这个项目做测试的义务，我也没有需要大家帮忙测试的想法。

4，还是建议你参照docker-compose的文档，一键拉起，历经验证，肯定不会有问题（如有请反馈）。

5，一个项目让人五分钟之内拉起即可体验是其能够让人快速接受的根本，为了达到这一点，我耗费大量的时间与精力，做过大量的工作，而你一开始就舍近求远，以至于走了弯路。

**Comment by itweixiang** [comment]
> 1，该篇文档开头我就已做过标注与说明，上边回复里也做了说明。
> 
> 2，自动初始化是完整可用的，正常流程走完，肯定会有用户数据生成的，代码在此：
> 
> https://github.com/eryajf/go-ldap-admin/blob/02638f213e8a530c27bfb1f05a8d092dec08fe35/public/common/init_mysql_data.go#L232
> 
> 3，你没有给这个项目做测试的义务，我也没有需要大家帮忙测试的想法。
> 
> 4，还是建议你参照docker-compose的文档，一键拉起，历经验证，肯定不会有问题（如有请反馈）。
> 
> 5，一个项目让人五分钟之内拉起即可体验是其能够让人快速接受的根本，为了达到这一点，我耗费大量的时间与精力，做过大量的工作，而你一开始就舍近求远，以至于走了弯路。



十分抱歉，不好意思！

前几天说话不好，很抱歉，这几天我也想了很久，很不应该。

我通过你们docker compose构建了，确实如你所说是可以一键构建的。

我也review了相关的配置，和我外挂mysql的差别。

应是项目自己mysql，my.cnf里面有很多特定的配置，此处未体现与文档中。

导致外挂mysql，初始化数据时，初始化数据不完整。


我是想用外挂mysql的，这样与其他如跳板机等共用mysql，方便管理一些。

但是转念一想，ldap也是一个比较重要的系统，单独一个mysql也是可以理解的。

再次抱歉！

**Comment by eryajf** [comment]
没事儿，误会解开就好了。

有时候我也会连接外置的数据库，这个理论上是没问题的，my.cnf里边大多也都是常规配置，你如果方便的话，可以贴一下你的配置，以及在初始化的时候，是否有报错之类的。

**Comment by dustinyounglee** [comment]
我其实今天也遇到了这个问题，我是很早之前到用户，一直没升级，今天手欠升级了下docker,然后发现重新部署最后版本后，包括核对了数据库字段对比，发现了权限不对。核查了jwt，以及对比了字段后，重启docker，即可解决
