### ISSUE TITLE
🐛 使用IPV6网络环境后端报错

### ISSUE THREAD

**Issue by Doraemonsan** [eryajf/go-ldap-admin#160]
#### 您使用的版本？ | Your usage version?
v0.5.6 
#### 您使用的场景？ | Your usage scenarios?
可行性验证测试
#### 您做了什么操作？ | What did you do?
使用域名解析测试服务器V6地址后登录到前端
#### 您遇到了什么问题？ | What are your problems?
在使用人员管理-分组管理时-同步原LDAP部门功能，页面报错”Request failed with status code 502“，同时后端也抛出大量日志
F12信息:
![image](https://user-images.githubusercontent.com/21234683/222957634-d03a1e67-1c43-4d1f-985a-d06afb63e9f9.png)
后端运行日志：
![image](https://user-images.githubusercontent.com/21234683/222957053-6b81a874-300c-4252-a222-ab166725c26d.png)
#### 您期望的结果是怎样的？ | What is your expected outcome?
点击同步后应正常同步

后附log文件，已隐去IP地址信息
[run.log](https://github.com/eryajf/go-ldap-admin/files/10891670/run.log)

**Comment by eryajf** [comment]
您好 @Doraemonsan👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Doraemonsan. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
由于centos那篇文档是用户贡献文档，我没有做充分的测试，所以建议你通过docker-compose部署体验，相关环境会比较完备一些。目前我手上没有服务器资源，等有了资源之后，我会对那篇文档进行验证。
