### ISSUE TITLE
 [Feature] 修改密码

### ISSUE THREAD

**Issue by Sunshine-JamesHu** [eryajf/go-ldap-admin#161]
#### 您使用的场景？ | 1. Your usage scenarios?
目前有两个问题
一是个人用户在忘记密码的时候可能出现邮箱名差一点，然后A用户输出了B用户的邮箱导致B用户的密码被重置
二是希望能有一个密码定时失效的功能 

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
是否可以使用邮箱验证码的方式去修改密码，而不是直接将修改后的密码发送到邮箱
是否能增加初次登录必须修改密码和定时密码失效的功能

**Comment by eryajf** [comment]
您好 @Sunshine-JamesHu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Sunshine-JamesHu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> A用户输出了B用户的邮箱导致B用户的密码被重置

的确有此问题

> 是否可以使用邮箱验证码的方式去修改密码

是一个很好的思路，我将考虑对此功能支持

> 是否能增加初次登录必须修改密码和定时密码失效的功能

关于初次登陆这个，之前考虑的可能都是通过管理员发布通知这种形式，看起来做到系统上要求似乎更合适。
关于密码定时失效，这个似乎有待商榷，我会考虑这个功能。

**Comment by Sunshine-JamesHu** [comment]
辛苦活菩萨了，爱你，比心。

**Comment by eryajf** [comment]
不敢当，折煞我也😂 感谢打赏

**Comment by Sunshine-JamesHu** [comment]
一杯咖啡而已，小小心意。
我正愁那老古董LDAP怎么用呢，这突然送上门的温暖，怎能寒了开源人的心。
现在这东西确实很好用，但是对于企业级应用来说，稍微欠缺了一点儿，主要是这个密码能重置别人的，没办法上生产。
而且生产堡垒机的密码是一个比较严肃的事情，定时轮换是很有必要的，老哥你再考虑考虑呗。

**Comment by eryajf** [comment]
嗯，我会考量这些功能

**Comment by Sunshine-JamesHu** [comment]
爱你老哥，给你发了一封邮件，你要是感兴趣的话回复我哟。

**Comment by eryajf** [comment]
> 是否可以使用邮箱验证码的方式去修改密码

这个功能已上线，可分别拉取前后端最新的镜像进行体验

**Comment by ixiaoyi93** [comment]
有修改密码的接口吗？

**Comment by eryajf** [comment]
> 有修改密码的接口吗？

关于修改密码提供的能力，请看：http://ldapdoc.eryajf.net/pages/e4b577/
