### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#169]
## Question Report
既然作为管理员登陆的账号，无法在编辑用户信息的页面进行**重置用户**的密码，那么是否可以删除该配置项呢？

### 你使用了哪个版本？ | Which version did you use?
v0.5.8-2023/03/09

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
是指删除这个用户吗？

**Comment by ixiaoyi93** [comment]
> 

把重置密码的按钮或者选项直接去掉，在前端不展示。

**Comment by eryajf** [comment]
> 把重置密码的按钮或者选项直接去掉，在前端不展示。

可以考虑

**Comment by eryajf** [comment]
see this pr: https://github.com/eryajf/go-ldap-admin-ui/pull/40
