### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by TopJohn** [eryajf/go-ldap-admin#170]
请问如何修改dc=eryajf,dc=net，我在配置文件修改完启动报错，想修改成自己公司的组织

**Comment by eryajf** [comment]
您好 @TopJohn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @TopJohn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ixiaoyi93** [comment]
> 请问如何修改dc=eryajf,dc=net，我在配置文件修改完启动报错，想修改成自己公司的组织

贴报错信息吧

**Comment by eryajf** [comment]
> > 请问如何修改dc=eryajf,dc=net，我在配置文件修改完启动报错，想修改成自己公司的组织
> 
> 贴报错信息吧

我猜他应该已经解决了，所以把issue关闭了
