### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#171]
## Question Report

大佬，我想请教一下。从飞书同步用户， 是同步过来之后就立即向同步过来的用户邮箱发送 ldap用户初始默认密码吗？（我想先在技术或者运维部门进行测试联调，但是目前是全量同步用户，为了避免出现同时误认为垃圾邮箱需要确认一下）

### 你使用了哪个版本？
v0.5.8-2023/03/09

### 预期行为 | Expected behavior
无

### 实际行为 | Actual behavior
无

### 原因分析（如果可以） | Cause analysis (if possible)
无

### 问题重现步骤 | Steps to reproduce the problem
无

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
现在用户同步过来之后，不会给用户发送邮件

另外需要注意，同步用户之前，需要先同步分组，这个顺序不要弄错。

希望调试顺利，如有问题，欢迎继续反馈交流

**Comment by ixiaoyi93** [comment]
> 

我们现在HR没有为飞书用户设置邮箱。那我可以理解成，我同步过来之后，可以根据需要开通的用户，补录邮箱？这个发邮件告知用户初始密码，是在哪一步实现的呢

**Comment by eryajf** [comment]
目前没有设计主动给用法发邮件的动作，所以同步过来的用户，他们的初始密码都是一样的，是配置文件当中，下边这条配置信息决定的：
https://github.com/eryajf/go-ldap-admin/blob/53d1948868fa8fe4a56c3dfe2135483eda74a7ef/config.yml#L105

所以如果全量同步了所有的用户，那可以选择人工给公司全员发一封相对正式的邮件，并在里边告知相关注意事项，以及用法。

---

如果没有设置邮箱，可以看看是不是用户确实没有邮箱，一般情况下，应该会有一个字段代表着用户的邮箱的话，如果没有，我比较建议是先在源头数据补上，然后在进行同步，这个地方如果不规范化，后续还是一个麻烦事儿。

选择哪个字段作为用户邮箱，可以通过关系管理那里自定义映射。

**Comment by ixiaoyi93** [comment]
> 

您的意思是，默认的密码设置了。只是没有通知流程，那可以拿着 `user-init-password: "123456" ` 登录，然后重置密码。是这个意思吧？

**Comment by eryajf** [comment]
OK
