### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#172]
#### 您使用的版本？ | Your usage version?
docker latest 镜像.

#### 您使用的场景？ | Your usage scenarios?
同步飞书用户到MySQL以及 LDAP.

#### 您做了什么操作？ | What did you do?
手动创建了分组动态关联，如下：
![image](https://user-images.githubusercontent.com/34268642/226267913-c1aeb699-6d42-43f7-810f-ddc07be28a67.png)

手动创建了用户动态关联，如下：
![image](https://user-images.githubusercontent.com/34268642/226268001-389faaf2-08ba-4448-bee0-c92d1d5beba5.png)

暂时无其他操作.

#### 您遇到了什么问题？ | What are your problems?
![image](https://user-images.githubusercontent.com/34268642/226267404-c63d903d-d668-4273-accb-56ec5ca8129d.png)

点击`同步飞书部门`提示如上图错误信息。文字错误：
```
获取飞书部门列表失败：request Auth#GetTenantAccessToken failed: code: 10003, msg: invalid param
```

#### 您期望的结果是怎样的？ | What is your expected outcome?
能够同步飞书组织架构或者部门信息。

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
看起来是获取飞书信息有问题，可以先用这个工具自行调试一下， 等到数据调试OK的时候，再通过go-ldap-admin进行同步。

工具地址：https://github.com/eryajf/third-tools/tree/main/feishu

**Comment by ixiaoyi93** [comment]
> 看起来是获取飞书信息有问题，可以先用这个工具自行调试一下， 等到数据调试OK的时候，再通过go-ldap-admin进行同步。
> 
> 工具地址：https://github.com/eryajf/third-tools/tree/main/feishu

工具返回的信息：
```
分组信息: &{用户成功部 0x1400030c060 od-9836789f396b8fe822985fb36b225842 a53fb8g64b169327 od-c2ac2465f1fb374677cc45666f12a7c5 ou_de042079888ceefee0f85228c5c9ffa4  4000 [] 36 0x1400012503c false}
分组信息: &{项目运营中心 0x1400030c0c0 od-c2ac2465f1fb374677cc45666f12a7c5 21a384g64ab5d79a od-1a418a0519b5e18eab65d1dd99c824b8 ou_dabd34435f56e0213bf3eb9c78564f45 oc_aa77ad3f2f9a997dc91ba954c9c0d1df 16000 [] 8 0x1400012507a false}
分组信息: &{内容中心 0x1400030c0f0 od-c2ac2465f1fb374677cc45666f12a7c5 2e73734dd8dc76f4 od-685a1b5b70ab9ff1ce608ebe6deb10f8   20000 [] 6 0x140001250c0 false}
```
我没有太明白，这个工具返回的信息，我该如何使用工具返回的信息和我同步部门的报错信息进行调试?还请大佬指点一下，这两个之间的关系。

**Comment by eryajf** [comment]
按说如果使用工具能够正常拿到数据，那项目这边应该也没有问题才对，除非是config.yml当中没有正确配置飞书的配置信息，而且感觉是这个原因的概率挺大的

**Comment by ixiaoyi93** [comment]
> 按说如果使用工具能够正常拿到数据，那项目这边应该也没有问题才对，除非是config.yml当中没有正确配置飞书的配置信息，而且感觉是这个原因的概率挺大的

我的锅，确实配置问题。失误了，失误了
