### ISSUE TITLE
🙋 问题交流。。。 | [Question] 执行 make build-linux 报错

### ISSUE THREAD

**Issue by ZhangZangQian** [eryajf/go-ldap-admin#173]
## Question Report

执行 make build-linux 报错，非 go 开发者，不知道怎么解决

### 你使用了哪个版本？ | Which version did you use?

使用了 v0.5.8 tag 对应的代码

### 预期行为 | Expected behavior

执行成功

### 实际行为 | Actual behavior

报错 

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/113660447/226300522-b51637d7-5f56-47be-9ff1-e10a8a8b665c.png">

### 问题重现步骤 | Steps to reproduce the problem

执行 make build-linux 命令即可，配置了国内镜像。
<img width="494" alt="image" src="https://user-images.githubusercontent.com/113660447/226301091-7b2122c9-988c-43e7-b64a-208dd4a0b72c.png">

**Comment by eryajf** [comment]
您好 @ZhangZangQian👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ZhangZangQian. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ZhangZangQian** [comment]
> 你的go版本是多少

go version go1.20.2 linux/amd64

**Comment by eryajf** [comment]
你尝试把go版本改到1.18试下

**Comment by ZhangZangQian** [comment]
搞定了，好像是网络问题，换了个代理

go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
