### ISSUE TITLE
🐛 关于飞书同步的一些问题

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#174]
#### 您使用的版本？ | Your usage version?
docker-compose  latest 

#### 您使用的场景？ | Your usage scenarios?
同步飞书用户到ldap

#### 您做了什么操作？ | What did you do?
先同步飞书组织架构，能够正常同步；再同步飞书用户，能够正常同步。

#### 您遇到了什么问题？ | What are your problems?
点击“同步飞书用户”之后，发现飞书用户不在对应的部门内。

#### 您期望的结果是怎样的？ | What is your expected outcome?
用户与所在部门应该对应。

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
是指这个用户要在对应的分组下边对吧，代码当中针对这块儿是已经做了处理的，你可以在go-ldap-admin管理后台看下分组里是否有对应的用户。

**Comment by ixiaoyi93** [comment]
> 是指这个用户要在对应的分组下边对吧，代码当中针对这块儿是已经做了处理的，你可以在go-ldap-admin管理后台看下分组里是否有对应的用户。

![image](https://user-images.githubusercontent.com/34268642/226316404-cd2c9adf-8660-4964-b393-763f61824799.png)
没有呢？甚情况，大佬。

**Comment by eryajf** [comment]
这里外层是分组，点击右侧的齿轮，会进入到分组里边，里边能够看到分组里对应的用户

**Comment by ixiaoyi93** [comment]
> 这里外层是分组，点击右侧的齿轮，会进入到分组里边，里边能够看到分组里对应的用户

看到了，这个在ldap里面不能对应嘛？
![image](https://user-images.githubusercontent.com/34268642/226325823-75755f9b-08d7-452a-8332-4c4b9e3cc49a.png)
我看到了用户了，这个不能只在部门下面展示吗（那种树形结构展示）？这是一种什么现象呢？

**Comment by eryajf** [comment]
是对应的，但是你的这个截图我倒是真的没有看出来，如果你是用docker-compose部署的，那方便的话，从phpldapadmin那里看下，看看这个分组里的用户信息，是否能够跟go-ldap-admin对应上。

> 另外你这边截图，请注意数据脱敏。

**Comment by ixiaoyi93** [comment]
> 是对应的，但是你的这个截图我倒是真的没有看出来，如果你是用docker-compose部署的，那方便的话，从phpldapadmin那里看下，看看这个分组里的用户信息，是否能够跟go-ldap-admin对应上。
> 
> > 另外你这边截图，请注意数据脱敏。

![image](https://user-images.githubusercontent.com/34268642/226500003-137725bf-aafa-4d49-af12-8c62ac4603ad.png)
这个也是只有部门信息，部门下面没有用户，用户都在 `ou=people` 下面。甚情况？

**Comment by eryajf** [comment]
这是正常的，你需要阅读一下这篇文档：http://ldapdoc.eryajf.net/pages/5683c6/

了解一下当前平台对接openLDAP的设计思路。

**Comment by ixiaoyi93** [comment]
> 这是正常的，你需要阅读一下这篇文档：http://ldapdoc.eryajf.net/pages/5683c6/
> 
> 了解一下当前平台对接openLDAP的设计思路。

这个文档我看了，只是有些地方没有想明白。如果是这样的设计，感觉同步到ldap 的组织架构没啥意义，我完全只同步用户就行。毕竟在ldap里面用户在 `ou=people,dc=eryajf,dc=net` 下面存储。而且你在文档中也说明`简单一句话讲就是，ou无法添加人，cn下可以添加人，使用的建议是，顶级的菜单建议使用ou，往下的知道里边会有人的可以使用cn`。截图如下：
![image](https://user-images.githubusercontent.com/34268642/226502018-2181cb31-e0e2-497d-b6b8-f3c2f1365bfa.png)
还请大佬解惑。

**Comment by eryajf** [comment]
你这里算是两个问题，我一一作答。
- 第一个：为什么有了全部的用户，还要同步组织架构的分组呢。
关于这个问题，其实不同步也行，但是对于ldap来说，其实外部系统连接的时候，未必全部都是基于全员来认证的。举个例子，比如你的Jenkins系统，配置ldap连接的时候，其实是没必要把配置指向到`ou=people,dc=eryajf,dc=net`这个全员的，往往是指向到技术那个大分组就OK了，这样就能限制只在技术分组里的人才能登陆Jenkins这个系统，这只是举了一个小例子，其实还有很多灵活地用户。你看看这篇文档，大概就能理解这两块儿的用法了：https://wiki.eryajf.net/pages/3416.html

- 第二个：ou无法添加人，cn下可以添加人
这个问题其实不是go-ldap-admin平台制定的规则，而是openLDAP给这个objectClass本身做的功能限制。关于这块儿，你可以看看这篇文档来辅助理解：http://ldapdoc.eryajf.net/pages/a5328b/
