### ISSUE TITLE
🚀 重名用户处理不够友好，建议通过数字填充

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#175]
#### 您使用的场景？ | 1. Your usage scenarios?
飞书同步到go-ldap-admin

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
举例，比如有2个名叫张三的同事。用户名“zhangsan”被使用的时候，可以自动使用数字填充。比如第二个张三的用户名就叫“zhangsan1”或者“zhangsan2”。

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
关于这个问题，目前没有太好的方案，是不是应该在源头就解决掉呢，如果源头上两个人的 custom_name_pinyin 是一样的值，那程序这边也不好判断这俩人是不是一个人，虽然可以通过其他辅助字段来判断。

我们之前源头上是这样做的，张三先入职，那就是张三，如果再来个技术部的张三，他的名字就会叫 张三-技术部。
