### ISSUE TITLE
🚀 一些功能。。。 | [Feature]Some feature...

### ISSUE THREAD

**Issue by xiabin** [eryajf/go-ldap-admin#179]
#### 您使用的场景？ | 1. Your usage scenarios?
想把企业微信的组织架构同步到 window server 的 active directory 中
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
此项目可以直接跟active directory 配置 并可以进行企业微信组织架构的同步

**Comment by eryajf** [comment]
您好 @xiabin👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @xiabin. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by jackadam1981** [comment]
AD确实也是需要的，ldap是做了各个应用程序的认证，AD是做windows计算机终端的权限分配，统一组策略。
我现在就是用的AD管理登录windows的账号密码，强制终端使用各种组策略来进行终端管理的，AD也有一个轻型目录认证服务，简单整合了nextcloud企业云盘。
为了更好的使用LDAP做统一认证，为了连接钉钉、企业微信，才找到了这个项目。

https://lework.github.io/2019/07/25/openldap-to-ad/
这里有一个用lsc同步 ad openldap的文章，还没实验，研究一下，将这个也放进docker compose,用现成的也挺好。
或者将lsc整合进go-ldap-admin，应该也挺好。
