### ISSUE TITLE
🥳谁在使用 go-ldap-admin

### ISSUE THREAD

**Issue by eryajf** [eryajf/go-ldap-admin#18]
**使用了 go-ldap-admin 的公司，烦请您在 Issue 留下以下信息，非常感谢您的支持！**

## 格式示例

- 地点：北京
- 组织：xxx公司
- 官网：xxxxx.com
- 场景：用户，分组管理，钉钉自动同步
- 展示Logo图片：（如果未提供Logo，我们将从官网截图展示）

> 您的公司信息将在项目官网进行展示：[http://ldapdoc.eryajf.net](http://ldapdoc.eryajf.net/#%F0%9F%A5%B3-%E8%B0%81%E5%9C%A8%E4%BD%BF%E7%94%A8)

**Comment by wangjiadee** [comment]
地点：深圳
公司： ub-tech

**Comment by JinCheng666** [comment]
地点：郑州
组织：某水利设计院的二级组织
联系：634298263@qq.com

**Comment by AA12GQ** [comment]
地点：长沙
组织：为基信息技术有限公司
官网：www.veigit.com
联系：875151567

**Comment by jyhgit** [comment]
地点：杭州
组织：市值风云公司
官网：https://www.wogoo.com
场景：用户，分组管理，钉钉自动同步

**Comment by gebangfeng** [comment]
地点：北京
组织：王府井免税品数字零售有限公司
官网：wfjec.com
场景：用户，分组管理

**Comment by zpj874878956** [comment]
地点：深圳
组织：高盈国际创新科技（深圳）有限公司
官网：https://www.1quant.com
场景：用户，分组管理

**Comment by Sunshine-JamesHu** [comment]
地点：合肥
组织：安徽容知日新股份有限公司
官网：ronds.com
场景：Devops统一用户登录

**Comment by yunqueyiliao** [comment]
地点：上海
组织：云鹊医疗科技(上海)有限公司
官网：https://www.yunqueyi.com/
场景：公司内网统一用户登录

**Comment by moyuanbo** [comment]
地点：广州
组织：岗顶的某家游戏公司
场景：创建和管理OPENLDAP用户，用于多个SVN项目

**Comment by Pepperpotato** [comment]
地点：北京
组织：即时设计
官网：js.design
场景：同步飞书用户至ldap

**Comment by laipeng8** [comment]
地点：成都
组织：数字先锋科技有限公司
联系：2195143506@qq.com
场景：同步飞书用户到ldap
