### ISSUE TITLE
🚀 是否可以随机生成密码，或者创建可以让用户设置密码的特殊链接 | [Feature]Some feature...

### ISSUE THREAD

**Issue by ckyoung123421** [eryajf/go-ldap-admin#180]
#### 您使用的场景？ | 1. Your usage scenarios?
比如使用飞书导入用户，导入一大批用户按现在的逻辑都是使用的默认密码，那么可能会有人永远都不用ldap账户，导致其他人有机会用默认密码尝试登录他人的账户，造成一些不必要的麻烦。
在某些条件下，如无法发送邮件或其他通知的方式下，生成随机密码或链接有困难，但可以作为选项

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
打开选项，在新建或导入用户时可以生成随机密码，通过邮件发送给用户
或生成设置密码的链接，用户直接点击链接进行密码设置，初始密码就不告知（实现应该工作量大一些）

**Comment by eryajf** [comment]
您好 @ckyoung123421👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ckyoung123421. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
关于这个问题，我会好好考虑，看看能不能用一个比较合理的方式来解决。

**Comment by gwdev-ops** [comment]
支持一下这个issues，非常需要一个设置随机密码的功能
