### ISSUE TITLE
分组管理界面显示不显示分组🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by liujazz** [eryajf/go-ldap-admin#181]
#### 您使用的版本？ | Your usage version?
v0.5.9
#### 您使用的场景？ | Your usage scenarios?
飞书同步分组后一开始能够正确在前端显示分组，后面发现映射字段不符合预期，修改了映射后重新同步分组后在前端不显示列表了
#### 您做了什么操作？ | What did you do?
飞书同步分组后一开始能够正确在前端显示分组，后面发现映射字段不符合预期，修改了映射后重新同步分组后在前端不显示列表了
#### 您遇到了什么问题？ | What are your problems?
![image](https://user-images.githubusercontent.com/31301335/228427474-e8428c7b-bd6c-4617-8009-1aff11bb84cf.png)
![image](https://user-images.githubusercontent.com/31301335/228427496-e130b023-7dec-441b-b1f8-2250a005b210.png)
![image](https://user-images.githubusercontent.com/31301335/228427506-67284917-a084-4a9c-9f2f-a838ad0785ce.png)

#### 您期望的结果是怎样的？ | What is your expected outcome?
正确在前端显示分组列表，同时发现一个问题：打开分组管理界面默认会查询所有的分组然后显示，当分组过多时会查询时间很久，是否考虑做一个分页，默认查询前50个这种。

**Comment by eryajf** [comment]
您好 @liujazz👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @liujazz. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 修改了映射后重新同步分组后在前端不显示列表了

一般关系更改之后，建议是把数据清空，然后重新同步。前端不显示数据，看下MySQL里边group表是否有数据呢？

> 同时发现一个问题：打开分组管理界面默认会查询所有的分组然后显示，当分组过多时会查询时间很久，是否考虑做一个分页，默认查询前50个这种。

现在分组以及用户都是有分页的，默认情况下是十条记录

**Comment by eryajf** [comment]
docker部署也是一样，取消config.yml的配置挂载就可以了。

不太科学，如果MySQL有数据，不可能前端是空白的

**Comment by liujazz** [comment]
我通过快照回退了，目前正常了

**Comment by eryajf** [comment]
我知道了，因为分组这里是个树状的，这个树状的请求确实没有做分页
