### ISSUE TITLE
🐛 重新导入的用户无法登录 | [Bug] Some problem...

### ISSUE THREAD

**Issue by ckyoung123421** [eryajf/go-ldap-admin#183]
#### 您使用的版本？ | Your usage version?
v0.5.9 + v0.5.12
#### 您使用的场景？ | Your usage scenarios?
ubuntu20.04
#### 您做了什么操作？ | What did you do?
删除导入的用户后，再导入用户
#### 您遇到了什么问题？ | What are your problems?
原来已经有从飞书导入的用户，我在网页管理端将除admin之外的用户全部删除，然后再点击从飞书导入
这时再使用浏览器登录导入的其中的用户，会提示用户不存在，我查看log是因为数据库SELECT时使用的是id进行查找，但其实再导入的用户，ID会递增，不会使用原来的ID
![image](https://user-images.githubusercontent.com/16368382/229066762-f6aa93f5-296a-453c-8b9e-2dfe70ef2fea.png)
![image](https://user-images.githubusercontent.com/16368382/229067092-0e5b6aa7-471e-41b0-acf4-5914d2d2b509.png)
即使重启后端前端，也是一样的现象
#### 您期望的结果是怎样的？ | What is your expected outcome?
解决该问题。

**Comment by eryajf** [comment]
您好 @ckyoung123421👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ckyoung123421. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ckyoung123421** [comment]
应该是我修改飞书根目录导致的一些问题，后面保留feishu_0后没问题了
