### ISSUE TITLE
🐛[Bug] 飞书获取指定部门报错

### ISSUE THREAD

**Issue by ixiaoyi93** [eryajf/go-ldap-admin#184]
#### 您使用的版本？ | Your usage version?
docker lastet

#### 您使用的场景？ | Your usage scenarios?
获取飞书指定部门或者是指定部门下面的用户

#### 您做了什么操作？ | What did you do?
参考飞书文档：https://open.feishu.cn/document/ukTMukTMukTM/uETNz4SM1MjLxUzM/v3/guides/scope_authority?lang=zh-CN。

进行飞书机器人应用的权限配置。如下图所示：
![image](https://user-images.githubusercontent.com/34268642/229407541-6aee0d07-4271-434d-971e-fce909d27bbf.png)

#### 您遇到了什么问题？ | What are your problems?
通过飞书进行如上图权限配置之后，提示如下错误：
![image](https://user-images.githubusercontent.com/34268642/229407633-ab742989-f203-4e00-89bc-6ce47b6dedbb.png)

#### 您期望的结果是怎样的？ | What is your expected outcome?
根据飞书的相关文档，目前飞书是可以指定机器人应用的通讯录权限。我希望通过飞书应用的权限可以实现指定部门的用户同步。

**Comment by eryajf** [comment]
您好 @ixiaoyi93👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixiaoyi93. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ixiaoyi93** [comment]
@eryajf 老哥，什么时候更新一版

**Comment by ckyoung123421** [comment]
@ixiaoyi93 @eryajf 已更新可使用飞书列表的版本 #186

**Comment by ixiaoyi93** [comment]
> 

已经体验了，感谢老哥贡献。非常好用！
