### ISSUE TITLE
🐛 一些问题。。。 | 分组页面未分页和多层级部门数据没有

### ISSUE THREAD

**Issue by huxiangquan** [eryajf/go-ldap-admin#188]
#### 您使用的版本？ | Your usage version?
0.5.9
#### 您使用的场景？ | Your usage scenarios?
部门用户同步统一登陆
#### 您做了什么操作？ | What did you do?
同步部门
#### 您遇到了什么问题？ | What are your problems?
分组页面没有分页，几百个部门的时候整个页面反应迟钝。
部门层级只有二级，再下面的部门无法获取。
#### 您期望的结果是怎样的？ | What is your expected outcome?
面页分页。多级部门全部获取。

**Comment by eryajf** [comment]
您好 @huxiangquan👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huxiangquan. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
分页的问题是因为这个数据是一个树状的，所以没做分页。

多级部门数据没有这个应该不会，能否看下接口的返回，看看是数据库里就没有，还是接口没有正常返回呢。

**Comment by huxiangquan** [comment]
> 

已检查，是有数据的，没仔细看。树状图不好分布看能不能设计成逐层级展开呢。默认只显示第一级，点击后再展开第二级依次这样展开。另外选中上级部门时，下级部门能否也一起全选中呢。
