### ISSUE TITLE
关于其他平台修改密码不生效

### ISSUE THREAD

**Issue by jenvenson** [eryajf/go-ldap-admin#191]
其他平台（如confluence，jira等）已接入了ldap，想使用这些平台（如jira）修改用户密码，发现修改后仅能自己平台，无法登录加入ldap的其他平台（包括go-ldap-admin），在go-ldap-admin平台修改密码其他平台均可以登录，请问这个是什么原因及如何解决？

**Comment by eryajf** [comment]
您好 @jenvenson👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @jenvenson. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
再看下readme的图你就明白了，你把方向搞反了。

![](https://camo.githubusercontent.com/65fe95b5ee953a83c2bbd241ca8ef897805ea34f6b98571c04d4f4ceabdd7bed/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f657279616a662f74752f6d61696e2f696d672f696d6167655f32303232303631345f3133313532312e6a7067)
