### ISSUE TITLE
🙋 问题交流。。。 | 同步用户失败

### ISSUE THREAD

**Issue by huxiangquan** [eryajf/go-ldap-admin#192]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
docker镜像版本: 2023-04-10_13-23+钉钉组织+bitnami/openldap
### 预期行为 | Expected behavior
同步用户成功 
### 实际行为 | Actual behavior
同步用户后，只有一个用户被同步过来。
### 原因分析（如果可以） | Cause analysis (if possible)
点击同步后，日志中输出国查询用户不存在的SQL记录。
![image](https://user-images.githubusercontent.com/52623921/232367733-cac4e06d-9f80-42f5-b644-e2149c084d33.png)
最后有输出调用syncDingTalkUsers的日志，但数据没有同步成功。
2023/04/17 11:00:08 /app/service/isql/user_isql.go:127 record not found
[0.578ms] [rows:0] SELECT * FROM `users` WHERE `source_user_id` = 'dingtalk_16807621568869467' AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1
[GIN] 2023/04/17 - 11:00:08 | 200 |          3m6s |  192.168.233.20 | POST     "/api/user/syncDingTalkUsers"

### 问题重现步骤 | Steps to reproduce the problem
点击用户同步。

**Comment by eryajf** [comment]
您好 @huxiangquan👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huxiangquan. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by wang-xiaowu** [comment]
您好作者，同样问题
同步飞书的数据之后报错`record not found`
```go
2023/04/21 11:37:08 /app/service/isql/field_relation_isql.go:40 record not found
[0.687ms] [rows:0] SELECT * FROM `field_relations` WHERE `flag` = 'feishu_user' AND `field_relations`.`deleted_at` IS NULL ORDER BY `field_relations`.`id` LIMIT 1
[GIN] 2023/04/21 - 11:37:08 | 200 |  9.797166939s |   116.3.194.203 | POST     "/api/user/syncFeiShuUsers"
```

**Comment by wang-xiaowu** [comment]
现在使用企微同步数据报错not allow to access from your ip, hintxxx
飞书同步数据 record not found
-.-

**Comment by eryajf** [comment]
其中的sql输出是正常的情况，还是需要看点击同步之后，浏览器控制台那里，看看后端接口返回了什么错误

**Comment by bcaay** [comment]
![image](https://user-images.githubusercontent.com/86762085/233829539-c28771ac-b823-4537-a8c9-df126b65ad7a.png)
同步飞书分组时，显示同步成功了，浏览器返回的也是正常的，但是飞书分组下并没有创建同步的分组，请问这个怎么解决

**Comment by ixiaoyi93** [comment]
@bcaay 看一下 Response 返回的啥呢

**Comment by bcaay** [comment]
> 
![image](https://user-images.githubusercontent.com/86762085/233835012-22b85344-4575-44b4-9431-81ef100f2e98.png)

**Comment by bcaay** [comment]
> @bcaay看一下 Response 返回的啥呢
![image](https://user-images.githubusercontent.com/86762085/233835203-fcda1e68-8c2b-4426-963a-4453170180fd.png)

**Comment by ixiaoyi93** [comment]
@bcaay 看着没啥问题，你看看ldap日志吧，还有就是字段关系管理那块有没有配置正确。

**Comment by bcaay** [comment]
> @bcaay 看着没啥问题，你看看ldap日志吧，还有就是字段关系管理那块有没有配置正确。

![image](https://user-images.githubusercontent.com/86762085/233914953-8c9458ff-2d4c-41d2-a765-2c6e8a79df57.png) 

@ixiaoyi93  字段是按照文档配置的，ldap的日志也看不出哪有问题

![image](https://user-images.githubusercontent.com/86762085/233915395-90e4c332-5689-401a-b01a-0cdd8b6ee415.png)

**Comment by bcaay** [comment]
确实是分组字段的问题，我改了一下同步成功了，但是不会同步子部门
![image](https://user-images.githubusercontent.com/86762085/233921806-4d7aca26-54f3-494f-9815-28c7498be5af.png)

**Comment by ixiaoyi93** [comment]
@bcaay 盲猜可能跟这个配置有关：
![image](https://user-images.githubusercontent.com/34268642/234210691-0246df43-15fe-4179-9bce-455d8e0c0f94.png)

**Comment by huxiangquan** [comment]
> @bcaay 盲猜可能跟这个配置有关： ![image](https://user-images.githubusercontent.com/34268642/234210691-0246df43-15fe-4179-9bce-455d8e0c0f94.png)

后面不知道动了哪里同步成功了，今天在测这个按部门同步了。之前没发现这个配置。
