### ISSUE TITLE
🙋 问题交流。。。 | [Question] 飞书同步组织架构，如何将People分组下的用户数据直接放到feishuroot下？

### ISSUE THREAD

**Issue by ljl764439816** [eryajf/go-ldap-admin#194]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
go-ldap-admin-ui-v0.5.12
go-ldap-admin-v0.5.9

请问如何，在同步用户时直接将用户数据也放到feishuroot下，而不写入People

期望组织架构分组信息与人员信息在同一分组下

直接修改config.yml中user-dn: "ou=feishuroot,dc=eryjf,dc=net" 是否可行？

**Comment by eryajf** [comment]
您好 @ljl764439816👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ljl764439816. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
不行，看这篇文章： http://ldapdoc.eryajf.net/pages/5683c6/
