### ISSUE TITLE
企业微信同步报错，手机号/邮箱/职位都无法同步到字段

### ISSUE THREAD

**Issue by riverwoo** [eryajf/go-ldap-admin#195]
企业微信同步报错，手机号/邮箱/职位都无法同步到字段，手机号一直是18888888888，有办法解决吗
![4F4205AF-FB66-4B1F-94B5-2794A8CA51C5](https://user-images.githubusercontent.com/19513606/233119312-2763b83f-2d4e-4314-8db0-5bebc5cbd5f5.jpeg)

**Comment by eryajf** [comment]
您好 @riverwoo👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @riverwoo. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
现在如果手机号为空，则会填充随机数
