### ISSUE TITLE
🙋 问题交流 没有接口管理相关文档

### ISSUE THREAD

**Issue by Coldfengzi** [eryajf/go-ldap-admin#196]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
最新版
### 预期行为 | Expected behavior
使用接口实现添加用户、发送更改密码的邮件等功能
### 实际行为 | Actual behavior
不知道如何调用接口管理中的相关接口
### 问题重现步骤 | Steps to reproduce the problem
必现

**Comment by eryajf** [comment]
您好 @Coldfengzi👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Coldfengzi. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
请求后端接口时，需带上指定的cookie和header。

详见这里： https://github.com/gnimli/go-web-mini/issues/4#issuecomment-1085561502
