### ISSUE TITLE
🐛 您好，关于企微同步这块，目前同步数据会报错48009或者出现白名单ip问题，请问咱们有啥解决方案么？

### ISSUE THREAD

**Issue by wang-xiaowu** [eryajf/go-ldap-admin#197]
#### 您使用的版本？ | Your usage version?
docker，latest
#### 您做了什么操作？ | What did you do?
同步企微部门数据/成员数据
#### 您遇到了什么问题？ | What are your problems?
关于企微同步这块，目前同步数据会报错48009或者出现白名单ip问题

**Comment by eryajf** [comment]
您好 @wang-xiaowu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wang-xiaowu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by wang-xiaowu** [comment]
还有就是提个小优化点哈
我最终使用飞书进行同步了，然后同步用户信息后需要再点下查询才能展示用户，这里我开始还以为没同步过来。。

**Comment by eryajf** [comment]
> 关于企微同步这块，目前同步数据会报错48009或者出现白名单ip问题

之前一直没有精力来弄这块儿，随后如果有空，我会看看这个问题

**Comment by wang-xiaowu** [comment]
> > 关于企微同步这块，目前同步数据会报错48009或者出现白名单ip问题
> 
> 之前一直没有精力来弄这块儿，随后如果有空，我会看看这个问题

好的，辛苦

**Comment by WinJayX** [comment]
> 关于企微同步这块，目前同步数据会报错48009或者出现白名单ip问题

之前一直没有精力来弄这块儿，随后如果有空，我会看看这个问题

_Originally posted by @eryajf in https://github.com/eryajf/go-ldap-admin/issues/197#issuecomment-1518453142_
            

=================================

请问这个问题解决了么？ 对于新用户而言，企微同步的功能还能使用吗？ 谢谢。

**Comment by eryajf** [comment]
我刚刚又试了一下，发现仍旧能够直接获取用户信息。不知道是不是我创建的测试企业微信的原因。

如果你需要配置白名单，可以使用`设置接收消息服务器URL`的方式，然后参照我这篇文章进行校验：https://wiki.eryajf.net/pages/95d127/
