### ISSUE TITLE
🐛 删除数据报错：LDAP Result Code 34 "Invalid DN Syntax": invalid DN

### ISSUE THREAD

**Issue by wang-xiaowu** [eryajf/go-ldap-admin#198]
#### 您使用的版本？ | Your usage version?
docker-latest
#### 您做了什么操作？ | What did you do?
我希望使用飞书别名作为各平台登录名称，所以飞书同步完用户信息后，可能有用户别名设置为空，所以数据同步时发生问题。而后在将该用户删除时报错：LDAP Result Code 34 "Invalid DN Syntax": invalid DN

这是我的动态字段设置
![image](https://user-images.githubusercontent.com/44340137/233774111-21fc26bc-944a-495c-ac2f-e7d4e278e8a3.png)

#### 您遇到了什么问题？ | What are your problems?
删除用户信息报错：删除数据报错：LDAP Result Code 34 "Invalid DN Syntax": invalid DN

**Comment by eryajf** [comment]
您好 @wang-xiaowu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wang-xiaowu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
