### ISSUE TITLE
🐛 关于角色赋权的相关问题

### ISSUE THREAD

**Issue by wang-xiaowu** [eryajf/go-ldap-admin#201]
#### 您使用的版本？ | Your usage version?
docker-latest
#### 您使用的场景？ | Your usage scenarios?
现象：在为普通用户授予权限之后，依然无法进行登录，报错用户不存在。
原因：传过来的是角色id

问题代码截图见：

![image](https://user-images.githubusercontent.com/44340137/234162903-21ae71da-806a-4e7f-9b06-58816e3de119.png)

![image](https://user-images.githubusercontent.com/44340137/234162842-61327960-0769-48c1-bc1d-94bc20e12e3c.png)

**Comment by eryajf** [comment]
您好 @wang-xiaowu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wang-xiaowu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by wang-xiaowu** [comment]
和之前的pr一起，统一放#45里了

**Comment by eryajf** [comment]
OK，等我晚上回去看下
