### ISSUE TITLE
🚀 邮箱后缀支持自定义

### ISSUE THREAD

**Issue by wang-xiaowu** [eryajf/go-ldap-admin#207]
#### 您使用的场景？ | 1. Your usage scenarios?
我最近在迁移公司各系统用户数据到ldap，迁移yapi的过程中发现yapi以邮箱为唯一标准，也就是说如果使用ldap方式登录后，如果ldap邮箱和原用户邮箱保持一致，就会继承下原账户信息，也就不需要重新分配权限了

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
希望email后缀可以在config.yml中定义，而不是写死成@eryajf.net

**Comment by eryajf** [comment]
您好 @wang-xiaowu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wang-xiaowu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by wang-xiaowu** [comment]
如果ok我晚上提个pr，作者方便的话可以看下

**Comment by eryajf** [comment]
可以，没问题，不过这里也要看下，单纯username+自定义邮箱后缀是否能满足需求。
一般情况下，尽可能不新增配置，当然必要的时候，是可以增加到。

**Comment by wang-xiaowu** [comment]
嗯嗯

**Comment by huxiangquan** [comment]
这个已经合并了吗？我这边也是这个需求，邮件后缀要自定义。有个内部的邮件服务器。

**Comment by wang-xiaowu** [comment]
嗯 我今天提
这个默认邮箱后缀的属性放在`ldap:`下合适吗？@eryajf

**Comment by wang-xiaowu** [comment]
还有个小建议哈，个人中心的Education和Skills咋看咋感觉过于“随便”了，因为毕竟用这个产品的肯定都是公司/项目组织用途的
要不要删掉或者改的正式点比较好
![image](https://github.com/eryajf/go-ldap-admin/assets/44340137/973a38df-5422-49a7-bdb1-8cd3bfd9b3aa)

**Comment by eryajf** [comment]
> 这个默认邮箱后缀的属性放在`ldap:`下合适吗？

放这里可以的

**Comment by eryajf** [comment]
> 还有个小建议哈，个人中心的Education和Skills咋看咋感觉过于“随便”了，因为毕竟用这个产品的肯定都是公司/项目组织用途的 要不要删掉或者改的正式点比较好 ![image](https://user-images.githubusercontent.com/44340137/281589091-973a38df-5422-49a7-bdb1-8cd3bfd9b3aa.png)

哈哈，这个是用的模板，所以就没有改。不过可以去掉。
