### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by likunsi** [eryajf/go-ldap-admin#212]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?

官网docker compose 直接部署

### 预期行为 | Expected behavior

希望同步企业微信

### 实际行为 | Actual behavior

点击”同步企业微信部门“显示成功但是并没有同步到页面
点击”同步企业微信用户信息“显示成功但是并没有同步到页面
![image](https://github.com/eryajf/go-ldap-admin/assets/117960512/372e837b-acd1-4548-a28c-764b01f8fab8)

### 原因分析（如果可以） | Cause analysis (if possible)

ldap里也没有发现组和用户
![image](https://github.com/eryajf/go-ldap-admin/assets/117960512/a7c36324-737c-47af-9898-dc77ad919f26)
![image](https://github.com/eryajf/go-ldap-admin/assets/117960512/c7971d1e-87c0-474f-8f26-279f9224e449)

### 问题重现步骤 | Steps to reproduce the problem

点击”同步企业微信部门“
点击”同步企业微信用户信息“

**Comment by eryajf** [comment]
您好 @likunsi👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @likunsi. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
