### ISSUE TITLE
转换企业微信部门数据失败：record not found

### ISSUE THREAD

**Issue by Wangyxiang** [eryajf/go-ldap-admin#215]
#### 您期望的结果是怎样的？ |   企微部门信息正常同步

![image](https://github.com/eryajf/go-ldap-admin/assets/51821806/ad402dbe-34e8-4d44-b48f-46a210099460)

![image](https://github.com/eryajf/go-ldap-admin/assets/51821806/70640849-f448-47f6-b132-69e17a3bca0a)

**Comment by eryajf** [comment]
您好 @Wangyxiang👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Wangyxiang. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by liujazz** [comment]
先建立字段映射

**Comment by Wangyxiang** [comment]
我建立了字段关系，然后点击同步，页面显示通过成功，但似乎并没有数据。是哪里配置有问题嘛
![image](https://github.com/eryajf/go-ldap-admin/assets/51821806/0e72a534-0228-4ee1-a2fe-11d67a367780)
![image](https://github.com/eryajf/go-ldap-admin/assets/51821806/81604f41-d025-41e9-b668-f1787f9dbee7)
