### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by chickx** [eryajf/go-ldap-admin#216]
#### 您使用的版本？ | Your usage version?
latest，centos7
#### 您使用的场景？ | Your usage scenarios?
同步钉钉部门
#### 您做了什么操作？ | What did you do?
点击同步钉钉部门
#### 您遇到了什么问题？ | What are your problems?
网页UI界面部门全没了，但是通过LDAP admin看到是同步成功的
#### 您期望的结果是怎样的？ | What is your expected outcome?
web界面正常显示

**Comment by eryajf** [comment]
您好 @chickx👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @chickx. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
