### ISSUE TITLE
同步原LDAP用户信息后，所属部门出现“请选择部门信息”部门，并无法删除。

### ISSUE THREAD

**Issue by huangzhongzhang** [eryajf/go-ldap-admin#217]
#### 您使用的版本？ | Your usage version?

容器化部署，lateset

#### 您使用的场景？ | Your usage scenarios?

测试。

#### 您做了什么操作？ | What did you do?

安装，并导入原有LDAP信息。

#### 您遇到了什么问题？ | What are your problems?

同步原LDAP用户信息后，所属部门出现“请选择部门信息”部门，并无法删除。

![微信截图_20230523105227](https://github.com/eryajf/go-ldap-admin/assets/13826425/9da53aac-cb2b-4abb-94c2-c6a597338572)

![微信截图_20230523105301](https://github.com/eryajf/go-ldap-admin/assets/13826425/f3f351fd-d7f0-42f2-b59e-0ced6936677e)

#### 您期望的结果是怎样的？ | What is your expected outcome?

默认不出现此项，并可删除。

**Comment by eryajf** [comment]
您好 @huangzhongzhang👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huangzhongzhang. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
