### ISSUE TITLE
🙋 使用docker-compose 快速拉起失败

### ISSUE THREAD

**Issue by yibeizj** [eryajf/go-ldap-admin#218]
## Question Report
使用docker-compose 快速拉起失败
日志如下：
![image](https://github.com/eryajf/go-ldap-admin/assets/27260207/3addd477-f818-4616-a43c-76eacc3a252c)

**Comment by eryajf** [comment]
您好 @huazhanghui007👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huazhanghui007. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个报错倒是第一次遇到，你是在什么样的主机上拉起的呢

**Comment by huazhanghui007** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/27260207/37ba1a81-237b-42d2-8cb5-a350864fca1b)

**Comment by eryajf** [comment]
可以重试一下，看看是否还有相同报错，建议把数据，以及镜像都删除，然后重新来一次

**Comment by huazhanghui007** [comment]
[root@ecs-a61c docker-compose]# docker images    
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# docker-compose ps
Name   Command   State   Ports
------------------------------
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# docker-compose up -d
Pulling mysql (dockerproxy.com/mysql/mysql-server:5.7)...
5.7: Pulling from mysql/mysql-server
d70f3c0cccba: Pull complete
e7dc89aa39f7: Pull complete
76cc4215b650: Pull complete
25b0bb53e492: Pull complete
349b52643cc3: Pull complete
62ddcf4a4134: Pull complete
c91c597e717d: Pull complete
c7e93886e496: Pull complete
Digest: sha256:1178cdd375f758968cd834ac4057bae41307e64b7c69a9e145896e7b11f48064
Status: Downloaded newer image for dockerproxy.com/mysql/mysql-server:5.7
Pulling openldap (dockerproxy.com/osixia/openldap:1.4.0)...
1.4.0: Pulling from osixia/openldap
33cc09c9b190: Pull complete
738f3cb59013: Pull complete
91445f9ed621: Pull complete
47e6dbabcdaf: Pull complete
3ff95d106a17: Pull complete
bb76a46060b0: Pull complete
cbfb6c93b787: Pull complete
84111ae63e7b: Pull complete
1aeb02b7595f: Pull complete
9ef242d12597: Pull complete
Digest: sha256:ccd95cc6e61effc1bbc4fff8b09d358ee9d6739a43f4124d6219ac18d82879d1
Status: Downloaded newer image for dockerproxy.com/osixia/openldap:1.4.0
Pulling phpldapadmin (dockerproxy.com/osixia/phpldapadmin:0.9.0)...
0.9.0: Pulling from osixia/phpldapadmin
695ddc5be713: Pull complete
8c216a02c36e: Pull complete
1a1027aafb7a: Pull complete
8f7a381d4cde: Pull complete
08ea8b51d1b2: Pull complete
fb991431dcc1: Pull complete
06ad340c0b75: Pull complete
05f69b6a9301: Pull complete
900bcb3ddce1: Pull complete
cc96a7c21f5a: Pull complete
Digest: sha256:d112b82be1336f91e028b0348755133fda333992355b533419355a65c32ff9ad
Status: Downloaded newer image for dockerproxy.com/osixia/phpldapadmin:0.9.0
Pulling go-ldap-admin-server (dockerproxy.com/eryajf/go-ldap-admin-server:latest)...
latest: Pulling from eryajf/go-ldap-admin-server
547446be3368: Pull complete
e11536b7c5b0: Pull complete
4f4fb700ef54: Pull complete
cb7026371907: Pull complete
edc9dc45456f: Pull complete
Digest: sha256:e74d641f2b111938852bf25681f75ea1c98643edbc9f628577037da4a8e4cf1e
Status: Downloaded newer image for dockerproxy.com/eryajf/go-ldap-admin-server:latest
Pulling go-ldap-admin-ui (dockerproxy.com/eryajf/go-ldap-admin-ui:latest)...
latest: Pulling from eryajf/go-ldap-admin-ui
6717b8ec66cd: Pull complete
a8fbffeda4dc: Pull complete
b47f6806a609: Pull complete
dd7db1f1d8e9: Pull complete
51e4edb263ef: Pull complete
4f4fb700ef54: Pull complete
aa38e126dadc: Pull complete
Creating go-ldap-admin-openldap ... done
Creating go-ldap-admin-mysql ... done
Creating go-ldap-admin-server ... done
Creating go-ldap-admin-ui ... done
Creating go-ldap-admin-openldap ... 
Creating go-ldap-admin-phpldapadmin ... 
Creating go-ldap-admin-server ... 
Creating go-ldap-admin-ui ... 
[root@ecs-a61c docker-compose]# docker-compose ps
           Name                         Command                 State                          Ports                    
------------------------------------------------------------------------------------------------------------------------
go-ldap-admin-mysql          /entrypoint.sh --default-a ...   Restarting                                                
go-ldap-admin-openldap       /container/tool/run --copy ...   Up           0.0.0.0:388->389/tcp,:::388->389/tcp, 636/tcp
go-ldap-admin-phpldapadmin   /container/tool/run              Up           443/tcp, 0.0.0.0:8091->80/tcp,:::8091->80/tcp
go-ldap-admin-server         /bin/sh -c ./wait && ./go- ...   Restarting                                                
go-ldap-admin-ui             /bin/sh -c nginx -g "daemo ...   Up           0.0.0.0:8090->80/tcp,:::8090->80/tcp         
[root@ecs-a61c docker-compose]# docker-compose ps | date
Wed May 24 11:26:13 CST 2023
[root@ecs-a61c docker-compose]# docker-compose ps
           Name                         Command                 State                          Ports                    
------------------------------------------------------------------------------------------------------------------------
go-ldap-admin-mysql          /entrypoint.sh --default-a ...   Restarting                                                
go-ldap-admin-openldap       /container/tool/run --copy ...   Up           0.0.0.0:388->389/tcp,:::388->389/tcp, 636/tcp
go-ldap-admin-phpldapadmin   /container/tool/run              Up           443/tcp, 0.0.0.0:8091->80/tcp,:::8091->80/tcp
go-ldap-admin-server         /bin/sh -c ./wait && ./go- ...   Restarting                                                
go-ldap-admin-ui             /bin/sh -c nginx -g "daemo ...   Up           0.0.0.0:8090->80/tcp,:::8090->80/tcp         
[root@ecs-a61c docker-compose]# docker logs --tail 200 -f go-ldap-admin-mysql | tain -n 5
-bash: tain: command not found
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error

------------  重新来，还是报错

**Comment by huazhanghui007** [comment]
`[root@ecs-a61c docker-compose]# docker images    
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# docker-compose ps
Name   Command   State   Ports
------------------------------
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# 
[root@ecs-a61c docker-compose]# docker-compose up -d
Pulling mysql (dockerproxy.com/mysql/mysql-server:5.7)...
5.7: Pulling from mysql/mysql-server
d70f3c0cccba: Pull complete
e7dc89aa39f7: Pull complete
76cc4215b650: Pull complete
25b0bb53e492: Pull complete
349b52643cc3: Pull complete
62ddcf4a4134: Pull complete
c91c597e717d: Pull complete
c7e93886e496: Pull complete
Digest: sha256:1178cdd375f758968cd834ac4057bae41307e64b7c69a9e145896e7b11f48064
Status: Downloaded newer image for dockerproxy.com/mysql/mysql-server:5.7
Pulling openldap (dockerproxy.com/osixia/openldap:1.4.0)...
1.4.0: Pulling from osixia/openldap
33cc09c9b190: Pull complete
738f3cb59013: Pull complete
91445f9ed621: Pull complete
47e6dbabcdaf: Pull complete
3ff95d106a17: Pull complete
bb76a46060b0: Pull complete
cbfb6c93b787: Pull complete
84111ae63e7b: Pull complete
1aeb02b7595f: Pull complete
9ef242d12597: Pull complete
Digest: sha256:ccd95cc6e61effc1bbc4fff8b09d358ee9d6739a43f4124d6219ac18d82879d1
Status: Downloaded newer image for dockerproxy.com/osixia/openldap:1.4.0
Pulling phpldapadmin (dockerproxy.com/osixia/phpldapadmin:0.9.0)...
0.9.0: Pulling from osixia/phpldapadmin
695ddc5be713: Pull complete
8c216a02c36e: Pull complete
1a1027aafb7a: Pull complete
8f7a381d4cde: Pull complete
08ea8b51d1b2: Pull complete
fb991431dcc1: Pull complete
06ad340c0b75: Pull complete
05f69b6a9301: Pull complete
900bcb3ddce1: Pull complete
cc96a7c21f5a: Pull complete
Digest: sha256:d112b82be1336f91e028b0348755133fda333992355b533419355a65c32ff9ad
Status: Downloaded newer image for dockerproxy.com/osixia/phpldapadmin:0.9.0
Pulling go-ldap-admin-server (dockerproxy.com/eryajf/go-ldap-admin-server:latest)...
latest: Pulling from eryajf/go-ldap-admin-server
547446be3368: Pull complete
e11536b7c5b0: Pull complete
4f4fb700ef54: Pull complete
cb7026371907: Pull complete
edc9dc45456f: Pull complete
Digest: sha256:e74d641f2b111938852bf25681f75ea1c98643edbc9f628577037da4a8e4cf1e
Status: Downloaded newer image for dockerproxy.com/eryajf/go-ldap-admin-server:latest
Pulling go-ldap-admin-ui (dockerproxy.com/eryajf/go-ldap-admin-ui:latest)...
latest: Pulling from eryajf/go-ldap-admin-ui
6717b8ec66cd: Pull complete
a8fbffeda4dc: Pull complete
b47f6806a609: Pull complete
dd7db1f1d8e9: Pull complete
51e4edb263ef: Pull complete
4f4fb700ef54: Pull complete
aa38e126dadc: Pull complete
Creating go-ldap-admin-openldap ... done
Creating go-ldap-admin-mysql ... done
Creating go-ldap-admin-server ... done
Creating go-ldap-admin-ui ... done
Creating go-ldap-admin-openldap ... 
Creating go-ldap-admin-phpldapadmin ... 
Creating go-ldap-admin-server ... 
Creating go-ldap-admin-ui ... 
[root@ecs-a61c docker-compose]# docker-compose ps
           Name                         Command                 State                          Ports                    
------------------------------------------------------------------------------------------------------------------------
go-ldap-admin-mysql          /entrypoint.sh --default-a ...   Restarting                                                
go-ldap-admin-openldap       /container/tool/run --copy ...   Up           0.0.0.0:388->389/tcp,:::388->389/tcp, 636/tcp
go-ldap-admin-phpldapadmin   /container/tool/run              Up           443/tcp, 0.0.0.0:8091->80/tcp,:::8091->80/tcp
go-ldap-admin-server         /bin/sh -c ./wait && ./go- ...   Restarting                                                
go-ldap-admin-ui             /bin/sh -c nginx -g "daemo ...   Up           0.0.0.0:8090->80/tcp,:::8090->80/tcp         
[root@ecs-a61c docker-compose]# docker-compose ps | date
Wed May 24 11:26:13 CST 2023
[root@ecs-a61c docker-compose]# docker-compose ps
           Name                         Command                 State                          Ports                    
------------------------------------------------------------------------------------------------------------------------
go-ldap-admin-mysql          /entrypoint.sh --default-a ...   Restarting                                                
go-ldap-admin-openldap       /container/tool/run --copy ...   Up           0.0.0.0:388->389/tcp,:::388->389/tcp, 636/tcp
go-ldap-admin-phpldapadmin   /container/tool/run              Up           443/tcp, 0.0.0.0:8091->80/tcp,:::8091->80/tcp
go-ldap-admin-server         /bin/sh -c ./wait && ./go- ...   Restarting                                                
go-ldap-admin-ui             /bin/sh -c nginx -g "daemo ...   Up           0.0.0.0:8090->80/tcp,:::8090->80/tcp         
[root@ecs-a61c docker-compose]# docker logs --tail 200 -f go-ldap-admin-mysql | tain -n 5
-bash: tain: command not found
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error
exec /entrypoint.sh: exec format error`

-----------------重新来还是一样的报错

**Comment by eryajf** [comment]
主要是MySQL没有起来，你的系统CPU架构应该是那个镜像不兼容，你可以看看先让MySQL起来

**Comment by Galaxy3696** [comment]
### 我使用windows上的Docker Desktop也无法拉起，也是MySQL相关问题
2023-07-26 14:56:32 2023-07-26T06:56:32.188163Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:56:32 2023-07-26T06:56:32.189079Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:56:32 2023-07-26T06:56:32.189109Z 0 [ERROR] Aborting
2023-07-26 14:56:32 
2023-07-26 14:56:34 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:56:34 2023-07-26T06:56:34.606994Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:56:34 2023-07-26T06:56:34.607921Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:56:34 2023-07-26T06:56:34.607955Z 0 [ERROR] Aborting
2023-07-26 14:56:34 
2023-07-26 14:56:38 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:56:38 2023-07-26T06:56:38.626057Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:56:38 2023-07-26T06:56:38.626985Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:56:38 2023-07-26T06:56:38.627015Z 0 [ERROR] Aborting
2023-07-26 14:56:38 
2023-07-26 14:56:45 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:56:45 2023-07-26T06:56:45.887926Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:56:45 2023-07-26T06:56:45.889000Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:56:45 2023-07-26T06:56:45.889041Z 0 [ERROR] Aborting
2023-07-26 14:56:45 
2023-07-26 14:57:00 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:57:00 2023-07-26T06:57:00.067792Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:57:00 2023-07-26T06:57:00.068736Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:57:00 2023-07-26T06:57:00.068766Z 0 [ERROR] Aborting
2023-07-26 14:57:00 
2023-07-26 14:57:26 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:57:26 2023-07-26T06:57:26.548198Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:57:26 2023-07-26T06:57:26.549225Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:57:26 2023-07-26T06:57:26.549260Z 0 [ERROR] Aborting
2023-07-26 14:57:26 
2023-07-26 14:58:18 mysqld: [Warning] World-writable config file '/etc/mysql/my.cnf' is ignored.
2023-07-26 14:58:18 2023-07-26T06:58:18.797411Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-26 14:58:18 2023-07-26T06:58:18.798379Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-26 14:58:18 2023-07-26T06:58:18.798410Z 0 [ERROR] Aborting

**Comment by eryajf** [comment]
如果compose里的MySQL起不来，请自行部署MySQL，然后通过更改配置连接自建MySQL。

我手边没有Windows环境，无法复现此问题。

**Comment by ianchan85** [comment]
@eryajf 我今天在Win10下，测试用Docker-Compose快速拉起，提示World-writable config file '/etc/mysql/my.cnf' is ignored，这个错误是注释了docker-compose.yaml下面这两句就能正常拉起服务，Decker-Desktop显示都running了
`#- ./data/mysql:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
      #- ./config/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件`
但是后台登陆admin提示错误，日志显示
`server    | [4.464ms] [rows:0] SELECT * FROM `users` WHERE `username` = 'admin' AND `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT 1

go-ldap-admin-server    | 2023-11-20 15:21:28 DEBUG middleware/AuthMiddleware.go:113 github.com/eryajf/go-ldap-admin/middleware.unauthorized JWT��֤ʧ��, ������: 401, ������Ϣ: �û�������`

用phpmyadmin进mysql后台看到，[go_ldap_admin]的表'users'是空的，这种要怎么解决，我试过删掉重新拉起，是一样的错误。

**Comment by eryajf** [comment]
由于我这边没有win的环境，所以没办法做完整的测试验证。
如果是这种情况，那还是建议你把mysql外置，然后调整一下连接mysql的配置文件，再次重新部署即可。
