### ISSUE TITLE
🙋 使用docker-compose 一直停在《 ⠿ Container go-ldap-admin-server        Starting       473.7s 》

### ISSUE THREAD

**Issue by woojunrt** [eryajf/go-ldap-admin#219]
日志如下
一直停在 ⠿ Container go-ldap-admin-server        Starting                                       518.1s 
请求大神帮助。
image换成docker.mirrors.sjtug.sjtu.edu.cn/eryajf/go-ldap-admin-server试了也一样。

# docker-compose up -d
[+] Running 5/5
 ✔ go-ldap-admin-ui Pulled                                                                      
 ✔ mysql Pulled                                                                                 
 ✔ openldap Pulled                                                                              
 ✔ phpldapadmin Pulled                                                                          
 ✔ go-ldap-admin-server Pulled                                                                  
[+] Building 0.0s (0/0)                                                                         
[+] Running 5/6
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s  
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
[+] Running 5/6er-compose_go-ldap-admin  Create...                                        0.1s 
 ✔ Network docker-compose_go-ldap-admin  Create...                                        0.1s 
 ✔ Container go-ldap-admin-openldap      Started                                          0.6s 
 ✔ Container go-ldap-admin-mysql         Started                                          0.7s 
 ✔ Container go-ldap-admin-phpldapadmin  Starte...                                        1.6s 
 ⠿ Container go-ldap-admin-server        Starting                                       498.0s 
 ✔ Container go-ldap-admin-ui            Created                                          0.0s

**Comment by eryajf** [comment]
您好 @woojunrt👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @woojunrt. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这两个镜像是同一个。
另外卡在这一步的原因大概是啥呢，docker看看容器状态，以及容器日志
