### ISSUE TITLE
新建的用户无法在访问ldap时获取到

### ISSUE THREAD

**Issue by zningsc** [eryajf/go-ldap-admin#220]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 预期行为 | Expected behavior
通过访问ldap服务器获取到里面的用户
### 实际行为 | Actual behavior
能够连接，但是无法将用户显示出来
### 原因分析（如果可以） | Cause analysis (if possible)
新建的用户没有objectClass: posixAccount、homeDirectory、uidnumber和gidnumber，所以其他通过LDAP服务器访问时无法获取到这些用户列表，通过LDAP-Admin进去编辑该用户，将缺少的信息补入后就可以获取到
### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @zningsc👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @zningsc. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这的确是该项目的一些局限，在设计初期就固定下了用户和分组的两个class，而不是像phpldapadmin那样的兼容所有的。

因此使用这个管理后台，通常会重建数据，如果原来的数据与当前架构设计不兼容，则需要考虑把原来的数据做一下迁移。
