### ISSUE TITLE
新增用户的时候，部门无法选择 

### ISSUE THREAD

**Issue by JustShowTime** [eryajf/go-ldap-admin#221]

**Comment by eryajf** [comment]
您好 @JustShowTime👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @JustShowTime. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by JustShowTime** [comment]
![1686550244289](https://github.com/eryajf/go-ldap-admin/assets/49704186/682a4c14-25ec-4eee-8a49-3f5aefb383d1)

**Comment by eryajf** [comment]
部门只能使用 cn 类型的。

阅读这篇文档，你就可以明白了：http://ldapdoc.eryajf.net/pages/5683c6/

**Comment by backlash-go** [comment]
同问 这个需要怎么操作才能选择部门

**Comment by backlash-go** [comment]
> ![1686550244289](https://private-user-images.githubusercontent.com/49704186/245047570-682a4c14-25ec-4eee-8a49-3f5aefb383d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzA0OTAsIm5iZiI6MTcwMzc3MDE5MCwicGF0aCI6Ii80OTcwNDE4Ni8yNDUwNDc1NzAtNjgyYTRjMTQtMjVlYy00ZWVlLThhNDktM2Y1YWVmYjM4M2QxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZjFiZGNiMTkwMTU5MDA1YjRmYTY2NDhmYWVjOGE3MmNiMmQwOTQxZTUzYjY2ZjNkOWE1MmRkNTRlZjQ5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mf-ih7tzoUqZuBcWK-M8HfPRtoXD_I-Oyy8zvA4nKzM) 补充说明，我用的docker compose启动的程序


同问 这个需要怎么操作才能选择部门

试了几下，还是不太懂

**Comment by eryajf** [comment]
> > ![1686550244289](https://private-user-images.githubusercontent.com/49704186/245047570-682a4c14-25ec-4eee-8a49-3f5aefb383d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NzA0OTAsIm5iZiI6MTcwMzc3MDE5MCwicGF0aCI6Ii80OTcwNDE4Ni8yNDUwNDc1NzAtNjgyYTRjMTQtMjVlYy00ZWVlLThhNDktM2Y1YWVmYjM4M2QxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEzMjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZjFiZGNiMTkwMTU5MDA1YjRmYTY2NDhmYWVjOGE3MmNiMmQwOTQxZTUzYjY2ZjNkOWE1MmRkNTRlZjQ5NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mf-ih7tzoUqZuBcWK-M8HfPRtoXD_I-Oyy8zvA4nKzM) 补充说明，我用的docker compose启动的程序
> 
> 同问 这个需要怎么操作才能选择部门
> 
> 试了几下，还是不太懂

创建一个分组，类型选择为cn，再回来就能选择了
