### ISSUE TITLE
docker镜像被删了吗？安装的时候提示找不到

### ISSUE THREAD

**Issue by ixueyong** [eryajf/go-ldap-admin#222]
镜像被删了吗？
<img width="675" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/79446043/42c55c97-1c2f-42e0-a83b-0bc45c3f6f63">

**Comment by eryajf** [comment]
您好 @ixueyong👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ixueyong. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ixueyong** [comment]
前缀有的哦， 截图里能看到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eryajf/go-ldap-admin] docker镜像被删了吗？安装的时候提示找不到 (Issue #222)





 
没有删，你也可以在前边增加前缀拉取试试 dockerproxy.com

**Comment by eryajf** [comment]
> 前缀有的哦， 截图里能看到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月13日(星期二) 下午5:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [eryajf/go-ldap-admin] docker镜像被删了吗？安装的时候提示找不到 (Issue #222) 没有删，你也可以在前边增加前缀拉取试试 dockerproxy.com — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

可能是在这个加速节点缓存丢了，如果你的网络OK，可以尝试把加速前缀去掉再试试
