### ISSUE TITLE
🚀 希望可以增加对密码设置的要求限制，例如加上长度8位以上，包含大小写字母加数字

### ISSUE THREAD

**Issue by blankleee** [eryajf/go-ldap-admin#223]
您使用的场景？ | 1. Your usage scenarios?
1.现在大家对密码的安全度不重视，只能在平台测做限制，如果不做限制的话，用户容易设置弱密码，导致安全风险。

您期望的结果是怎样的？ | 2. What is your expected outcome?
1.希望可以增加对密码设置的要求限制，加上长度8位以上，包含大小写字母加数字
2.首次登陆控制台要求用户修改密码或者发送链接让用户修改密码

**Comment by eryajf** [comment]
您好 @blankleee👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @blankleee. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
