### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...windows环境下执行dockercompose mysql 启动失败

### ISSUE THREAD

**Issue by DUANTUTU** [eryajf/go-ldap-admin#226]
![image](https://github.com/eryajf/go-ldap-admin/assets/50581551/183d131a-7d89-44c7-bb8c-6ccda34c5f72)
当我在windows环境下执行dockercompose 镜像可以正常拉取成功，其他容器正常启动，但是go-ldap-admin-mysq 启动失败，
删除compose文件里mysql的挂载路径可以成功，但是没有相对应的数据

**Comment by eryajf** [comment]
您好 @DUANTUTU👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @DUANTUTU. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这类部署上的问题，抱歉不能提供太多的帮助，可选择单独部署MySQL，然后配置连接外部MySQL
