### ISSUE TITLE
默认的账密admin/123456有如下图的报错

### ISSUE THREAD

**Issue by MysTer1ous** [eryajf/go-ldap-admin#227]
#### 您使用的版本？ | Your usage version?

最新的
#### 您使用的场景？ | Your usage scenarios?
阿里云
#### 您做了什么操作？ | What did you do?
在docker-compose.yaml改了     
 LDAP_ORGANISATION: "abc.com"
 LDAP_DOMAIN: "abc.com"

#### 您遇到了什么问题？ | What are your problems?
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/8b1c66fd-585c-405b-a594-7edfa4a3d019)

**Comment by eryajf** [comment]
您好 @MysTer1ous👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @MysTer1ous. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
再没有了解项目全貌的情况下，建议使用默认配置，不要更改配置

像你这个，只改这一个地方，并不行的。

详见： http://ldapdoc.eryajf.net/pages/adb742/

**Comment by MysTer1ous** [comment]
> 在没有了解项目全貌的情况下，建议使用默认配置，不要更改配置
> 
> 像你这个，只改这一个地方，并不行的。
> 
> 详见： http://ldapdoc.eryajf.net/pages/adb742/

好的，谢谢大佬，我先用docker试试，后面在用centos7安装
