### ISSUE TITLE
🚀 一些功能。。。 | [Feature]请问能否支持自定义dc/域名

### ISSUE THREAD

**Issue by MysTer1ous** [eryajf/go-ldap-admin#228]
#### 您使用的场景？ | 1. Your usage scenarios?
局域网

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
能否支持自定义dc/域名

**Comment by eryajf** [comment]
您好 @MysTer1ous👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @MysTer1ous. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by MysTer1ous** [comment]
http://ldapdoc.eryajf.net/pages/adb742/#%E5%89%8D%E8%A8%80
已找到文档，谢谢
