### ISSUE TITLE
🐛 报错内容：panic: 绑定admin账号异常: LDAP Result Code 49 "Invalid Credentials": 

### ISSUE THREAD

**Issue by MysTer1ous** [eryajf/go-ldap-admin#229]
#### 您使用的版本？ | Your usage version?
docker-compose lasted
#### 您使用的场景？ | Your usage scenarios?
阿里云
#### 您做了什么操作？ | What did you do?
按照文档自定义basedn，在config/config.yml加入了钉钉应用的appkey和appsecret
#### 您遇到了什么问题？ | What are your problems?
如图：
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/d4930fb1-3112-42de-b31f-0c9d3cc074c5)

#### 您期望的结果是怎样的？ | What is your expected outcome?
这里加入钉钉应用的appkey和appsecret有什么效果

**Comment by eryajf** [comment]
您好 @MysTer1ous👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @MysTer1ous. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by MysTer1ous** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/73ffa525-83eb-45ef-818d-4da056cf155b)

**Comment by MysTer1ous** [comment]
我想后续想用命令：ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f ou.ldif
加ou请问怎么加呢，是进入哪个docker容器里面？

**Comment by eryajf** [comment]
> 我想后续想用命令：ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f ou.ldif 加ou请问怎么加呢，是进入哪个docker容器里面？

如果配置正确，这个ou在ldap容器启动之后会自动加上，你应该再检查一下配置

**Comment by MysTer1ous** [comment]
> #### 您使用的版本？ | Your usage version?
> docker-compose lasted
> 
> #### 您使用的场景？ | Your usage scenarios?
> 阿里云
> 
> #### 您做了什么操作？ | What did you do?
> 按照文档自定义basedn，在config/config.yml加入了钉钉应用的appkey和appsecret
> 
> #### 您遇到了什么问题？ | What are your problems?
> 如图： ![image](https://user-images.githubusercontent.com/28255159/249985914-d4930fb1-3112-42de-b31f-0c9d3cc074c5.png)
> 
> #### 您期望的结果是怎样的？ | What is your expected outcome?
> 这里加入钉钉应用的appkey和appsecret有什么效果

请问这个报错是哪里的问题呀

**Comment by MysTer1ous** [comment]
> 



> > 我想后续想用命令：ldapadd -x -D "cn=admin,dc=mydomain,dc=com" -W -f ou.ldif 加ou请问怎么加呢，是进入哪个docker容器里面？
> 
> 如果配置正确，这个ou在ldap容器启动之后会自动加上，你应该再检查一下配置

我是放在docs/docker-compose/add_ou.ldif，会自动加上这个新的ou是么，前提是我的ou写的正确
