### ISSUE TITLE
🙋 钉钉能够获取到部门，但不能获取到用户

### ISSUE THREAD

**Issue by skret028** [eryajf/go-ldap-admin#231]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
v0.5.10 2023-04-25 
### 预期行为 | Expected behavior
拉取到用户列表
### 实际行为 | Actual behavior
没有拉取到
### 问题重现步骤 | Steps to reproduce the problem
1、分组配置：
![eb3f6a13ad978f209f370fb7406083fa](https://github.com/eryajf/go-ldap-admin/assets/107525301/f3165d53-d09b-487a-833b-c2bb2ac0867b)
![e69200255e0087ba090bfd294724819b](https://github.com/eryajf/go-ldap-admin/assets/107525301/1ecd7b4c-3017-434f-93d9-236378a0ea90)
2、拉取到的部门列表：
![6a1cb811db8e28705c4d95c951dcdca1](https://github.com/eryajf/go-ldap-admin/assets/107525301/143564e8-68af-4b7d-b0b5-dd804f4e87f7)
3、拉取用户失败：
![f47037863fed1d7cbd088f93603896c6](https://github.com/eryajf/go-ldap-admin/assets/107525301/67daa237-0620-4311-b144-eb83f58c2b74)
![cb298fe09412535d6c15fa41e6444c1b](https://github.com/eryajf/go-ldap-admin/assets/107525301/47c2d248-905c-4f1a-899e-a7da3ba910e0)
4、oplenldap组织：
![f9dd53820086118c1c035db16dd319c6](https://github.com/eryajf/go-ldap-admin/assets/107525301/2bb4fe6f-0313-41fa-8a1f-4deb01d52bf0)
5、go-ldap-admin-server日志
![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/6a742767-3851-4cae-889b-309a8a68bae8)

**Comment by eryajf** [comment]
您好 @skret028👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @skret028. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by skret028** [comment]
6、config/init.ldif已修改
![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/0dbec647-598b-4efe-8962-1987aaa05771)
7、confing/config.yml中ldap配置已修改
![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/24025376-f360-4f12-9900-2e576ffb5572)

**Comment by eryajf** [comment]
首先要给这个issue点赞，非常标准且完整。

我看了下，可能问题主要出在这里：

<img width="838" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/33259379/63dc54d0-5d84-4248-a60f-e13124435b82">

看看字段关系这张表里，有没有这条记录，是不是当时创建的时候没有成功呢

**Comment by skret028** [comment]
是在mysql: go-ldap-admin/field_relations 表里吗？
![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/36f8a9d2-6c49-4e38-bcd2-0d45c813dd79)
{"mail": "email", "avatar": "avatar", "mobile": "mobile", "remark": "name", "nickname": "name", "position": "title", "username": "custom_name_pinyin", "givenName": "name", "groupName": "custom_name_pinyin", "jobNumber": "job_number", "introduction": "remark", "sourceDeptId": "id", "sourceUserId": "userid", "postalAddress": "work_place", "sourceUnionId": "unionid", "sourceDeptParentId": "parentid"}
感觉是正常的呢？

**Comment by skret028** [comment]
错误好像是这里触发的：

![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/9bc77c93-c81b-4594-b364-28775b998666)

**Comment by skret028** [comment]
找到问题了原因了：
1、报错内容：
SELECT* FROM 'field relations' WHERE 'flag'= 'dingtalk user' AND 'field relations'. deleted at' IS NULL ORDER BY 'field relations'. 'id' 
是在filed_relation里没找到flag=dingtalk_user的数据，因为我只有一条flag=dingtalk_group的数据。

2、错误原因
因为我是填写了“用户动态字段关联”同时也填写“分子字段动态关联”，再点确定，这就导致只保存了“dingtalk_group“一条数据，并且内容包含了用户和分组的关联内容。
第一次用没有看出来，正好也没有截字段标识的图。

3、解决办法
分别单独填写“字段关系管理”中“用户字段动态关联“和”分组字段动态关联“后，拉取成功。
![image](https://github.com/eryajf/go-ldap-admin/assets/107525301/d76a5f49-2de5-4b56-b1d8-38fced8f71d6)

4、修改建议
（1）延续当前一次填写两个标签的方式，但是保存时拆分为两条，编辑时也可选择标签作修改。
（2）修改标签选择为下拉选择或更明确的方式，并且保存时只保存该标签下的映射内容。
