### ISSUE TITLE
🐛已经有group，新增用户选定不了group，有’禁止‘的图标，group是灰色的

### ISSUE THREAD

**Issue by MysTer1ous** [eryajf/go-ldap-admin#232]
#### 您使用的版本？ | Your usage version?
ui:v0.5.12
#### 您使用的场景？ | Your usage scenarios?
在cnetos7系统上搭建的go-ldap-admin
#### 您做了什么操作？ | What did you do?
我在go-ldap-admin-ui新建的几个group，新建用户时不能指定group，group显示时灰色的
#### 您遇到了什么问题？ | What are your problems?
在go-ldap-adin界面新增用户后不能加入指定组，如图
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/15e969f9-8e1b-401c-a7b7-4e8a7ded442a)
光标移到group会有禁止的图标
#### 您期望的结果是怎样的？ | What is your expected outcome?
我在新建user后能加入指定group

**Comment by eryajf** [comment]
您好 @MysTer1ous👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @MysTer1ous. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
看这里： http://ldapdoc.eryajf.net/pages/5683c6/

**Comment by MysTer1ous** [comment]
> 看这里： http://ldapdoc.eryajf.net/pages/5683c6/

明白，不过我后续添加user有如下报错呢请问
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/a7ae58c6-b86b-4d10-b83f-25d75750f0d6)

**Comment by MysTer1ous** [comment]
> > 看这里： http://ldapdoc.eryajf.net/pages/5683c6/
> 
> 明白，不过我后续添加user有如下报错呢请问 ![image](https://user-images.githubusercontent.com/28255159/252544102-a7ae58c6-b86b-4d10-b83f-25d75750f0d6.png)

![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/29adaa14-74b8-4e6a-a27c-b215e2bd7f49)

**Comment by MysTer1ous** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/28255159/13d8f268-1c46-4179-a14f-5d7fd1109518)

**Comment by eryajf** [comment]
> ![image](https://user-images.githubusercontent.com/28255159/252572350-13d8f268-1c46-4179-a14f-5d7fd1109518.png)

这个报错的意思是用户名重复了
