### ISSUE TITLE
修改飞书自动同步，手动同步报错“Client.Timeout exceeded while awaitina headers”

### ISSUE THREAD

**Issue by Young-3** [eryajf/go-ldap-admin#233]
#### 您使用的版本？ | Your usage version?
2023-04-25
#### 您使用的场景？ | Your usage scenarios?
飞书用户自动同步
#### 您做了什么操作？ | What did you do?
修改：
enable-sync: true  # 是否开启定时同步飞书的任务
dept-sync-time: "0 20 0 * * *" # 部门同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点
user-sync-time: "0 40 0 * * *" # 用户同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点,注意请把用户同步的任务滞后于部门同步时间,比如部门为2点,则用户为3点
#### 您遇到了什么问题？ | What are your problems?
修改“false”为“true”后，手动同步报错
"获取飞书用户列表失败: Post "https:/open.feishu.cn/open-apis/auth/3/tenant_access_token/internal": context deadline exceeded
(Client.Timeout exceeded while awaitina headers)"
#### 您期望的结果是怎样的？ | What is your expected outcome?
修改配置后，同步正常

**Comment by eryajf** [comment]
您好 @Young-3👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Young-3. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
创建飞书应用等步骤有没有做呢，详见：http://ldapdoc.eryajf.net/pages/83c90b/

**Comment by eryajf** [comment]
这个参数作为自动同步的配置，所以看起来没问题了
