### ISSUE TITLE
关于ldap版本的问题

### ISSUE THREAD

**Issue by dangaoxia** [eryajf/go-ldap-admin#234]
部署的是ldap 2.5的版本 新增组织的时候报错 LDAP Result Code 53 "Unwilling To Perform": operation not permitted within namingContext 现在只能查看数据不能进行新增或者修改

**Comment by eryajf** [comment]
您好 @dangaoxia👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @dangaoxia. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
你的ldap是通过什么方式部署的呢

建议使用与这个项目一致的版本。

**Comment by dangaoxia** [comment]
是在cenos7上用二进制文件启动的，用mysql作为存储

**Comment by dangaoxia** [comment]
现在无法通过页面去操作数据，只能从ldap读取数据

**Comment by eryajf** [comment]
还是建议你使用与项目一致的版本。其他版本未经测试。
