### ISSUE TITLE
无法向ldap同步用户信息

### ISSUE THREAD

**Issue by dangaoxia** [eryajf/go-ldap-admin#235]
#### 您使用的版本？ | Your usage version?
docker-compose在本地快速拉起的测试环境
#### 您使用的场景？ | Your usage scenarios?
测试
#### 您遇到了什么问题？ | What are your problems?
对用户进行操作会导致报错，无法同步到ldap
<img width="947" alt="截屏2023-07-13 21 44 50" src="https://github.com/eryajf/go-ldap-admin/assets/57345969/ba39fe8e-c91e-4a52-bff3-be11d9234800">

**Comment by eryajf** [comment]
通过compose拉起，是否有更改什么配置，按说compose拉起的不应该会有这个问题

**Comment by dangaoxia** [comment]
因为通过compose拉起来的mysql没办法启动，所以改成腾讯云5.7的云数据库，其他没有改动了

**Comment by dangaoxia** [comment]
[Entrypoint] MySQL Docker Image 5.7.38-1.2.8-server
[Entrypoint] Initializing database
2023-07-14T01:42:09.084413Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2023-07-14T01:42:09.085541Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2023-07-14T01:42:09.085564Z 0 [ERROR] Aborting
这个镜像感觉是没做好，换了服务器也是一样的报错

**Comment by eryajf** [comment]
我在Mac以及Linux上都验证过没有问题。

你直接参考这里的配置试试呢：http://ldapdoc.eryajf.net/pages/f081dc/#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by dangaoxia** [comment]
额。我用m1的mac部署mysql也是一样不能启动，报错一样的

**Comment by dangaoxia** [comment]
<img width="1089" alt="截屏2023-07-14 10 23 12" src="https://github.com/eryajf/go-ldap-admin/assets/57345969/ab2bb4bf-872d-4cc3-96e1-7167fb6561b8"> 我把mysql的挂载目录取消后启动起来，但是依旧无法使用

**Comment by eryajf** [comment]
我刚刚重新在本地Mac启动是没有问题的，一下就起来了。你的这个错误看起来是初始化数据的问题，建议你重新基于此处（https://github.com/eryajf/go-ldap-admin/tree/main/docs/docker-compose） ，在一个干净的目录中，拉起。

<img width="1591" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/33259379/a0cfb7dd-3679-4d71-a255-2609556a5a41">

**Comment by gamesme** [comment]
排查许久 应该是默认的ldap架构缺少 ou=people,dx=yourname,dx=com 这条entry

**Comment by eryajf** [comment]
> 排查许久 应该是初始化时的ldap架构缺少 `ou=people,dc=yourname,dc=com` 这条entry

有不少人的体验过程不顺利，就是因为这里没有按照官方文档要求的走，导致自己走弯路。
