### ISSUE TITLE
🙋 同步im用户数据问题

### ISSUE THREAD

**Issue by dangaoxia** [eryajf/go-ldap-admin#236]
比如钉钉员工变更部门后不会更新

**Comment by eryajf** [comment]
您好 @dangaoxia👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @dangaoxia. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
目前部门变更并没有添加同步逻辑。之前考虑是部门变化可能是一个频繁的，而有些权限依赖部门控制，因此这块儿就没有做实时的同步对齐

**Comment by dangaoxia** [comment]
向第三方同步的userid这一块能同步到ldap吗

**Comment by eryajf** [comment]
同步什么样的字段到ldap的哪个属性，取决于字段关系管理当中你的配置规则。你可以阅读一下这块儿的文档介绍 http://ldapdoc.eryajf.net/pages/84953d/

**Comment by dangaoxia** [comment]
ldap不是很了解，按照文档的意思那就是我可以对字段进行取舍，比如把ldap的employeeNumber字段映射成userid，感谢作者解惑🙏

**Comment by eryajf** [comment]
> 比如把ldap的employeeNumber字段映射成userid

对，这是正解
