### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by huxiangquan** [eryajf/go-ldap-admin#237]
1，因为用户邮件格式错误导致不能同步到ldap中，此时再编辑用户资源无法保存，编辑的时候也会到ldap去查找，而ldap中本就没有同步成功。
2，批量或单个删除用户资料时也去查了ldap，在ldap中没有时，就中断了整个删除过程，导致无法删除，反而要先点同步用户到ldap成功才能删除。同1问题，如果本来就没同步成功也就无法删除。
3，部门页希望能只显示第一层或第二层，不要把所有部门一次性展开。
4，钉钉的只同步指定部门下的功能，类似飞书中的部门过滤希望能添加。

**Comment by eryajf** [comment]
您好 @huxiangquan👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huxiangquan. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
问题1和2其实都是一开始未曾解决的一个问题，那就是ldap数据处理的事务性，因为这个没能支持，所以才添加了用户双向手动同步的功能，算是一个曲线救国。

问题3 因为使用的Vue组件做的展示，这个点我看看是否能有办法做一下优化。

问题4 这个理论上是能做的，只不过目前暂时没有太多精力做这个事情。
