### ISSUE TITLE
🙋 问题交流。。。 | [Question] 优雅重启

### ISSUE THREAD

**Issue by bourne-3** [eryajf/go-ldap-admin#240]
### 你使用了哪个版本？ | Which version did you use?
最新版

### 预期行为 | Expected behavior
通过cicd对项目进行部署，当重启服务时，如何实现优雅zero-down的方式重启
预期：重新部署项目时，可以仍然接受请求并处理请求
### 实际行为 | Actual behavior
目前是通过context的方式继续处理尚未断开的链接，但是没有对在重启过程中的链接进行处理

### 原因分析（如果可以） | Cause analysis (if possible)
目前仅通过context的方式处理尚未断开的链接
但是在重启的过程中，如果有链接请求到项目，无法处理该请求，当并发量大时这种case还是需要处理的

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @bourne-3👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @bourne-3. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
如果cicd部署的是go-ldap-admin，那么似乎没有必要有如此高的不中断要求吧，这只是一个管理控制面，凑中午也可以进行发布，多数时候普通用户应该是不会用到的。顶多会有一些管理员经常使用。

背后的ldap仍然一直在运行，这就够了吧。

或者是我没理解你的意思？
