### ISSUE TITLE
🙋 问题交流 如何升级版本

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#242]
## Question Report
我的服务是跑在k8s环境中的。
之前使用`go-ldap-admin-server:2022-08-06_03-23`  这个版本跑了好久，也有不少数据了。
最近想更新到最新版本`eryajf/go-ldap-admin-server:2023-07-20_12-53`。
数据库结构看起来有不少变化，应该如何更新呢？

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这是个很好的问题，说实话，项目迭代过程中，我的确忽视了这一环节。要想从22-08直接升级到当前版本，我觉得只有将数据备份，然后升级，或者拉个新的环境，尝试将数据导入，进行模拟升级，然后再正式升级。

**Comment by aosolao** [comment]
建议可在后续发布新版本时创建一个数据库更新sql脚本。针对前一个版本的数据表结构做调整。
目前我打算新建一个平台手动录入用户数据，不折腾数据库避免损坏数据。
这个工单可以关闭啦。
