### ISSUE TITLE
🐛 同步原ldap用户信息时将分组也同步了导致报错

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#243]
#### 您使用的版本？ | Your usage version?
docker image: eryajf/go-ldap-admin-ui:2023-06-21_10-39

#### 您使用的场景？ | Your usage scenarios?

首先我使用go-ldap-admin平台创建了几个分组。如下图
![Snipaste_2023-08-07_16-45-03](https://github.com/eryajf/go-ldap-admin/assets/30789071/1f46cfda-8184-454e-bd58-8ea0d3a6e41a)

然后我在“用户管理”页面点击“同步原ldap用户信息”后出现报错，似乎平台将分组也当成了用户同步了进来，而分组本身就没有mobile字段所以导入一个分组后，mobile字段为空，再导入第二个时就提示重复了。
如下图“
![Snipaste_2023-08-07_16-45-41](https://github.com/eryajf/go-ldap-admin/assets/30789071/e9830710-d75b-43e1-90e0-c58835bd5476)

我认为分组不应该被当作用户同步进来。这是否是一个bug？

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
如果是项目的默认配置拉起的服务。先创建分组，然后再点击同步用户，是不应该会出现这个情况的。

可以看下你配置文件中的 user-dn 这个配置项内容是什么。这个应该是完整的用户dn才对：

```
# ldap用户OU
  user-dn: "ou=people,dc=eryajf,dc=net"
```

**Comment by aosolao** [comment]
```
      # ldap用户OU
      user-dn: "ou=lj_tec,dc=lj-ch,dc=com"
```
我感觉 user-dn配置没有问题


![Snipaste_2023-08-08_09-41-28](https://github.com/eryajf/go-ldap-admin/assets/30789071/99a0b353-bbaa-41e2-94bf-251509c2b9d1)

![image](https://github.com/eryajf/go-ldap-admin/assets/30789071/cf08b784-a9f1-4c60-80b7-b1d1b80e722a)


我发现，如果
按照上图的做法，名为lj_tec的ou创建的时候选择创建在顶级类目，然后在其中创建cn部门，同步的时候就不会被同步进来。


我发帖时的做法是在root下创建了名为lj_tec的ou然后在其中创建cn部门，这样同步用户的时候部门分组就会被同步到。

虽然目前我的问题解决了，但之后如果需要创建多层级的部门有可能会存在问题。

**Comment by eryajf** [comment]
你这里的user-dn用法还是跟我一开始设计的有一些出入。

建议你先看下这里：http://ldapdoc.eryajf.net/pages/5683c6/

默认的用户和分组的跟路由应该是确定的，一开始就创建的。事实上一键拉起的脚本里，也有这些数据初始化的动作。

**Comment by aosolao** [comment]
如果所有用户都放在 ou=people,dc=eryajf,dc=net 下面的话，如何让用户关联部门呢？

**Comment by eryajf** [comment]
你可以添加几个用户，创建几个分组，然后把用户加到分组，再登陆phpldapadmin看看就明白了

**Comment by aosolao** [comment]
你的意思是，先创建用户，创建用户的时候不要选分组。
然后再编辑添加分组。
是吗？

**Comment by eryajf** [comment]
可以

**Comment by aosolao** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/30789071/3273e4b6-cfda-4f5e-bfec-377f7295b34d)

但所属部门，是必填项目，创建用户的时候应该怎么选择呢？
上层的 ou=lj_tec,dc=lj-ch,dc=com 是ou没办法选择

**Comment by aosolao** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/30789071/12b6223f-be8b-44a2-87c3-90190a4319df)


这是一开始创建的用户和分组。看起来似乎没问题？
这是在创建时就选择了部门的。
但这样创建，在用户页面同步还是会把分组同步到用户列表里

**Comment by aosolao** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/30789071/93d8f22b-d90e-4f11-83bb-d27412744999)
突然理解了，我想我可能没问题了

**Comment by eryajf** [comment]
> ![image](https://user-images.githubusercontent.com/30789071/258979792-93d8f22b-d90e-4f11-83bb-d27412744999.png) 突然理解了，我想我可能没问题了

正解
