### ISSUE TITLE
🐛 一些问题 新建用户报错

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#244]
#### 您使用的版本？ | Your usage version?
docker image: eryajf/go-ldap-admin-ui:2023-06-21_10-39

#### 您使用的场景？ | Your usage scenarios?
一个全新部署的环境，已经创建好了部门、用户组。
到创建用户的步骤时报错。
用户已经添加到go-ldap-admin数据库中，但是没有添加到openldap中，点击同步或者编辑，都无法写入openldap
![Snipaste_2023-08-07_17-49-19](https://github.com/eryajf/go-ldap-admin/assets/30789071/5ee917e3-5c19-4d00-be34-2d22043c7995)

openldap的日志如下：
```
64d0be03 conn=1003 op=67 ADD dn="uid=anfang,ou=lj_tec,dc=lj-ch,dc=com"
64d0be03 conn=1003 op=67 RESULT tag=105 err=32 text=

```

go-ldap-admin-server的日志如下：
```
2023/08/07 18:01:27 放回了一个 LDAP 连接
[GIN] 2023/08/07 - 18:01:27 | 200 |    9.850486ms |     10.233.80.0 | POST     "/api/user/syncSqlUsers"
[GIN] 2023/08/07 - 18:01:27 | 200 |    7.191944ms |     10.233.80.0 | GET      "/api/user/list?username=&nickname=&status=&syncState=&mobile=&pageNum=1&pageSize=10"
[GIN] 2023/08/07 - 18:01:36 | 200 |    4.849222ms |     10.233.80.0 | GET      "/api/group/tree?pageNum=1&pageSize=1000"
2023/08/07 18:01:37 放回了一个 LDAP 连接
[GIN] 2023/08/07 - 18:01:37 | 200 |   11.437503ms |     10.233.80.0 | POST     "/api/user/update"
[GIN] 2023/08/07 - 18:01:38 | 200 |    7.567044ms |     10.233.80.0 | GET      "/api/user/list?username=&nickname=&status=&syncState=&mobile=&pageNum=1&pageSize=10"

```

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
