### ISSUE TITLE
🙋 问题交流。。。 企微邮箱同步问题

### ISSUE THREAD

**Issue by a22124497** [eryajf/go-ldap-admin#245]
您使用的版本？ | Your usage version?
docker-compose在本地快速拉起的测试环境

您使用的场景？ | Your usage scenarios?
测试

您遇到了什么问题？ | What are your problems?
已按照 这个修改为自定义http://ldapdoc.eryajf.net/pages/adb742/修改了 config.yml，docker-compose.yml，init.ldif
sed -i  's/dc=eryajf/dc=inchitech/g' 
sed -i  's/dc=net/dc=com/g'  
sed -i  's/eryajf.net/inchitech.com/g' 

ldap中 登陆已经是 cn=admin,dc=inchitech,dc=com  的自定义名字，8090登陆后看到的dc也是我自定义的名字
现在的问题是，邮箱不对，我用的企业微信同步，用户字段 中biz_email或email，他都是用的拼音加eryajf.net 生成的邮箱，而不是获取 的邮箱 ，至少他后缀就不对
docker compose 下的那个 sql/goxxx.sql好像是不生效的   
配置如下，不知道我是哪边漏了没改对

config.yml
————————————————————————————————————

# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  # url前缀
  url-path-prefix: api
  # 程序监听端口
  port: 8888
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: true
  # rsa公钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-public-key: go-ldap-admin-pub.pem
  # rsa私钥文件路径(config.yml相对路径, 也可以填绝对路径)
  rsa-private-key: go-ldap-admin-priv.pem

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

database:
  # 数据库类型 mysql sqlite3
  driver: mysql
  # 数据库连接sqlite3数据文件的路径
  source: go-ldap-admin.db

mysql:
  # 用户名
  username: root
  # 密码
  password: 123456
  # 数据库名
  database: go_ldap_admin
  # 主机地址
  host: mysql
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: test jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12000
  # 刷新token最大过期时间, 小时
  max-refresh: 12000

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200

# email configuration
email:
  port: '465'
  user: 'test@163.com'
  from: 'go-ldap-admin后台'
  host: 'smtp.163.com'
  # is-ssl: true
  pass: '123456'

# # ldap 配置
ldap:
  # ldap服务器地址
  url: ldap://openldap:389
  # ladp最大连接数设置
  max-conn: 10
  # ldap服务器基础DN
  base-dn: "dc=inchitech,dc=com"
  # ldap管理员DN
  admin-dn: "cn=admin,dc=inchitech,dc=com"
  # ldap管理员密码
  admin-pass: "123456"
  # ldap用户OU
  user-dn: "ou=people,dc=inchitech,dc=com"
  # ldap用户初始默认密码
  user-init-password: "123456"
  # 是否允许更改分组DN
  group-name-modify: false
  # 是否允许更改用户DN
  user-name-modify: false
# 📢 即便用不到如下三段配置信息，也不要删除，否则会有一些奇怪的错误出现
dingtalk:
  # 配置获取详细文档参考： http://ldapdoc.eryajf.net/pages/94f43a/
  flag: "dingtalk" # 作为钉钉在平台的标识
  app-key: "xxxxxxxxxxxxxxx" # 应用的key
  app-secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx" # 应用的secret
  agent-id: "12121212" # 目前agent-id未使用到，可忽略
  enable-sync: false  # 是否开启定时同步钉钉的任务
  dept-sync-time: "0 30 2 * * *" # 部门同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点
  user-sync-time: "0 30 3 * * *" # 用户同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点,注意请把用户同步的任务滞后于部门同步时间,比如部门为2点,则用户为3点
wecom:
  # 配置获取详细文档参考：http://ldapdoc.eryajf.net/pages/cf1698/
  flag: "wecom" # 作为微信在平台的标识
  corp-id: "ww2edfc06" # 企业微信企业ID
  agent-id: 1000003 # 企业微信中创建的应用ID
  corp-secret: "zurKMo6N_rxpaNDCSmE5_6" # 企业微信中创建的应用secret
  enable-sync: false # 是否开启定时同步企业微信的任务
  dept-sync-time: "0 30 2 * * *" # 部门同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点
  user-sync-time: "0 30 3 * * *" # 用户同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点,注意请把用户同步的任务滞后于部门同步时间,比如部门为2点,则用户为3点
feishu:
  # 配置获取详细文档参考：http://ldapdoc.eryajf.net/pages/83c90b/
  flag: "feishu" # 作为飞书在平台的标识
  app-id: "xxxxxxx" # 飞书的app-id
  app-secret: "xxxxxxxxxxx" # 飞书的app-secret
  enable-sync: false  # 是否开启定时同步飞书的任务
  dept-sync-time: "0 20 0 * * *" # 部门同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点
  user-sync-time: "0 40 0 * * *" # 用户同步任务的时间点 * * * * * * 秒 分 时 日 月 周, 请把时间设置在凌晨 1 ~ 5 点,注意请把用户同步的任务滞后于部门同步时间,比如部门为2点,则用户为3点
  dept-list:      #部门列表，不设置则使用公司根部门，如果不希望添加子部门，在开头加上^
    # - "^od-xxx"
    # - "od-xxx"
  enable-bot-inform: false
+++++++++++++++++++++++++++++++++++++++++++++++++++++++

init.ldif
——————————————————————————————————
dn: ou=people,dc=inchitech,dc=com
ou: people
description: 用户根目录
objectClass: organizationalUnit

dn: ou=dingtalkroot,dc=inchitech,dc=com
ou: dingtalkroot
description: 钉钉根部门
objectClass: top
objectClass: organizationalUnit

dn: ou=wecomroot,dc=inchitech,dc=com
ou: wecomroot
description: 企业微信根部门
objectClass: top
objectClass: organizationalUnit

dn: ou=feishuroot,dc=inchitech,dc=com
ou: feishuroot
description: 飞书根部门
objectClass: top
objectClass: organizationalUnit

+++++++++++++++++++++++++++++++++++++++

docker-compose.yaml

version: '3'

networks:
  go-ldap-admin:
    driver: bridge

services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/mysql-server:5.7
    container_name: go-ldap-admin-mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    hostname: go-ldap-admin-mysql
    restart: always # 设置容器自启模式
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Shanghai # 设置容器时区与宿主机保持一致
      MYSQL_ROOT_PASSWORD: 123456 # 设置root密码
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: go_ldap_admin
    volumes:
      # 数据挂载目录自行修改哦！
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - ./data/mysql:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
      - ./config/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问
    networks:
      - go-ldap-admin

  openldap:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/openldap:1.4.0
    container_name: go-ldap-admin-openldap
    hostname: go-ldap-admin-openldap
    restart: always
    environment:
      TZ: Asia/Shanghai
      LDAP_ORGANISATION: "inchitech.com"
      LDAP_DOMAIN: "inchitech.com"
      LDAP_ADMIN_PASSWORD: "123456"
    command: [ '--copy-service' ]
    volumes:
      - ./data/openldap/database:/var/lib/ldap
      - ./data/openldap/config:/etc/ldap/slapd.d
      - ./config/init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
    ports:
      - 388:389
    networks:
      - go-ldap-admin

  phpldapadmin:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/phpldapadmin:0.9.0
    container_name: go-ldap-admin-phpldapadmin
    hostname: go-ldap-admin-phpldapadmin
    restart: always
    environment:
      TZ: Asia/Shanghai # 设置容器时区与宿主机保持一致
      PHPLDAPADMIN_HTTPS: "false" # 是否使用https
      PHPLDAPADMIN_LDAP_HOSTS: go-ldap-admin-openldap # 指定LDAP容器名称
    ports:
      - 8091:80
    volumes:
      - ./data/phpadmin:/var/www/phpldapadmin
    depends_on:
      - openldap
    links:
      - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
    networks:
      - go-ldap-admin

  go-ldap-admin-server:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-server
    container_name: go-ldap-admin-server
    hostname: go-ldap-admin-server
    restart: always
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, openldap:389
    ports:
      - 8888:8888
    volumes:  # 可按需打开此配置，将配置文件挂载到本地 可在服务运行之后，执行 docker cp go-ldap-admin-server:/app/config.yml ./config 然后再取消该行注释
      - ./config/config.yml:/app/config.yml
    depends_on:
      - mysql
      - openldap
    links:
      - mysql:go-ldap-admin-mysql # ldap容器的 service_name:container_name
      - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
    networks:
      - go-ldap-admin

  go-ldap-admin-ui:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-ui
    container_name: go-ldap-admin-ui
    hostname: go-ldap-admin-ui
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8090:80
    depends_on:
      - go-ldap-admin-server
    links:
      - go-ldap-admin-server:go-ldap-admin-server
    networks:
      - go-ldap-admin

**Comment by eryajf** [comment]
您好 @a22124497👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @a22124497. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
