### ISSUE TITLE
运行时报一下错

### ISSUE THREAD

**Issue by 13265435206** [eryajf/go-ldap-admin#247]
# github.com/eryajf/go-ldap-admin/service/isql
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\service\isql\user_isql.go:176:18: invalid operation: funk.MinInt(roleSortList) (value of type int) is not an interface
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\service\isql\user_isql.go:197:29: invalid operation: funk.MinInt(currentRoleSorts) (value of type int) is not an interface
# github.com/eryajf/go-ldap-admin/public/client/dingtalk
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:51:29: rsp.DeptDetailUsers undefined (type response.DeptDetailUserInfo has no field or method DeptDetailUsers)
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:80:12: rsp.HasMore undefined (type response.DeptDetailUserInfo has no field or method HasMore)
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:83:19: rsp.NextCursor undefined (type response.DeptDetailUserInfo has no field or method NextCursor)
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:106:25: rsp.UserIds undefined (type response.GetHrmEmployee has no field or method UserIds)
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:107:10: rsp.NextCursor undefined (type response.GetHrmEmployee has no field or method NextCursor)
C:\Program Files\AllSoft\Go\pkg\mod\github.com\eryajf\go-ldap-admin@v0.5.9\public\client\dingtalk\dingtalk.go:110:24: rsp.NextCursor undefined (type response.GetHrmEmployee has no field or method NextCursor)

**Comment by eryajf** [comment]
您好 @13265435206👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @13265435206. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
