### ISSUE TITLE
🚀 添加对Oauth2登录的支持

### ISSUE THREAD

**Issue by RavenLiao** [eryajf/go-ldap-admin#249]
#### 您使用的场景？ | 1. Your usage scenarios?
希望支持飞书登录等第三方登录。
飞书是可以通过自建应用进行Oauth2登录的。希望添加支持。
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
添加飞书登录，可以一键登录后台，以及通过登录页面颁发token，可以让treafik等网关使用。

而且支持Oauth2支持可以解决重置密码的问题。IM用户注册后可不设置默认密码，只能通过oauth2登录来初始化密码。

**Comment by eryajf** [comment]
您好 @Raven-L👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Raven-L. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
