### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chenconghe** [eryajf/go-ldap-admin#250]
#### 您使用的版本？ | Your usage version?
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/mysql-server:5.7
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/openldap:1.4.0
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/phpldapadmin:0.9.0
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-server
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-ui
#### 您使用的场景？ | Your usage scenarios?
测试环境
#### 您做了什么操作？ | What did you do?
按照文档修改了自定义域名，将config.yml init.ldif docker-compose.yml里面的默认域名修改成我们公司的域名
#### 您遇到了什么问题？ | What are your problems?
修改完后docker-compose重启后go-ldap-admin-server的日志就提示标题上面显示的错误，然后不断重启，浏览器访问就提示502错误
![image](https://github.com/eryajf/go-ldap-admin/assets/59158123/15a92444-7127-456b-a2ce-11bdf033c4a8)

![image](https://github.com/eryajf/go-ldap-admin/assets/59158123/27e51c9a-f9d3-488d-845c-a2a469bde794)

#### 您期望的结果是怎样的？ | What is your expected outcome?
我想达到的最基本的目的就是能够将默认的域名修改成自定义的域名并且可以使用就可以

**Comment by eryajf** [comment]
您好 @chenconghe👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @chenconghe. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
看报错应该是配置有问题，有配置没有正常加载导致的

**Comment by airwin** [comment]
我也是类似的报错，也是本地改了配置后拉起就报错，不过我的initConfig没报错，下面的initDB报的 -.-
`
2023-09-22 14:33:12     INFO    common/logger.go:110    github.com/eryajf/go-ldap-admin/public/common.InitLogger        初始化zap日志完成!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe18de1]

goroutine 1 [running]:
github.com/eryajf/go-ldap-admin/public/common.InitDB()
        /app/public/common/database.go:19 +0x21
main.main()
        /app/main.go:29 +0x4f
`

**Comment by airwin** [comment]
看了一下代码，应该是新旧版本的config.yml不同导致的，新版config增加了database项，旧版本的只有mysql项

**Comment by eryajf** [comment]
> 看了一下代码，应该是新旧版本的config.yml不同导致的，新版config增加了database项，旧版本的只有mysql项

按说配置应该只有一份，你的旧配置是从哪里获取的呢

**Comment by airwin** [comment]
> > 看了一下代码，应该是新旧版本的config.yml不同导致的，新版config增加了database项，旧版本的只有mysql项
> 
> 按说配置应该只有一份，你的旧配置是从哪里获取的呢

我是在迁移的时候拷了一个旧版的config.yml过来导致的，如果按照说明从服务里面直接copy再改就没事了

**Comment by airwin** [comment]
遇到了新的问题，导入了备份的mysql数据后，管理员登录报错“没有权限” @eryajf
