### ISSUE TITLE
🙋 问题交流。。。 | [问题] 关于登录密码错误的提示？

### ISSUE THREAD

**Issue by KIKIZONG** [eryajf/go-ldap-admin#251]
## Question Report

亲们，我按照官方的 “CentOS7 安装 Go-Ldap-Admin”教程一步步执行，http://ldapdoc.eryajf.net/pages/866885/#%E5%AE%89%E8%A3%85%E6%95%B0%E6%8D%AE%E5%BA%93

均没有发生错误，但是在打开web管理页面，

输入用户名admin密码123456的时候，系统提示用户名或密码错误，请保留在此页面或重新输入的提示框。

虽然ldap生成的密码是 嘻哈加密的，但是密码确认是 123456没有错的。请教下各位大牛是否有解或者有其他什么解决方案，多谢！

**Comment by eryajf** [comment]
还是那个老问题，这篇文章开头已经说明了前置注意。

建议使用docker-compose拉起的方式进行体验与实际使用

**Comment by qif580231** [comment]
我也遇到了这个问题，现在是接入在用的openldap环境。go-ldap-admin部署完成后提示密码错误。请问应该如何解决，还是配置文件填写有问题。

**Comment by eryajf** [comment]
对接自用的，需要确保config中配置正确，这块儿有几个地方需要修改。详见：http://ldapdoc.eryajf.net/pages/adb742/

建议先部署demo体验，然后体会里边的配置以及功能。熟悉之后再对接原有的ldap
