### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by hzyinliang** [eryajf/go-ldap-admin#255]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
latset

### 预期行为 | Expected behavior
钉钉账号同步到openldap
### 实际行为 | Actual behavior
部署 go ldap admin -容器拉起的方式。配置钉钉同步，完成账号同步！但是测试后发现，如果钉钉账号信息在同步后做了修改，如钉钉账号调整了部门，或者更改了邮箱字段，go ldap admin同步后，该账号不会自动更新成新的部门或者新的邮箱！
### 原因分析（如果可以） | Cause analysis (if possible)
不详！
### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @hzyinliang👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @hzyinliang. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by hzyinliang** [comment]
钉钉账号更新了邮箱或者部门，手动或者自动更新GO LDAP ADMIN，GO LDAP ADMIN内的该账户无法自动更新成新的部门或者邮箱！

**Comment by eryajf** [comment]
这个问题的确存在，一开始故意这么设计的，因为有的公司组织架构变更太快，有时候一些授权会与ldap绑定，所以盲目跟随组织架构变动，可能会导致权限系统错乱。

不过这个问题的确有不少人提过。

后边我考虑加一个开关的配置，将这个功能可配置化，供使用者选择
