### ISSUE TITLE
🐛 一些问题。。。 | [Bug] 如何关闭SQL日志和操作日志

### ISSUE THREAD

**Issue by ylighgh** [eryajf/go-ldap-admin#265]
#### 您使用的版本？ | Your usage version?

v0.5.10 2023-04-25

#### 您使用的场景？ | Your usage scenarios?

LDAP密码重置

#### 您做了什么操作？ | What did you do?

无

#### 您遇到了什么问题？ | What are your problems?

1. 配置文件中 mysql.log-mode为false时，标准输出中仍然能够看见sql执行的日志，如何关闭

2. 我不希望将每次请求的url 记录 存入 operation_logs 表中，如何关闭该功能

#### 您期望的结果是怎样的？ | What is your expected outcome?

解决上面两个问题

**Comment by eryajf** [comment]
您好 @ylighgh👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ylighgh. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ylighgh** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/59725600/c3a05729-d2e9-4e70-9926-3b37c452ade0)
![image](https://github.com/eryajf/go-ldap-admin/assets/59725600/c3931027-506a-46cf-8c7d-e2117ac7d961)

**Comment by eryajf** [comment]
这是个问题，我随后看看支持一下这个能力

**Comment by ylighgh** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/59725600/83e2b576-84dc-4708-ad52-0b59674ece3a)
我在初始化orm模型的暴力时候加了一个这个配置 `Logger: logger.Default.LogMode(logger.Silent)` 就不会显示sql在标准输出中了，但是数据库中的 opertaion_log 我还没有找到怎么关闭

**Comment by eryajf** [comment]
应该注释掉这句就好了： 

https://github.com/eryajf/go-ldap-admin/blob/30c9a71d438acf0e178728561c03458848676b9e/routes/a_routes.go#L36

**Comment by ylighgh** [comment]
好的，问题已经解决，谢谢~

**Comment by eryajf** [comment]
如果有兴趣，也欢迎将这个功能点PR上来
