### ISSUE TITLE
ldap连接池  去连接window ad 过一段时间，好像连结会断开

### ISSUE THREAD

**Issue by DevOpserzhao** [eryajf/go-ldap-admin#266]
https://github.com/eryajf/go-ldap-admin/blob/main/public/common/ldap.go

我是用了这个

**Comment by eryajf** [comment]
您好 @DevOpserzhao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @DevOpserzhao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
ad我这边没有经过测试，也没有对应的环境，无法提供更多的参考

**Comment by DevOpserzhao** [comment]
目前 发现运行一段时间 就报ad错误 `LDAP Result Code 53 \"Unwilling To Perform\": 0000001F: SvcErr: DSID-031A124C, problem 5003 (WILL_NOT_PERFORM), data`
