### ISSUE TITLE
🐛 [Bug] 钉钉同步 员工部门信息在LDAP中是一个字符串 应该是一个列表

### ISSUE THREAD

**Issue by SoWhatI** [eryajf/go-ldap-admin#267]
#### 您使用的版本？ | Your usage version?
openldap:1.4.0
phpldapadmin:0.9.0
go-ldap-admin-server:latest
go-ldap-admin-ui:latest
#### 您使用的场景？ | Your usage scenarios?
钉钉同步
#### 您做了什么操作？ | What did you do?
钉钉同步
#### 您遇到了什么问题？ | What are your problems?
员工部门信息在LDAP中是一个字符串
![image](https://github.com/eryajf/go-ldap-admin/assets/31054087/9dd4c81b-2932-4447-a2b0-6a878e686fad)
#### 您期望的结果是怎样的？ | What is your expected outcome?
员工部门信息在LDAP中是一个列表
![image](https://github.com/eryajf/go-ldap-admin/assets/31054087/1373489f-da04-4f7a-8b50-41b15e9eaa7c)

**Comment by eryajf** [comment]
您好 @SoWhatI👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @SoWhatI. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
不是很明白这个issue想要表达的意思，员工部门信息希望是一个列表，有没有具体的示例呢

**Comment by SoWhatI** [comment]
如下图，第一个是目前的，期望的是第二个
![image](https://github.com/eryajf/go-ldap-admin/assets/31054087/f6e0a66f-33e3-4a46-bf7b-657f7801ca38)

**Comment by eryajf** [comment]
或者你可以说下你的应用场景大概是什么

另外请浏览该项目的用户以及分组的设计思路：http://ldapdoc.eryajf.net/pages/5683c6/

其实已经写死了两种情况，并且应该是满足当下需求的。

**Comment by SoWhatI** [comment]
em，我阅读了下代码，大约是这里的问题
https://github.com/eryajf/go-ldap-admin/blob/30c9a71d438acf0e178728561c03458848676b9e/service/ildap/user_ildap.go#L22C1-L22C1
将`user.Departments = strings.TrimRight(deptTmp, ",")`修改为`user.Departments = strings.Split(user.Departments, ",")`

**Comment by SoWhatI** [comment]
> em，我阅读了下代码，大约是这里的问题 https://github.com/eryajf/go-ldap-admin/blob/30c9a71d438acf0e178728561c03458848676b9e/service/ildap/user_ildap.go#L22C1-L22C1 将`user.Departments = strings.TrimRight(deptTmp, ",")`修改为`user.Departments = strings.Split(user.Departments, ",")`

场景是钉钉同步后，一个开源系统在接入LDAP，在有多个部门的员工出问题了

**Comment by eryajf** [comment]
是这个开源的系统会基于部门进行规则过滤吗，还是什么

之前我验证过一个人归属多个部门，那就是归属多个呗，会有什么问题吗

**Comment by SoWhatI** [comment]
比如张三归属部门A和B，按照现有的存储，这个开源系统读取的是`A,B`，它就认为是`A,B`是一个部门
