### ISSUE TITLE
🐛 GroupName的长度设置太小了。

### ISSUE THREAD

**Issue by ryugei** [eryajf/go-ldap-admin#271]
#### 您使用的版本？ | Your usage version?
0.5.11
#### 您使用的场景？ | Your usage scenarios?
对接confluence
#### 您做了什么操作？ | What did you do?
添加[confluence-administrators]用户组
#### 您遇到了什么问题？ | What are your problems?
提示GroupName的长度最大不能超过20
#### 您期望的结果是怎样的？ | What is your expected outcome?
GroupName字段允许长度放宽到40？

**Comment by eryajf** [comment]
您好 @ryugei👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ryugei. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
可以调整，晚些时候我来处理一下

**Comment by eryajf** [comment]
该问题已修复
