### ISSUE TITLE
🐛 一些问题。。。 | [Bug] 编辑用户 增删 【所属部门】报错

### ISSUE THREAD

**Issue by ryugei** [eryajf/go-ldap-admin#278]
#### 您使用的版本？ | Your usage version?
0.5.15
go-ldap-admin-server镜像ID：28ebd80af032
go-ldap-admin-ui镜像ID：b555bfc89120
#### 您使用的场景？ | Your usage scenarios?
对接JIRA
#### 您做了什么操作？ | What did you do?
用户管理界面 对admin 以外的其他用户进行编辑，为用户 增删 【所属部门】
#### 您遇到了什么问题？ | What are your problems?
报错如下：更新用户失败在LDAP更新用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": businessCategory: value #0 invalid per syntax
#### 您期望的结果是怎样的？ | What is your expected outcome?
正常返回结果

**Comment by eryajf** [comment]
您好 @ryugei👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ryugei. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
麻烦再详细一点你的操作上下文，比如是直接部署拉起之后，创建了分组，然后更新用户分组的时候报的这个错误吗

最好能给出复现步骤

**Comment by caiiicv** [comment]
我也遇到 LDAP Result Code 21 "Invalid Attribute Syntax": businessCategory: value #0 invalid per syntax 这个错误，修改basedn和配置好钉钉同步参数，docker-compose 拉起后同步钉钉分组，和同步用户都正常，但修改用户信息后保存就报错

**Comment by ryugei** [comment]
经过我自己诊断处理，我回退了你之前做的fix后就不再出现了。
回退的 fix如下：
[fix: 用户更新时提交默认分组的问题 (](https://github.com/eryajf/go-ldap-admin/commit/5343539efe381e1c45504343217669ebdbc9ccc6)https://github.com/eryajf/go-ldap-admin/pull/276[)](https://github.com/eryajf/go-ldap-admin/commit/5343539efe381e1c45504343217669ebdbc9ccc6)

**Comment by eryajf** [comment]
已复现，我来定位一下

**Comment by backlash-go** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/43260088/2ded80eb-667e-4fd0-8997-da15fc4d3fec)
![image](https://github.com/eryajf/go-ldap-admin/assets/43260088/4492f937-01f0-4174-b831-59a368a03210)

**Comment by eryajf** [comment]
@backlash-go 打开检查，然后再请求一次，看看请求的参数是怎样的
