### ISSUE TITLE
用的不是飞书，是lark，lark的api 地址怎么改呢？

### ISSUE THREAD

**Issue by fengchenggang1995** [eryajf/go-ldap-admin#280]
#### 您使用的场景？ | 1. Your usage scenarios?
lark 和 ldap 信息同步

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
lark 和ldap 打通，现在只有飞书的api 地址，看不到lark，希望能解决。

**Comment by eryajf** [comment]
您好 @fengchenggang1995👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @fengchenggang1995. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
应该是兼容的，你可以直接配置试试

**Comment by fengchenggang1995** [comment]
获取飞书部门列表失败：Get "https://open.feishu.cn/open-apis/contact/v3/departments/0/children?fetch_child=true&page_size=50&page_token=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

改成lark的appid 后，它是到飞书的地址去获取的
