### ISSUE TITLE
修改用户信息保存时报错：LDAP Result Code 21 "Invalid Attribute Syntax": businessCategory: value #0 invalid per syntax

### ISSUE THREAD

**Issue by caiiicv** [eryajf/go-ldap-admin#281]
#### 您使用的版本？ | Your usage version?
docker-compose  拉取的最新版本
#### 您使用的场景？ | Your usage scenarios?
拉库后docker-compose直接部署没有对文件进行任何修改，创建用户正常，修改用户信息并保存出现报错
#### 您做了什么操作？ | What did you do?
正常创建用户
#### 您遇到了什么问题？ | What are your problems?
修改用户信息保存时报错
#### 您期望的结果是怎样的？ | What is your expected outcome?
保存回写正常

**Comment by eryajf** [comment]
您好 @caiiicv👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @caiiicv. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
该问题已修复，拉取最新版本镜像即可
