### ISSUE TITLE
第三方系统对接openldap时无法连接

### ISSUE THREAD

**Issue by caiiicv** [eryajf/go-ldap-admin#283]
第三方系统对接openldap时无法连接，提示端口无法通讯LDAP端口已改为389，但在windwos用LdapAdmin.exe工具可以正常连接上，服务器防火墙已关闭，密码为默认的123456，而用群辉的LDAP Server 就可以正常连接上。
![Snipaste_2023-11-17_16-12-39](https://github.com/eryajf/go-ldap-admin/assets/62830679/62e6582f-69e8-48e7-bad5-c5b18091eb0c)
![Snipaste_2023-11-17_16-13-45](https://github.com/eryajf/go-ldap-admin/assets/62830679/7a436260-1c55-4abb-a520-dd0a2d98286e)
#### 您使用的版本？ | Your usage version?
docker-compose 方式部署
#### 您使用的场景？ | Your usage scenarios?
第三方系统对接
#### 您做了什么操作？ | What did you do?
与第三方平台对接
#### 您遇到了什么问题？ | What are your problems?
对接通讯异常
#### 您期望的结果是怎样的？ | What is your expected outcome?
可以正常对接第三方平台

**Comment by eryajf** [comment]
您好 @caiiicv👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @caiiicv. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
看起来超出我的认知领域了，暂时没办法帮到你

**Comment by caiiicv** [comment]
好吧！感谢！
