### ISSUE TITLE
同步写入密码时能否指定写入类型

### ISSUE THREAD

**Issue by huangjun0910** [eryajf/go-ldap-admin#285]
#### 您使用的场景？ | 1. Your usage scenarios?
用户从钉钉同步，配合radius进行WIFI及VPN认证
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
![image](https://github.com/eryajf/go-ldap-admin/assets/76147995/d5fd4d1e-ca48-4a61-b645-8abc8331815a)
当同步钉钉用户写入初始密码时是否可以指定此密码类型，还有能否产生随机密码并增加批量将密码以邮件形式发送给用户，所有密码都一样第一次发通知时会造成用户恶意更改其他人密码

**Comment by eryajf** [comment]
您好 @huangjun0910👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @huangjun0910. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
现在在平台新创建的用户已经走了 ssha 的加密方式，这里看到的clear应该是同步这里没有走这个加密方式，可以调整。你说的随机密码这个值得采纳，但是依赖通知系统是能够正常工作的才行，另外也需要确保该用户字段中的邮箱是准确可用的才行，这个可能不是大部分用户都能满足这个情况，所以还得考虑

**Comment by huangjun0910** [comment]
平台如何调整在创建默认密码时的存储方式如何调整为clear而不使用ssha呢，没有看到有对应配置的地方

**Comment by eryajf** [comment]
> 平台如何调整在创建默认密码时的存储方式如何调整为clear而不使用ssha呢，没有看到有对应配置的地方

目前没有这项配置，我晚些时候把这个做成可配置的
