### ISSUE TITLE
现在支持lark了吗？

### ISSUE THREAD

**Issue by fengchenggang1995** [eryajf/go-ldap-admin#286]

**Comment by eryajf** [comment]
您好 @fengchenggang1995👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @fengchenggang1995. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
