### ISSUE TITLE
🙋 问题交流。。。 | [Question] 钉钉同步失败问题

### ISSUE THREAD

**Issue by wh1te3zzz** [eryajf/go-ldap-admin#288]
## Question Report
同步钉钉用户或者部门失败，提示“转换钉钉部门数据失败：record not found”、“转换钉钉用户数据失败：record not found”
- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
0.5.15
### 预期行为 | Expected behavior
同步钉钉员工与部门
### 实际行为 | Actual behavior
同步失败
<img width="1275" alt="微信图片_20231208181106" src="https://github.com/eryajf/go-ldap-admin/assets/96282103/e5842b23-5ceb-436b-bbf5-2c5583bf73bd">

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @wh1te3zzz👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wh1te3zzz. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
