### ISSUE TITLE
🙋 问题交流。。。 | [Question] 通过ldappasswd修改ldap密码不会在admin-server和admin-ui同步，导致两测密码不一致

### ISSUE THREAD

**Issue by babyshen** [eryajf/go-ldap-admin#289]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @babyshen👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @babyshen. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这倒是我没有想过的，已经有了这个平台，还是建议通过平台来进行操作。

**Comment by eryajf** [comment]
没有这个打算
