### ISSUE TITLE
钉钉组织架构无法同步，钉钉用户无法同步

### ISSUE THREAD

**Issue by b1uecream** [eryajf/go-ldap-admin#290]
#### 您使用的版本？ | Your usage version?
v0.5.15 2023-11-12
#### 您使用的场景？ | Your usage scenarios?
ldap同步钉钉
#### 您做了什么操作？ | What did you do?
1. 安装官方文档进行安装；
2. 在前端配置字段关系管理，如图：
钉钉用户字段关系
![user](https://github.com/eryajf/go-ldap-admin/assets/19721645/ffcdaae4-9d9b-466f-a40b-a3eed0d82e63)
钉钉组织架构字段关系
![group](https://github.com/eryajf/go-ldap-admin/assets/19721645/834762bb-8e3c-49e5-b3a3-3e9dabb75b30)
3. 在分组管理中点击同步钉钉部门，查看response，data为null
![group_result](https://github.com/eryajf/go-ldap-admin/assets/19721645/7f19e09c-6f99-4fd6-ae3a-8d233de4ee0c)
4.在用户管理中点击同步钉钉用户信息，查看 response，提示向mysql创建用户失败。
![user_result](https://github.com/eryajf/go-ldap-admin/assets/19721645/5eede6c3-26fc-42d4-a7e0-abed914df324)
5.在碰到问题后，我参考了[issue#256](https://github.com/eryajf/go-ldap-admin/issues/256) 和[issue#231](https://github.com/eryajf/go-ldap-admin/issues/2310),通过第三方工具同步组织架构和用户是正常的，但页面仍然无法进行同步。
![tt_group](https://github.com/eryajf/go-ldap-admin/assets/19721645/f3e41708-c1cd-44bb-b34e-4c9e9cdfa23e)
![tt_user](https://github.com/eryajf/go-ldap-admin/assets/19721645/73961c3d-1adb-4973-977e-441b91f3cd93)

#### 您遇到了什么问题？ | What are your problems?
无法同步钉钉组织架构和钉钉用户
#### 您期望的结果是怎样的？ | What is your expected outcome?
能够顺利完成同步。

**Comment by eryajf** [comment]
您好 @b1uecream👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @b1uecream. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
同步用户的这个错误主要是ganchen的手机号与表中已有数据重复了。目前设置的手机号必须唯一，所以会有这个错误出现。

一个比较简单的解决办法是，你可以连上数据库，搜索一下user表，where一下这个手机号，先把这条数据的手机号调整下，然后再次去同步，就可以了。

**Comment by eryajf** [comment]
另外给这个反馈点个赞，非常清晰，一眼就能看出来问题。

**Comment by b1uecream** [comment]
> 同步用户的这个错误主要是ganchen的手机号与表中已有数据重复了。目前设置的手机号必须唯一，所以会有这个错误出现。
> 
> 一个比较简单的解决办法是，你可以连上数据库，搜索一下user表，where一下这个手机号，先把这条数据的手机号调整下，然后再次去同步，就可以了。

我把数据库中users表里除了admin的行都删除后，再次同步组织和用户，发现组织架构仍然无法同步，用户每次同步仅一条信息。
![group_result](https://github.com/eryajf/go-ldap-admin/assets/19721645/55850a6a-4150-470e-b447-4f2d84ea767f)

![user_result](https://github.com/eryajf/go-ldap-admin/assets/19721645/51b85031-8024-47ee-aca0-6a58213ffa98)

**Comment by eryajf** [comment]
刚刚表达的意思是只调整一下手机号字段重复的那条记录就可以了，现在清空了表，但其实ldap里边数据是还在的，所以会出现这个错误。

现在你可以把ldap持久化的目录删除，把表里对应数据也清空，从头来过一遍。

**Comment by b1uecream** [comment]
用ldap admin连接了一下openldap，发现组织架构整个是空的
![WX20231214-142526](https://github.com/eryajf/go-ldap-admin/assets/19721645/94edb792-6be8-4554-941a-e2e4dc3eaef6)

**Comment by eryajf** [comment]
按说在部门同步成功没报错之后，就应该能看到部门信息了。
建议你把所有数据删除，然后从头来过

**Comment by jiangslee** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/a4b1e395-7296-4242-9c8b-fde26fc0d504)
@eryajf 大佬有群吗，我这也同步不了用户

**Comment by eryajf** [comment]
> ![image](https://private-user-images.githubusercontent.com/27892476/290447027-a4b1e395-7296-4242-9c8b-fde26fc0d504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDExMjksIm5iZiI6MTcwMjU0MDgyOSwicGF0aCI6Ii8yNzg5MjQ3Ni8yOTA0NDcwMjctYTRiMWUzOTUtNzI5Ni00MjQyLTljOGItZmRlMjZmYzBkNTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTBiNjkzNzNiNGEyNGE1YWVjMTE3NDdlNjM3ZWU3MTE4NDhhNjlmOTczN2Q3NTM3ZGVjZjJjMzc1NTU3M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GYgDpMTQor7nESrz4ujIm3RveqqiTpk3_6TQUqo9Db4) @eryajf* 大佬有群吗，我这也同步不了用户

你这个图显示已经是在同步中了，没有给到具体的错误信息，无法定位

**Comment by jiangslee** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/22ca5bb7-dbe7-47a6-be7c-2c22ade959de)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/b3596e96-3b8a-4208-aabc-a170667f0bca)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/fde2af26-618a-40dd-af67-46178eb16876)
同步部门一闪而过，没有报错信息，同步用户就如前贴的图，刷完啥也没留下来。。。找不到报错信息

**Comment by eryajf** [comment]
> 同步部门一闪而过，没有报错信息

这个一闪而过之后，看group表里，是否有对应的部门数据呢，按说同步成功了，就不应该没数据的。看你上边用tools也是能拿到的

**Comment by jiangslee** [comment]
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/826befd5-1f36-4e6a-b0fd-f496622200b7)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/521f44b8-affb-4545-a5d3-1c67d347c5cb)

没有呢，昨天还同步得了部门，会不会接口钉钉返回不了数据？

**Comment by jiangslee** [comment]
用户怎么都同步不了，清了数据后，部门今天也同步不了

**Comment by eryajf** [comment]
我看串了，你俩同时在一个issue里反馈，我信息混乱了。

在碰到问题后，我参考了https://github.com/eryajf/go-ldap-admin/issues/256 和[issue#231](https://github.com/eryajf/go-ldap-admin/issues/2310),通过第三方工具同步组织架构和用户是正常的，但页面仍然无法进行同步。

你也通过这里提到的工具，跑一跑，看看能不能拿到数据

**Comment by jiangslee** [comment]
> 我看串了，你俩同时在一个issue里反馈，我信息混乱了。
> 
> 在碰到问题后，我参考了#256 和[issue#231](https://github.com/eryajf/go-ldap-admin/issues/2310),通过第三方工具同步组织架构和用户是正常的，但页面仍然无法进行同步。
> 
> 你也通过这里提到的工具，跑一跑，看看能不能拿到数据

我curl跑了次department/list的接口能拿到数据，我只能再试试清空数据再重来一次。。。

**Comment by jiangslee** [comment]
@b1uecream 
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/21746e51-cfea-4546-b842-ae133ea2641f)
提示一下，你的这个值好像有误。

我重清数据获取到部门的步骤：

1. ```docker-compose down```
2. ```rm -rf ./data```
3. groups、group_users表从数据库truncate掉
4. ```docker-compose up -d```同步部门成功

可能是我用户数据太多了，同步人员超时暂时还是无法完成人员的同步。

**Comment by b1uecream** [comment]
> @b1uecream ![image](https://private-user-images.githubusercontent.com/27892476/290459895-21746e51-cfea-4546-b842-ae133ea2641f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzA2MTIsIm5iZiI6MTcwMjYzMDMxMiwicGF0aCI6Ii8yNzg5MjQ3Ni8yOTA0NTk4OTUtMjE3NDZlNTEtY2ZlYS00NTQ2LWI4NDItYWUxMzNlYTI2NDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZGM2ZGY1ZjQwODZmZjUyYWVmYWNkYzg3M2JkOWEwZTNlNThlNmI2MTE5YzM2NTMwNzg0NzIzODI5MTM4Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bQIy4rMcY8KWNpgiqbeSinnfaBorjsf8cij-KIaYY0o) 提示一下，你的这个值好像有误。
> 
> 我重清数据获取到部门的步骤：
> 
> 1. `docker-compose down`
> 2. `rm -rf ./data`
> 3. groups、group_users表从数据库truncate掉
> 4. `docker-compose up -d`同步部门成功
> 
> 可能是我用户数据太多了，同步人员超时暂时还是无法完成人员的同步。

我直接用生产环境方式部署的。

但我清空了mysql数据库里的表和ldap组织架构之后，按照[钉钉实操](http://ldapdoc.eryajf.net/pages/84953d/#%E9%92%89%E9%92%89)进行配置后，组织架构同步ok了，但同步用户的时候仍然有报错，报错信息如下：
![WX20231215-165128](https://github.com/eryajf/go-ldap-admin/assets/19721645/2c64ad0e-0333-4d84-ad84-3811ef012ba0)

**Comment by b1uecream** [comment]
找到问题的原因了，根据配置文件里面的ldap用户OU部分的配置，检查ldap，发现LDAP在同步组织架构后没有添加对应的ou，手动创建这个OU之后，进行同步，成功。
![4321](https://github.com/eryajf/go-ldap-admin/assets/19721645/17fda43e-8be6-4646-8bb3-e357133363fe)

**Comment by eryajf** [comment]
> 找到问题的原因了，根据配置文件里面的ldap用户OU部分的配置，检查ldap，发现LDAP在同步组织架构后没有添加对应的ou，手动创建这个OU之后，进行同步，成功。 ![4321](https://private-user-images.githubusercontent.com/19721645/290781754-17fda43e-8be6-4646-8bb3-e357133363fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTE5NTksIm5iZiI6MTcwMjcxMTY1OSwicGF0aCI6Ii8xOTcyMTY0NS8yOTA3ODE3NTQtMTdmZGE0M2UtOGJlNi00NjQ2LThiYjMtZTM1NzEzMzM2M2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA3MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMWM5ZWU4MzAwY2JlMWVhMWM2NDZhMTk1Y2RiOTlmNmZmNTJkZGMzZGE3MzljOGJlYjE2NTdmOTNmYWI2YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w73t-N5RDPXA3xKBTkiEgaibkrAI9hwW4juhpNoWIgs)

这个ou在这个里边定义着  https://github.com/eryajf/go-ldap-admin/blob/main/docs/docker-compose/config/init.ldif
