### ISSUE TITLE
🐛 钉钉用户列表失败 | [Bug] Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag

### ISSUE THREAD

**Issue by jiangslee** [eryajf/go-ldap-admin#291]
#### 您使用的版本？ | Your usage version?
```
$ docker compose ps -a
NAME                         IMAGE                                                               COMMAND                  SERVICE                CREATED             STATUS              PORTS
go-ldap-admin-openldap       registry.cn-hangzhou.aliyuncs.com/ali_eryajf/openldap:1.4.0         "/container/tool/run…"   openldap               18 minutes ago      Up 18 minutes       636/tcp, 0.0.0.0:388->389/tcp, :::388->389/tcp
go-ldap-admin-phpldapadmin   registry.cn-hangzhou.aliyuncs.com/ali_eryajf/phpldapadmin:0.9.0     "/container/tool/run"    phpldapadmin           18 minutes ago      Up 18 minutes       443/tcp, 0.0.0.0:8091->80/tcp, :::8091->80/tcp
go-ldap-admin-server         registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-server   "/bin/sh -c './wait …"   go-ldap-admin-server   18 minutes ago      Up 15 minutes       0.0.0.0:8888->8888/tcp, :::8888->8888/tcp
go-ldap-admin-ui             registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-ui       "/bin/sh -c 'nginx -…"   go-ldap-admin-ui       18 minutes ago      Up 18 minutes       0.0.0.0:8090->80/tcp, :::8090->80/tcp
```

#### 您使用的场景？ | Your usage scenarios?
想把钉钉组织架构同步到ldap后应用到群晖，实现免登

#### 您做了什么操作？ | What did you do?

- [x] 动态字段关系管理
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/bc0840a8-89f4-43f9-84c3-41678f80ec45)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/3263bc1d-b250-4299-9a32-98d9cf30e96b) 
- [x] 同步部门
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/5e3e0f29-bee8-4332-b754-30263583ee4b)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/49c92943-aaef-468e-be89-2596b0520d70)

- [x] #293
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/eddf6024-13e1-4ed4-89a5-db9d1f8eb2f8)
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/461606da-ab7e-4b8b-90ff-ad6b7aa8b964)

- [x] 修改`config/config.yml`把-7排除后，只会跑接口不会入库

```
dingtalk:
    dept-list:    # 配置要同步的部门列表，配置留空则同步所有部门，在开头加^表示不同步此部门
        - "^-7"
```
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/afc94495-fe1f-4d50-9696-289e9096915e)

#### 您遇到了什么问题？ | What are your problems?
```
SyncDingTalkUsers获取钉钉用户列表失败：Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag
```

https://github.com/zhaoyunxing92/dingtalk/blob/c1568b7fbac5c8d6bf9bd10594d52004694cc8f5/request/dept_detail_user_info.go#L26

#### 您期望的结果是怎样的？ | What is your expected outcome?

1. 能跑就行
2. 常用的动态字段关系管理有初始值，不想一个个字段进行复制粘贴。

**Comment by eryajf** [comment]
您好 @jiangslee👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @jiangslee. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
先看看钉钉后台那边，是否真的有-7这个ID，后来你把-7排除，然后重新跑的时候是不会同步吗？

第二个问题怎么说呢，这个可以考虑，随后我看看刷一些默认数据。只不过有时候有的朋友他的数据不一定适用，所以一开始没有填充默认数据。

**Comment by jiangslee** [comment]
> 先看看钉钉后台那边，是否真的有-7这个ID，后来你把-7排除，然后重新跑的时候是不会同步吗？
> 
> 第二个问题怎么说呢，这个可以考虑，随后我看看刷一些默认数据。只不过有时候有的朋友他的数据不一定适用，所以一开始没有填充默认数据。

![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/3c7a5890-bb83-4e09-a545-880ccc77efc6)

https://open.dingtalk.com/document/isvapp/common-errors

![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/9e60d542-bddb-43e6-8d95-fc7dd386948c)

这个是个家校通讯录的特殊ID，我排除`-7`后，点击`获取钉钉用户`，`docker compose logs -f `查看到只会一直刷`获取用户详情`的接口，但是数据库`没有一个用户入库`。

![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/94ecfca9-5b5b-484d-9a2b-67b7ab273b4e)

**Comment by eryajf** [comment]
> 查看到只会一直刷`获取用户详情`的接口，但是数据库`没有一个用户入库`。

按说刷这个日志就是在同步用户了，你这个接口最后的结果是什么呢，正常的200吗，还是有异常报错。也可以到数据库看看user表有没有对应数据

**Comment by jiangslee** [comment]
1. 最后的结果是返回200
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/5f816d8c-e58b-47ff-8632-bede9388201d)

2. 数据库user表没有数据
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/fb6f60bd-db91-41e5-bf21-0078ebd81cf3)

3. phpLdapAdmin的people没有数据
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/b2ba4239-06b7-40e5-8b5b-ff14a73ae397)

**Comment by eryajf** [comment]
分组的数据都正常落库了吗。从目前提供的信息来看，一切都没问题，看不出来是什么原因

**Comment by jiangslee** [comment]
> 分组的数据都正常落库了吗。从目前提供的信息来看，一切都没问题，看不出来是什么原因

我大概定位到原因了，下面这个配置只会按`已手动输入的部门ID列表`进行同步，我只输入了`- "^-7"`，没有其它部门ID所以不入库。
```
dingtalk:
    dept-list:    # 配置要同步的部门列表，配置留空则同步所有部门，在开头加^表示不同步此部门
        - "^-7"
```

查看代码逻辑：

https://github.com/eryajf/go-ldap-admin/blob/d00d6df8a114e0d4378dffeadf2c8f602b9dd13d/public/client/dingtalk/dingtalk.go#L16C5-L39

我临时改了点代码测试能入库了：
![image](https://github.com/eryajf/go-ldap-admin/assets/27892476/542921e0-0e05-458f-ba6f-a2fdeece9da9)

然后遇到新问题，再看看
```
{
    "code": 506,
    "data": null,
    "msg": "SyncDingTalkUsers写入用户失败：添加用户: ***, 失败: AddUser向LDAP创建用户失败：LDAP Result Code 21 \"Invalid Attribute Syntax\": mail: value #0 invalid per syntax"
}
```

改进思路：

- [ ] 优化排除项功能，区分`同步所有部门列表+排除项`，`手动指定同步部门id`的配置

**Comment by eryajf** [comment]
关于排除这个逻辑，我周末再测试验证一下，可能是有问题的。

你下边的这个错误，是说邮箱的字段语法有问题，这个建议你可以先把数据拿到看看长什么样
