### ISSUE TITLE
无法在现有用户和组中添加samba 相关 objectclass

### ISSUE THREAD

**Issue by cacaocal** [eryajf/go-ldap-admin#292]
#### 您使用的场景？ | 1. Your usage scenarios?
使用nas存储 接入ldap user和group 怎么增加创建samba 相关的objectclass

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
希望可以用户和组添加时候可以关联相关opjectclass

**Comment by eryajf** [comment]
您好 @cacaocal👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @cacaocal. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
目前的设计来说，的确是不支持的，当前的设计可见： http://ldapdoc.eryajf.net/pages/5683c6/

至于其他objectclass的支持，限于我个人的学识及精力，应该没法新增，只能看后边如果有人有心思提交PR，我可以做合并。

**Comment by cacaocal** [comment]
你好 我看到一篇文章 https://cloud.tencent.com/developer/article/2303220 ，如果我们需要根据用户组来过滤用户的话，Posixgroup用户组属性，是无法满足需要的。比如，confluence 、jira与openldap集成时，以用户组过淲用户时，Posixgroup用户组属性是无法满足的。需要用GroupOfUniqueNames用户组属性。

**Comment by eryajf** [comment]
当前项目，新增分组，选择cn的时候，是包含 GroupOfUniqueNames 属性的，你可以部署一个demo体验一下看看
