### ISSUE TITLE
🚀 希望添加postgresql 数据库的支持

### ISSUE THREAD

**Issue by StarGods** [eryajf/go-ldap-admin#294]
#### 您使用的场景？ | 1. Your usage scenarios?

 使用postgresql 数据库 部署 go-ldap-admin

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?

添加对postgresql 数据的支持

**Comment by eryajf** [comment]
您好 @StarGods👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @StarGods. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
mysql和sqlite的两种方式已经够用了吧。

pg我还不是很熟悉，所以暂时可能不会增加。
