### ISSUE TITLE
管理员是否可以通过配置管理指定dn下的用户？

### ISSUE THREAD

**Issue by wanghonglin-for** [eryajf/go-ldap-admin#295]
希望管理员可以通过配置的方式管理指定dn下的用户，以此来提高管理员权限使用的灵活性

**Comment by eryajf** [comment]
您好 @wanghonglin-for👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wanghonglin-for. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
