### ISSUE TITLE
可以提供注册功能不，然用户自己注册，管理员批准

### ISSUE THREAD

**Issue by hahau6** [eryajf/go-ldap-admin#296]
可以提供注册功能不，然用户自己注册，管理员批准

**Comment by eryajf** [comment]
您好 @hahau6👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @hahau6. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by hahau6** [comment]
自己实验室使用，新生入学自己注册，后台批准就行了。

**Comment by eryajf** [comment]
这个功能可以有，晚些时候我来看一看

**Comment by jasonfanj** [comment]
+1
