### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by zhangyh222** [eryajf/go-ldap-admin#298]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
v0.5.15-linux-amd64
### 预期行为 | Expected behavior
正常同步钉钉部门和用户
### 实际行为 | Actual behavior
点击同步钉钉部门按钮：获取钉钉部门列表失败：code:50004,msg:请求的部门id不在授权范围内
通讯录管理权限，HRM 个人信息权限已经授权给要同步的部门
字段关系填写如下：
![S}68XMH4E3WKC38X(T1`7D2](https://github.com/eryajf/go-ldap-admin/assets/63626458/40c18b75-6342-43dd-b999-8aa150bb1a54)
![image](https://github.com/eryajf/go-ldap-admin/assets/63626458/0cbf857b-e52f-41e1-aea2-cbd30bc077df)
钉钉配置如下：
![image](https://github.com/eryajf/go-ldap-admin/assets/63626458/fc4761c5-3f41-4808-905d-ec3bd65db5b0)

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @zhangyh222👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @zhangyh222. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
请严格按照文档配置，http://ldapdoc.eryajf.net/pages/94f43a/
