### ISSUE TITLE
🙋 问题交流 | Active Direcotry可以使用吗？

### ISSUE THREAD

**Issue by Borg99** [eryajf/go-ldap-admin#299]
您好，看了一下作者写的开源作品感觉挺好挺实用的，我这边目前环境是使用Active Direcotry(Windows)进行管理，据我了解Active Direcotry也是基于LDAP协议，go-ldap-admin有办法接入AD域控使用吗？

**Comment by eryajf** [comment]
您好 @Borg99👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Borg99. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
我没有这个环境，也没有ad的使用经验，所以无法做测试及功能验证。貌似之前已经有人对接过，好像是能正常使用的

**Comment by jackadam1981** [comment]
我可以提供活动目录的环境，也有AD的使用经验，可以协助你做测试。
可以说LDAP是在linux下做的用户统一鉴权，活动目录则是windows的用户统一鉴权，部署的时候，是轻量ldap协议。
LDAP为各种系统做鉴权，活动目录一般也能接入，但是活动目录更强大的是对加入活动目录的Windows终端进行管控，通过组策略管理终端计算机的windows设置。
