### ISSUE TITLE
docker-compose部署完成 admin登陆开发者模式查看测试显示用户不存在

### ISSUE THREAD

**Issue by guopeizhao** [eryajf/go-ldap-admin#302]
![curl_2024-01-19_18-17-59](https://github.com/eryajf/go-ldap-admin/assets/88373712/5f936c10-1210-4f2d-abc8-5c8ad0fc5071)
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | 
![openldap_2024-01-19_18-15-02](https://github.com/eryajf/go-ldap-admin/assets/88373712/b12325a6-16ad-4b75-bdb7-655aa0745979)
![openldapimages_2024-01-19_18-16-06](https://github.com/eryajf/go-ldap-admin/assets/88373712/5e208b4c-79c6-46b1-ac0c-701123f8a287)
Please answer these questions before submitting them. Thank you.

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @guopeizhao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @guopeizhao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
可到mysql容器里看看user表是否有数据，按说拉起之后，会自动初始化数据的

**Comment by guopeizhao** [comment]
好像没有内容



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eryajf/go-ldap-admin] docker-compose部署完成 admin登陆开发者模式查看测试显示用户不存在 (Issue #302)




 
可到mysql容器里看看user表是否有数据，按说拉起之后，会自动初始化数据的

**Comment by guopeizhao** [comment]
openldap有报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月19日(周五) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eryajf/go-ldap-admin] docker-compose部署完成 admin登陆开发者模式查看测试显示用户不存在 (Issue #302)




 
可到mysql容器里看看user表是否有数据，按说拉起之后，会自动初始化数据的

**Comment by guopeizhao** [comment]
你好
&nbsp; &nbsp;docker-compose.yaml文件详细内容见文件，我到mysql的go_ldap_admin库中users表中添加admin用户登录还是报错401，显示密码错误密码就是123456。还是无法登录，我telnet测试了下都是通的排除了网络问题，重新安装多会都是一样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eryajf/go-ldap-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月19日(星期五) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eryajf/go-ldap-admin] docker-compose部署完成 admin登陆开发者模式查看测试显示用户不存在 (Issue #302)





 
可到mysql容器里看看user表是否有数据，按说拉起之后，会自动初始化数据的

**Comment by guopeizhao** [comment]
![go_ldap_admin_server_2024-01-19_23-41-27](https://github.com/eryajf/go-ldap-admin/assets/88373712/1b38bbda-0762-4782-bd87-7c471324fa1d)
go_ldap_admin_server 日志中初始化完成后报错用户不存在了，不知道为什么数据库初始化成功后，go_ldap_admin_server库的users表为空白，添加用户admin后仍然无法登录 认证失败

**Comment by eryajf** [comment]
启动之后会有一个数据初始化的过程，看你这个日志没有打印这个内容。

难道是在config.yaml里边，把 init-data: true 这个改成false了吗？

**Comment by guopeizhao** [comment]
已成功登录，不知什么原因没有自动导入sql语句，手动导入 go_ldap_admin.sql 到 go_ldap_admin库中解决问题

**Comment by eryajf** [comment]
那个参数使用true，然后重新安装整个流程，就会自动初始化用户等相关数据。

**Comment by guopeizhao** [comment]
改成ture后，ldap-admin-server 没回重启都会初始化数据吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [eryajf/go-ldap-admin] docker-compose部署完成 admin登陆开发者模式查看测试显示用户不存在 (Issue #302)




 
那个参数使用true，然后重新安装整个流程，就会自动初始化用户等相关数据。

**Comment by eryajf** [comment]
不会，如果数据已存在，会跳过，所以理论上一直为true也没事儿

**Comment by guopeizhao** [comment]
我配置改成true重新安装一遍后，还是需要手动导入go-ldap-admin.sql 文件，没有自动导入
