### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by Mrliuch** [eryajf/go-ldap-admin#304]
#### 您使用的版本？ | Your usage version?
![image](https://github.com/eryajf/go-ldap-admin/assets/38660378/b3159112-fe0a-47da-894f-fcfdff726615)

#### 您使用的场景？ | Your usage scenarios?
<img width="1249" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/38660378/605864bd-0b04-4802-9f6e-78e9031e6aa9">

#### 您做了什么操作？ | What did you do?
原LDAP无数据，所有LDAP内的组织架构及用户都在go-ldap-admin中创建的。创建分组及对应用户完毕后，点击同步原LDAP用户信息，将分组信息同步至了用户列表，同时报错如图下节

#### 您遇到了什么问题？ | What are your problems?
<img width="1249" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/38660378/605864bd-0b04-4802-9f6e-78e9031e6aa9">
#### 您期望的结果是怎样的？ | What is your expected outcome?
点击同步原LDAP用户信息仅同步用户，分组信息不同步，且不报错

**Comment by eryajf** [comment]
您好 @Mrliuch👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Mrliuch. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ixiaoyi93** [comment]
先同步分组，再同步用户。

**Comment by Mrliuch** [comment]
> 先同步分组，再同步用户。

操作过，分组信息仍会同步至用户列表内
<img width="1175" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/38660378/d84e6d0d-723c-49f6-945d-a95221cdfbaa">
<img width="1110" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/38660378/0510c1b3-4eaf-4188-bd98-adef21b748dd">

**Comment by ixiaoyi93** [comment]
额，手机号字段的问题嘛，你看看是不是为空或者重复了。

**Comment by Mrliuch** [comment]
> 额，手机号字段的问题嘛，你看看是不是为空或者重复了。

分组设置不了手机号呢，现在的问题是分组的信息同步到了用户列表中，导致用户那里面同步信息报错

**Comment by ixiaoyi93** [comment]
> > 额，手机号字段的问题嘛，你看看是不是为空或者重复了。
> 
> 分组设置不了手机号呢，现在的问题是分组的信息同步到了用户列表中，导致用户那里面同步信息报错

你手动给他加上，在试试同步呢。

**Comment by eryajf** [comment]
一般来说，分组不会同步到用户表里，如果同步了，那只能说明一个情况，这个分组里有了用户的一些属性。看你上边的截图，感觉是之前在使用的过程中，没有针对用户和分组进行很好的隔离设计，所以导致会有分组同步到用户。

这里建议阅读一下文档对项目里设计思路的介绍：http://ldapdoc.eryajf.net/pages/5683c6/

另外如果无法直接将原来数据平移的话，可能得考虑按照项目设计的思路，重建用户以及分组的数据信息。

**Comment by Mrliuch** [comment]
> 一般来说，分组不会同步到用户表里，如果同步了，那只能说明一个情况，这个分组里有了用户的一些属性。看你上边的截图，感觉是之前在使用的过程中，没有针对用户和分组进行很好的隔离设计，所以导致会有分组同步到用户。
> 
> 这里建议阅读一下文档对项目里设计思路的介绍：http://ldapdoc.eryajf.net/pages/5683c6/
> 
> 另外如果无法直接将原来数据平移的话，可能得考虑按照项目设计的思路，重建用户以及分组的数据信息。

有一个前提，我只是将空的LDAP对接至了go-ldap-admin，LDAP内没有任何数据，除了LDAP的admin认证账号，所有的分组、用户都是通过go-ldap-admin创建的，创建后再点击同步LDAP用户按钮就会将之前创建的分组同步至用户列表。而并非将已有的LDAP数据同步至go-ldap-admin

**Comment by Mrliuch** [comment]
> 一般来说，分组不会同步到用户表里，如果同步了，那只能说明一个情况，这个分组里有了用户的一些属性。看你上边的截图，感觉是之前在使用的过程中，没有针对用户和分组进行很好的隔离设计，所以导致会有分组同步到用户。
> 
> 这里建议阅读一下文档对项目里设计思路的介绍：http://ldapdoc.eryajf.net/pages/5683c6/
> 
> 另外如果无法直接将原来数据平移的话，可能得考虑按照项目设计的思路，重建用户以及分组的数据信息。

感谢提醒，应该是没有按照文档提前初始化ou=people，但仍希望可以增加灵活性，可创建，同步其他顶级或次级ou至go-ldap-admin

**Comment by eryajf** [comment]
@Mrliuch 这块儿灵活性目前还没想好怎么设计，如果全量支持，工作量会很大。所以暂时只能按照里边固定的思路来用
