### ISSUE TITLE
🐛 登录报错无权限

### ISSUE THREAD

**Issue by Zzm0809** [eryajf/go-ldap-admin#305]
#### 您使用的版本？ | Your usage version?
docker-compose 中的版本

#### 您使用的场景？ | Your usage scenarios?
测试 

#### 您做了什么操作？ | What did you do?
直接 docker-compose 启动 点击登录后提示无权限 检查容器日志如下
```log
[GIN] 2024/01/30 - 15:15:55 | 200 |    2.851839ms |    222.71.90.53 | POST     "/api/base/login"
[GIN] 2024/01/30 - 15:15:55 | 200 |    1.429789ms |    222.71.90.53 | GET      "/api/user/info"

2024/01/30 15:15:55 /app/service/isql/api_isql.go:109 record not found
[0.493ms] [rows:0] SELECT * FROM `apis` WHERE `method` = 'GET' AND `path` = '/menu/access/tree' AND `apis`.`deleted_at` IS NULL ORDER BY `apis`.`id` LIMIT 1
[GIN] 2024/01/30 - 15:15:55 | 401 |    1.444268ms |    222.71.90.53 | GET      "/api/menu/access/tree?id=1"

```

检查 数据库中的 apis 表中并无 `method` = 'GET' AND `path` = '/menu/access/tree' 的数据
![image](https://github.com/eryajf/go-ldap-admin/assets/58576849/95957fad-5f56-40f0-a6c1-c64f0809fb67)

**Comment by eryajf** [comment]
您好 @Zzm0809👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Zzm0809. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这条日志输出是正常的，可忽略

请再提供详细点的信息，以及看看user表是否有数据

**Comment by Zzm0809** [comment]
> 这条日志输出是正常的，可忽略
> 
> 请再提供详细点的信息，以及看看user表是否有数据

user 表是有的 
![image](https://github.com/eryajf/go-ldap-admin/assets/58576849/b458a10d-6925-4184-aad7-b132012b1d44)

**Comment by eryajf** [comment]
登陆的时候报无权限吗，还是说密码错误呢

部署过程中，是不是直接拉起的，有无其他调整

**Comment by Zzm0809** [comment]
> 登陆的时候报无权限吗，还是说密码错误呢
> 
> 部署过程中，是不是直接拉起的，有无其他调整

1. 登录的时候报错无权限 如下图: 
![image](https://github.com/eryajf/go-ldap-admin/assets/58576849/9e3fe4c0-b7e5-4856-8638-3b299aaa6dba)

2. 密码使用的是默认密码 官网给的是 账号/密码为: admin/123456
3. 部署过程中因为本地已经起了一个容器名重复的 mysql , 所以改了一下 docker-compose 的 mysql 的名称 ,但是所有其他依赖的也同步改了, 否则不可能连接到这个 mysql 的

**Comment by eryajf** [comment]
我刚刚又重头走了一遍这个流程，docker-compose 拉起之后，直接就能正常登陆访问。

你的操作上下文我这边不是很清晰，建议你可以找个干净环境，一把拉起试试。

**Comment by Zzm0809** [comment]
> 我刚刚又重头走了一遍这个流程，docker-compose 拉起之后，直接就能正常登陆访问。
> 
> 你的操作上下文我这边不是很清晰，建议你可以找个干净环境，一把拉起试试。

好的 感谢, 我再试试 有问题再反馈
