### ISSUE TITLE
动态字段关系管理的配置文件

### ISSUE THREAD

**Issue by h55aa** [eryajf/go-ldap-admin#306]
#### 您使用的场景？ | 1. Your usage scenarios?
docker compose
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
可将动态字段关系管理写入配置文件，如config.yml

动态字段关系管理的配置能否放在某个配置文件中，方便docker挪到新位置或者出问题的时候重新一次性boot起来，不用后期再配置。
<img width="1225" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/3960822/d9056bf2-e87c-4211-8bee-238ffaf6aefa">

**Comment by 665465** [comment]
或者内置一个大概能用的，不符合需求的再修改就可以

**Comment by eryajf** [comment]
我今晚把这块儿能力补充一下
