### ISSUE TITLE
如何同步多个企业钉钉组织到ldap

### ISSUE THREAD

**Issue by ChinaNanSen** [eryajf/go-ldap-admin#308]
#### 您使用的场景？ | 1. Your usage scenarios?
我们有多个子公司，想把这些子公司都同步到go-ldap里面，用的都是钉钉，我自己在配置里面加了多个钉钉AKSK，只会同步一个。

**Comment by eryajf** [comment]
您好 @ChinaNanSen👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @ChinaNanSen. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
的确一开始设计的时候，对接IM没有考虑多个，所以即便配置文件里写了，也是没用的。

如果想要对接多个，需要一些代码逻辑的调整改造。

**Comment by ChinaNanSen** [comment]
我开启多个go-ldap-admin 和ui , 然后都指向 同一个mysql和ldap, 修改下config和nginx的配置 还能用

**Comment by eryajf** [comment]
> 我开启多个go-ldap-admin 和ui , 然后都指向 同一个mysql和ldap, 修改下config和nginx的配置 还能用

理论上可行，只要没有数据冲突之类的，应该都可以。有些字段要求值唯一，注意一下就好了

**Comment by ChinaNanSen** [comment]
的确会有数据冲突，我看看怎么规避下
