### ISSUE TITLE
🐛操作用户（分组）只有有失败操作、需要mysql事物回滚；同步企业好像只同步了根部门，其它部门没用同步。

### ISSUE THREAD

**Issue by xiongxcodes** [eryajf/go-ldap-admin#309]
#### 您使用的版本？ | Your usage version?
main 分支
#### 您使用的场景？ | Your usage scenarios?
新增用户
#### 您做了什么操作？ | What did you do?
新增用户、选择了默认group
#### 您遇到了什么问题？ | What are your problems?
操作ldap失败后，用户依然新增成功
#### 您期望的结果是怎样的？ | What is your expected outcome?
操作用户只有有失败操作、需要mysql事物回滚

**Comment by eryajf** [comment]
您好 @xiongxcodes👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @xiongxcodes. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
目前ldap还无法支持事务。同步部门应该可以正常同步，看下你的配置是不是没有配好

**Comment by WinJayX** [comment]
配置文件就是config.yaml这个么？感觉修改的都改过了，但是同步企业微信组织结构还是同步了根组织信息，二级及三级的组织信息没有同步过来🤣
