### ISSUE TITLE
后面的版本希望可以实现只同步钉钉架构里面的某些部门的员工

### ISSUE THREAD

**Issue by sev7en789** [eryajf/go-ldap-admin#31]
后面的版本希望可以实现只同步钉钉架构里面的某些部门的员工

**Comment by eryajf** [comment]
您好 @sev7en789👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @sev7en789. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by ixiaoyi93** [comment]
这个功能有计划吗，大佬

**Comment by eryajf** [comment]
> 这个功能有计划吗，大佬

你的这种使用场景大概是怎样的呢，按说全量同步，然后用起来也没啥影响吧

**Comment by helopng** [comment]
> 

比如我司有很多部门,业务部,生产部,销售部.但我LDAP打通的内部系统只是给信息部使用的,这时候我希望只同步信息部一个部门的. 目前给领导说的是全量同步下来,把其他部门删掉,后面新入职的就手动建了...

**Comment by huxiangquan** [comment]
> > 
> 
> 比如我司有很多部门,业务部,生产部,销售部.但我LDAP打通的内部系统只是给信息部使用的,这时候我希望只同步信息部一个部门的. 目前给领导说的是全量同步下来,把其他部门删掉,后面新入职的就手动建了...

这个已经合并了，目前镜像还没构建出来。可以拉代码自己打包测试一下。我这边已经在用了。
