### ISSUE TITLE
企业微信同步问题

### ISSUE THREAD

**Issue by lvhp520** [eryajf/go-ldap-admin#311]
docker-compose拉起的环境在同步企业微信后，提示成功但数据并没有同步。请问是什么原因？谢谢！
![截屏2024-03-04 上午10 35 24](https://github.com/eryajf/go-ldap-admin/assets/162075775/882a16f6-ec18-4419-800f-ce07168015b0)
![截屏2024-03-04 上午10 38 29](https://github.com/eryajf/go-ldap-admin/assets/162075775/c25f869d-006f-456b-ba7e-0c0f1db81b1e)

**Comment by eryajf** [comment]
您好 @lvhp520👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lvhp520. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by wozaitianwai** [comment]
是不是企微的接口不能拉取到组织信息了，我正好也刚刚开始研究这个项目，但是根据官方文档来看，api接口新增的ip拉去不到具体的信息了，要用户取单独授权

**Comment by eryajf** [comment]
> 是不是企微的接口不能拉取到组织信息了，我正好也刚刚开始研究这个项目，但是根据官方文档来看，api接口新增的ip拉去不到具体的信息了，要用户取单独授权

是的，目前官方对接口做了一些变化，原来的接口拿不到用户的手机号等信息

**Comment by wozaitianwai** [comment]
- [ ] 异步导出的接口，倒是能有name position uid，然后和跟腾讯企业邮箱企业通讯录组合下倒是可以组合出来，但是碰到同名的这个匹配就有点子麻烦了，刚巧碰到这种特殊情况。但是好像合并去了企业微信之后，之前的邮箱的screatkey貌似就没了……，感觉只有做单点登录了，

**Comment by WinJayX** [comment]
现在企业微信通过自建应用（新建的）同步用户数据，拿到的数据太少了吧，只有"userid": "16178", "name": "孙长硕", "position": "会计" 可以使用，到系统的字段关系管理处都不太好配置了。。。
导致同步完用户数据，可用登陆的字段只有userid了。。。邮箱都拿不到。。。
