### ISSUE TITLE
用户状态被禁用的状态下点击删除，无法删除该用户

### ISSUE THREAD

**Issue by Sunshine-JamesHu** [eryajf/go-ldap-admin#312]
#### 您期望的结果是怎样的？ |  可以删除

![image](https://github.com/eryajf/go-ldap-admin/assets/27839097/596ea11a-8c24-4a90-9a88-f5081fe17dbd)

**Comment by eryajf** [comment]
您好 @Sunshine-JamesHu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Sunshine-JamesHu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
