### ISSUE TITLE
钉钉员工如果有相同拼音名字 或者同名 换成拼音 弄成uid 是不是会有特殊处理呢 

### ISSUE THREAD

**Issue by backlash-go** [eryajf/go-ldap-admin#313]
钉钉员工如果有相同拼音名字 或者同名 换成拼音 弄成uid 是不是会有特殊处理呢

**Comment by eryajf** [comment]
您好 @backlash-go👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @backlash-go. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by backlash-go** [comment]
name映射一个其他字段 指的是 换成邮箱是吧  因为邮箱是唯一 
![image](https://github.com/eryajf/go-ldap-admin/assets/43260088/d230ba35-eef1-41c9-af39-6486d32f2d18)

**Comment by backlash-go** [comment]
因为这个出现多音情况下，这边数据库 表username 又是唯一索引，会有异常报错的

**Comment by eryajf** [comment]
正解，在关系管理里边，映射正确的邮箱字段是一个不错的解决方案

**Comment by backlash-go** [comment]
> 正解，在关系管理里边，映射正确的邮箱字段是一个不错的解决方案

是的，不过我还是想用手机号，因为手机号 更通用点
