### ISSUE TITLE
🐛 企业微信机构同步只同步了最上层机构 | [Bug] Some problem...

### ISSUE THREAD

**Issue by Winterloveyou** [eryajf/go-ldap-admin#314]
#### 您使用的版本？ | Your usage version?
0.5.16
#### 您使用的场景？ | Your usage scenarios?
数据同步
#### 您做了什么操作？ | What did you do?
企业微信分组数据同步
#### 您遇到了什么问题？ | What are your problems?
企业微信数据分组同步成功，但是同步了1个最上层的机构，下面的机构未同步
#### 您期望的结果是怎样的？ | What is your expected outcome?
同步全部机构

**Comment by eryajf** [comment]
您好 @Winterloveyou👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Winterloveyou. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by Winterloveyou** [comment]
还有就是，我发现用户缺少PosixAccout属性，部分系统识别不出来用户 希望能在新增用户的时候添加上这个属性
