### ISSUE TITLE
🙋 问题交流|K8S启动服务后登录提示没有权限

### ISSUE THREAD

**Issue by enica** [eryajf/go-ldap-admin#316]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-server
### 预期行为 | Expected behavior
正常登录
### 实际行为 | Actual behavior
admin登录提示无权限
### 原因分析（如果可以） | Cause analysis (if possible)
![go-1](https://github.com/eryajf/go-ldap-admin/assets/6247206/33905881-5469-473b-a902-574753275ff1)
后台日志
![go-2](https://github.com/eryajf/go-ldap-admin/assets/6247206/ea6e233d-19da-4996-af65-82580d75b698)

### 问题解决步骤 | Steps to reproduce the problem
执行以下sql语句：
INSERT INTO go_ldap_admin.apis (created_at,updated_at,deleted_at,`method`,`path`,category,remark,creator) VALUES
	 ('2023-02-24 19:51:37.398000000','2023-02-24 19:51:37.398000000',NULL,'GET','/menu/access/tree','api','获取接口列表','系统');
INSERT INTO go_ldap_admin.casbin_rule (ptype,v0,v1,v2,v3,v4,v5) VALUES
	 ('p','user','/menu/access/tree','GET','','','');
INSERT INTO go_ldap_admin.casbin_rule (ptype,v0,v1,v2,v3,v4,v5) VALUES
	 ('p','admin','/menu/access/tree','GET','','','');
重启服务

**Comment by eryajf** [comment]
您好 @enica👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @enica. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by enica** [comment]
已解决
