### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by Roger0822** [eryajf/go-ldap-admin#318]
### 你使用了哪个版本？ | Which version did you use?

v0.5.16 2024-02-21

### 预期行为 | Expected behavior
同步企业微信用户

### 实际行为 | Actual behavior
不成功

### 原因分析（如果可以） | Cause analysis (if possible)
miss token

现在企业微信同步是不是不行了？请问
![Uploading 1710566037864.jpg…]()

**Comment by eryajf** [comment]
您好 @Roger0822👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Roger0822. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
