### ISSUE TITLE
🐛 【忘记密码】发送验证码失败

### ISSUE THREAD

**Issue by KolorYan** [eryajf/go-ldap-admin#320]
#### 您使用的版本？ | Your usage version?
v0.5.15
#### 您做了什么操作？ | What did you do?
忘记密码
#### 您遇到了什么问题？ | What are your problems?
输入邮箱后，点击发送验证码，提示“该用户已离职或者未同步在ldap，无法重置密码，如有疑问，请联系管理员”
所有的账号都不行，非个例
#### 您期望的结果是怎样的？ | What is your expected outcome?
成功接收验证码并重置成功

**Comment by eryajf** [comment]
您好 @KolorYan👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @KolorYan. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
判断逻辑在这里：

https://github.com/eryajf/go-ldap-admin/blob/02638f213e8a530c27bfb1f05a8d092dec08fe35/logic/base_logic.go#L31

可以在库里查一下用户信息，看看这两个字段分别是什么，应该是其中一个状态不满足条件。

**Comment by KolorYan** [comment]
> 判断逻辑在这里：
> 
> https://github.com/eryajf/go-ldap-admin/blob/02638f213e8a530c27bfb1f05a8d092dec08fe35/logic/base_logic.go#L31
> 
> 可以在库里查一下用户信息，看看这两个字段分别是什么，应该是其中一个状态不满足条件。

数据库中status和sync_state的值都是true，看上去不会进这个判断才是

**Comment by KolorYan** [comment]
> 判断逻辑在这里：
> 
> https://github.com/eryajf/go-ldap-admin/blob/02638f213e8a530c27bfb1f05a8d092dec08fe35/logic/base_logic.go#L31
> 
> 可以在库里查一下用户信息，看看这两个字段分别是什么，应该是其中一个状态不满足条件。

sync_state是2，但是为什么是2呢，用户是通过go-ldap-admin后台添加的，但是点击用户列表里的【同步】操作，会提示“SyncUser向LDAP同步用户失败：LDAP Result Code 68 "Entry Already Exists":”

**Comment by KolorYan** [comment]
同步操作提示失败可以理解，因为是后台添加的，本身已经在ldap中存在用户了，但是，是不是后台添加的用户已经同步至ldap了，sync_state应该改为1才对

**Comment by eryajf** [comment]
因工作繁忙，因此不少issue没有跟进。
这个问题我现在怀疑，有一种可能是你的数据结构和标准的不一样，所以导致判断逻辑上出了一些问题。

如果还有在用，还需要解决，可继续沟通
