### ISSUE TITLE
docker拉取容器失败

### ISSUE THREAD

**Issue by YUlucky7** [eryajf/go-ldap-admin#328]
[root@VM-8-5-centos go-ldap-admin]# docker compose up -d
[+] Running 4/4
 ✘ phpldapadmin Error                                                                                                                                                                                  0.6s 
 ✘ mysql Error                                                                                                                                                                                         0.6s 
 ✘ go-ldap-admin Error                                                                                                                                                                                 0.6s 
 ✘ openldap Error                                                                                                                                                                                      0.6s 
Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/eryajf/openldap:1.4.1 not found: manifest unknown: manifest unknown

**Comment by eryajf** [comment]
您好 @YUlucky7👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @YUlucky7. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
已修复，可重新拉取
