### ISSUE TITLE
旧版本系统无法搭建，希望可以修复

### ISSUE THREAD

**Issue by YUlucky7** [eryajf/go-ldap-admin#329]
旧版本docker环境搭建时遇到不能连接镜像仓库的问题，是仓库删除了吗

**Comment by eryajf** [comment]
您好 @YUlucky7👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @YUlucky7. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
重复 #328
