### ISSUE TITLE
旧版本docker容器搭建失败

### ISSUE THREAD

**Issue by YUlucky7** [eryajf/go-ldap-admin#330]
[root@VM-8-5-centos docker-compose]# ls
config  docker-compose.yaml
[root@VM-8-5-centos docker-compose]# docker compose up -d
[+] Running 5/5
 ✘ mysql Error                                                                                                                                                                                         0.6s 
 ✘ openldap Error                                                                                                                                                                                      0.6s 
 ✘ phpldapadmin Error                                                                                                                                                                                  0.6s 
 ✘ go-ldap-admin-server Error                                                                                                                                                                          0.6s 
 ✘ go-ldap-admin-ui Error                                                                                                                                                                              0.6s 
Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/ali_eryajf/go-ldap-admin-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by eryajf** [comment]
您好 @YUlucky7👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @YUlucky7. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个旧版本镜像迁移到eryajf了，你这边是有场景要部署旧版本吗。那么可在 dockerhub 的 eryajf 下找到所有历史版本的镜像。
