### ISSUE TITLE
同步钉钉用户失败

### ISSUE THREAD

**Issue by kaidi2024** [eryajf/go-ldap-admin#332]
#### 您使用的版本？ | Your usage version?
2023-02-22_14-16

#### 您做了什么操作？ | What did you do?
同步钉钉用户，钉钉部门已同步成功

#### 您遇到了什么问题？ | What are your problems?
在LDAP删除用户失败LDAP
![image](https://github.com/eryajf/go-ldap-admin/assets/159096850/75a9438a-d7bc-497c-9c17-d2227b34abd8)

#### 您期望的结果是怎样的？ | What is your expected outcome?
同步钉钉用户，包括新增和删除的

**Comment by eryajf** [comment]
您好 @kaidi2024👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @kaidi2024. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
新增会自动同步，删除的不会，应该是有离职的，会更新状态。
你这个删除是手动删除的吗

**Comment by kaidi2024** [comment]
是的，钉钉上手动删除了人员，这种情况怎么同步

**Comment by eryajf** [comment]
是两个问题，一般企业里边不会删除人员，而是置为离职状态。

**Comment by kaidi2024** [comment]
那这两个问题怎么解决呢

**Comment by kaidi2024** [comment]
1. 报错已通过升级版本解决
2. 钉钉里删除人员，也可以同步的
