### ISSUE TITLE
🐛 生产环境解压部署浏览器打开提示 404   /github/workspace/service/isql/api_isql.go:109 record not found

### ISSUE THREAD

**Issue by lileih** [eryajf/go-ldap-admin#333]
#### 您使用的版本？ | Your usage version?
v0.5.16

#### 您使用的场景？ | Your usage scenarios?
生产使用,解压部署方式

#### 您做了什么操作？ | What did you do?
可以起来,监听在 8888 端口,用 curl命令测试有 pong 响应

<img width="704" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/10669788/203f060d-ebbe-4a15-8d22-3bab7f00db87">

#### 您遇到了什么问题？ | What are your problems?
浏览器打开出现404 page not found
<img width="448" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/10669788/93636fae-d919-4148-817b-05f02ba76a66">

<img width="1283" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/10669788/c38fc16e-f933-4370-a27c-63d9a6624aef">

**Comment by eryajf** [comment]
您好 @lileih👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lileih. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
应该是缺少初始化的数据，建议根据docker-compose安装文档一键拉起，快速体验，不踩坑。
