### ISSUE TITLE
钉钉用户同步,如何自动映射自定义ldap属性

### ISSUE THREAD

**Issue by TopJohn** [eryajf/go-ldap-admin#335]
#### 您使用的场景？ | 1. Your usage scenarios?
期望使用钉钉用户体系,接入群晖nas,但是nas提示缺少uid,和uidNumber

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
是否有办法自动添加属性

**Comment by eryajf** [comment]
您好 @TopJohn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @TopJohn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by Xiaoniba** [comment]
https://kb.synology.cn/zh-cn/DSM/help/DSM/AdminCenter/file_directory_service_join?version=7

选择自定义，按照这个添加
