### ISSUE TITLE
关于go ldap admin低权限用户如何登录

### ISSUE THREAD

**Issue by YUlucky7** [eryajf/go-ldap-admin#336]
这个项目好像是设置了低权限用户如user，guest，但是没有提示密码是什么

**Comment by eryajf** [comment]
您好 @YUlucky7👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @YUlucky7. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
