### ISSUE TITLE
go-ldap-admin-phpldapadmin 无法正常打开报错302

### ISSUE THREAD

**Issue by nedncs** [eryajf/go-ldap-admin#337]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
docker last

### 预期行为 | Expected behavior
访问phpldapadmin
### 实际行为 | Actual behavior
无法打开
### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @nedncs👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @nedncs. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
最新的compose文件已经不包含phpldapadmin，如有需要，可自行配置部署。
