### ISSUE TITLE
🚀 请考虑改进证书配置方式

### ISSUE THREAD

**Issue by fsdrw08** [eryajf/go-ldap-admin#338]
#### 您使用的场景？ | 1. Your usage scenarios?
可以用更优雅/常规/简单的方式自定义TLS证书

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
根据这里[如何自定义秘钥对儿](http://ldapdoc.eryajf.net/pages/119ea3/#%E5%90%8E%E7%AB%AF)的描述，如需自定义TLS证书，需要先把证书放到代码仓库中对应的目录，然后对此仓库代码进行重新编译，才能让此产品读取自定义的证书。  
我希望可以通过[config.yml](https://github.com/eryajf/go-ldap-admin/blob/main/config.yml)配置文件指定公私钥文件的路径(例如在yaml文件中加入tls配置项)，在服务启动的时候读取对应路径的公私钥文件，用来提供https服务

**Comment by eryajf** [comment]
您好 @fsdrw08👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @fsdrw08. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 用来提供https服务

这里的秘钥只是用于前后端交互式校验用户秘钥时加密传输所用，与ssl是两个东西。

如果需要https，可通过ng代理配置证书。
