### ISSUE TITLE
为什么http://localhost:8888登录后的页面是？？？

### ISSUE THREAD

**Issue by dai542** [eryajf/go-ldap-admin#340]
你好，我在虚拟机上部署了go-ldap-admin，相关服务正常启动，但是浏览器页面打开后很多？？？
<img width="1218" alt="12" src="https://github.com/eryajf/go-ldap-admin/assets/59718003/b6cb7152-5896-4735-8fb5-7abed1bfde6e">
<img width="806" alt="13" src="https://github.com/eryajf/go-ldap-admin/assets/59718003/97c9835f-fe04-4690-8339-022aa9d0ad99">

**Comment by eryajf** [comment]
您好 @dai542👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @dai542. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by dai542** [comment]
config.yml如附件，以txt命名上传。
[config.txt](https://github.com/eryajf/go-ldap-admin/files/15281500/config.txt)

**Comment by eryajf** [comment]
你是用的mysql还是sqlite，应该是环境的因素，导致的乱码，倒是第一次看到这个情况

**Comment by dai542** [comment]
mysql。系统是CentOS7.9，会不会是mysql版本太低了？
<img width="721" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/59718003/a09cf61f-dd1b-4f03-8936-1958af772ee2">

**Comment by eryajf** [comment]
5.5应该是有点低的，建议你可以用sqlite部署方式先部署体验，MySQL与项目中使用的对齐

**Comment by dai542** [comment]
应该不是mysql的版本问题，即使我已经升级了，问题依旧存在。我将使用sqlite尝试
<img width="801" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/59718003/8e04d544-eca6-4502-a4bc-a239fcab54fa">
