### ISSUE TITLE
🙋 问题交流。。。 | [Question] 咨询一下 在 分组外成员  添加时 无法使用

### ISSUE THREAD

**Issue by nangongchengfeng** [eryajf/go-ldap-admin#347]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

这一块是逻辑限制吗？分组外成员 

![image](https://github.com/eryajf/go-ldap-admin/assets/46562911/03058a60-f5eb-4139-98b9-8151e9c7b424)

**Comment by eryajf** [comment]
您好 @nangongchengfeng👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @nangongchengfeng. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by nangongchengfeng** [comment]
已经找到使用的方式
