### ISSUE TITLE
运行一段时间后同步组织架构出现问题

### ISSUE THREAD

**Issue by b1uecream** [eryajf/go-ldap-admin#349]
#### 您使用的版本？ | Your usage version?
v0.5.15 2023-11-12
#### 您使用的场景？ | Your usage scenarios?
同步钉钉组织架构
#### 您做了什么操作？ | What did you do?
运行了半年左右，手动创建过一个用户，没有其他操作。
钉钉由于人员变化，存在调岗、离职、入职等人员。
#### 您遇到了什么问题？ | What are your problems?
同步钉钉时报错，报错信息如下：
![image](https://github.com/eryajf/go-ldap-admin/assets/19721645/98a5dc73-4f8b-4bc9-be7c-f08bb74184b9)

#### 您期望的结果是怎样的？ | What is your expected outcome?
能够正确同步组织架构

**Comment by eryajf** [comment]
您好 @b1uecream👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @b1uecream. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个报错是因为同步用户信息的时候，会针对手机号进行唯一性校验，所以你去数据库里，查询下这个手机号，解决掉这个重复的问题，就能正常同步了
