### ISSUE TITLE
为什么更建议在生产环境使用原生方式进行部署？

### ISSUE THREAD

**Issue by MarsZhu** [eryajf/go-ldap-admin#351]
根据官方文档，似乎更建议使用原生方式进行部署，是因为在docker中运行存在问题吗？

**Comment by eryajf** [comment]
您好 @MarsZhu👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @MarsZhu. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这是原始陈旧的思想，根据你自己实际情况选择部署方式即可。
