### ISSUE TITLE
DsyncDingTalkDepts添加部门失败: 添加部门:******部, 失败: LDAP Result Code 68 "Entry Already Exists":

### ISSUE THREAD

**Issue by EnjoyH** [eryajf/go-ldap-admin#354]
一开始从钉钉同步过1次，后面因为调整了一下字段映射关系，全部删除了后，也把数据库groups清空了，再重新写入了config.yml文件配置到数据库，然后发现目前从钉钉同步报错，显示已存在，求解

**Comment by eryajf** [comment]
您好 @EnjoyH👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @EnjoyH. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
把挂载出来的data目录也删除，然后再同步就可以了。ldap的持久化数据在这个目录里。
