### ISSUE TITLE
🙋 请问系统里面的角色，对应openldap里面什么属性吗？

### ISSUE THREAD

**Issue by zbjdonald** [eryajf/go-ldap-admin#356]
🙋 请问系统里面的角色，对应openldap里面什么属性吗？

**Comment by eryajf** [comment]
您好 @zbjdonald👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @zbjdonald. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
两者没有关系，这个角色是web管理的角色
