### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by Accpet** [eryajf/go-ldap-admin#357]
最新的版本？
registry.cn-hangzhou.aliyuncs.com/eryajf/go-ldap-admin   latest    92adfab8b75e   About an hour ago   40.9MB
bitnami/openldap                                         2.6.7     2c108aad7084   6 weeks ago         159MB
registry.cn-hangzhou.aliyuncs.com/eryajf/openldap        1.4.1     5ed03ecfcb64   2 months ago        262MB
registry.cn-hangzhou.aliyuncs.com/eryajf/mysql           8.3       82563e0cbf18   3 months ago        632MB
mysql                                                    8.0.27    3218b38490ce   2 years ago         516MB
registry.cn-hangzhou.aliyuncs.com/eryajf/phpldapadmin    0.9.0     78148b61fdb5   4 years ago         302MB

启动时候  go-ldap-admin 错误

fbe3f73bbd64   registry.cn-hangzhou.aliyuncs.com/eryajf/go-ldap-admin        "/bin/sh -c './wait …"   8 minutes ago   Restarting (2) 2 seconds ago                                                          go-ldap-admin
018a83da6525   registry.cn-hangzhou.aliyuncs.com/eryajf/phpldapadmin:0.9.0   "/container/tool/run"    8 minutes ago   Up 8 minutes                   443/tcp, 0.0.0.0:8091->80/tcp, :::8091->80/tcp         go-ldap-admin-phpldapadmin
4521fc80a5ad   registry.cn-hangzhou.aliyuncs.com/eryajf/mysql:8.3            "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes                   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   go-ldap-admin-mysql
a6c15398c028   registry.cn-hangzhou.aliyuncs.com/eryajf/openldap:1.4.1       "/container/tool/run…"   8 minutes ago   Up 8 minutes                   0.0.0.0:389->389/tcp, :::389->389/tcp, 636/tcp         go-ldap-admin-openldap

docker logs -f fbe3f73bbd64
![WechatIMG1856](https://github.com/eryajf/go-ldap-admin/assets/3699607/ca90a6e0-c073-4cae-aa53-4cf6a002004b)

验证数据库账号密码正确

通过mysql -uroot -h物理机IP -p可以登陆

![Uploading WechatIMG1857.jpg…]()

**Comment by eryajf** [comment]
您好 @Accpet👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @Accpet. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
你这个应该不是通过docker-compose拉起的吧。

问题是连接MySQL的配置没对，参考这里：http://ldapdoc.eryajf.net/pages/f081dc/

可指定连接的MySQL地址。

**Comment by Accpet** [comment]
我是通过docker-compose拉起的
