### ISSUE TITLE
🙋 同步钉钉，其中邮箱默认同步了congif.yaml的邮件后缀，这个可以怎么设置不同步，

### ISSUE THREAD

**Issue by EnjoyH** [eryajf/go-ldap-admin#359]
## 原生部署方式，在config.yml配置
       # 是否允许更改分组DN
        group-name-modify: true
        # 是否允许更改用户DN
        user-name-modify: true
        # 用户密码加密方式 默认为 ssha 还可指定为 clear(表示不加密)
        user-password-encryption-type: "ssha"
        # 默认邮箱后缀
        #default-email-suffix: "email"
![image](https://github.com/eryajf/go-ldap-admin/assets/143678707/038d95bf-ccab-43da-b16d-9d59df16b4e2)
### 版本
        V0.5.17
### 预期行为 | Expected behavior
        同步钉钉主页呈现的邮箱
### 实际行为 | Actual behavior
       *****@email  其中*****同步了工号
### 原因分析（如果可以） | Cause analysis (if possible)
       
![image](https://github.com/eryajf/go-ldap-admin/assets/143678707/508a0931-a322-4df5-a625-00a982be08b6)

### 问题重现步骤 | Steps to reproduce the problem

**Comment by eryajf** [comment]
您好 @EnjoyH👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @EnjoyH. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by EnjoyH** [comment]
实际同步结果如图：
![image](https://github.com/eryajf/go-ldap-admin/assets/143678707/83ece3a2-c1df-4460-8896-ecb686836911)

**Comment by eryajf** [comment]
只有当 org_email为空的时候才会用这个后缀，所以你这个字段应该是空的，可以看看具体邮箱映射的具体是哪个字段，然后更改关系这里对应上就可以了。

通过这个工具测试：https://github.com/eryajf/glactl

**Comment by EnjoyH** [comment]
OK,Thanks
