### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by consam** [eryajf/go-ldap-admin#360]
static/static.go 的 “//go:embed all:dist” 少了个空格，应该是 "// go:embed all:dist"

**Comment by eryajf** [comment]
您好 @consam👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @consam. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.
