### ISSUE TITLE
🙋 问题交流。。。 | [Question] Some question...

### ISSUE THREAD

**Issue by xianhuadezhuren** [eryajf/go-ldap-admin#362]
## Question Report
ldap同步钉钉组织过来后，没有gid，这个是默认就会没有吗

**Comment by eryajf** [comment]
您好 @xianhuadezhuren👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @xianhuadezhuren. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
这个gid具体指的是哪个字段呢，分组映射可根据实际情况自行调整。

参考：https://ldapdoc.eryajf.net/pages/84953d/
