### ISSUE TITLE
🙋 问题交流。。。 | [Question] 同步人员信息错误

### ISSUE THREAD

**Issue by shistory** [eryajf/go-ldap-admin#371]
SyncDingTalkUsers获取钉钉用户列表失败：Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag
同步钉钉用户信息时报错，求解决方法
另外，有交流群

**Comment by eryajf** [comment]
您好 @shistory👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @shistory. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
要求是先同步分组，再同步用户，如果分组同步正常。

你这个错误，感觉和之前其他钉钉的情况都不一样。

**Comment by shistory** [comment]
同步分组了，而且分组正常获取到了

**Comment by eryajf** [comment]
先用这个工具测试是否能正常获取分组和用户：https://github.com/eryajf/glactl

**Comment by shistory** [comment]
2024/10/28 10:27:35 ERRO [获取用户列表失败 Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag]
一样的错误，囧

**Comment by shistory** [comment]
大佬，还有个问题，怎么情况已经同步的信息，或者是还原这套系统

**Comment by eryajf** [comment]
> 2024/10/28 10:27:35 ERRO [获取用户列表失败 Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag] 一样的错误，囧

看起来是你所在企业的钉钉有什么非标的情况。这个需要你自行深入排查一下了。

**Comment by eryajf** [comment]
> 大佬，还有个问题，怎么情况已经同步的信息，或者是还原这套系统

没太懂

**Comment by shistory** [comment]
就是我第一次用，把家校通讯同步进去了，想把这个部分人员及部门删除了，

**Comment by shistory** [comment]
家校通讯录里是学生的信息，这部分信息时没有用的

**Comment by eryajf** [comment]
> 就是我第一次用，把家校通讯同步进去了，想把这个部分人员及部门删除了，

可清空重新同步，重新同步时，配置文件指定要同步的部门就好了。

**Comment by shistory** [comment]
咋清空？没找大清空的地方

**Comment by eryajf** [comment]
看你是怎么部署的，如果是docker部署，并且数据库为sqlite，那么直接把data目录(包含所有数据)删除，重新启动，重新同步就可以了。

**Comment by shistory** [comment]
好的，谢谢，

**Comment by shistory** [comment]
2024/10/28 10:27:35 ERRO [获取用户列表失败 Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag]

**Comment by shistory** [comment]
2024/10/28 10:27:35 ERRO [获取用户列表失败 Key: 'DeptDetailUserInfo.DeptId' Error:Field validation for 'DeptId' failed on the 'min' tag]       这个BUG估计是因为我们是学校吧，如果付费解决的话多少钱

**Comment by eryajf** [comment]
参见：https://ldapdoc.eryajf.net/pages/7eab1c/

**Comment by shistory** [comment]
收到，抽个空让大佬给部署一下

**Comment by shistory** [comment]
应该是家校通讯录导致的BUG，这个受众太小了

**Comment by eryajf** [comment]
> 收到，抽个空让大佬给部署一下

通过里边的微信即可与我联系
