### ISSUE TITLE
🚀 增加对现有的LDAP用户 页面管理

### ISSUE THREAD

**Issue by wuxingwang1997** [eryajf/go-ldap-admin#43]
希望后续增加对历史用户的页面管理，可以同步到控制台管理

**Comment by eryajf** [comment]
您好 @wuxingwang1997👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wuxingwang1997. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
see #10

**Comment by eryajf** [comment]
@wuxingwang1997 该功能已支持，参考 #60
