### ISSUE TITLE
支持AD密码自助修改功能

### ISSUE THREAD

**Issue by dzhyw** [eryajf/go-ldap-admin#45]
当前企业都是使用AD域进行统一账户管理，密码策略为90天修改一次。希望能通过一个平台自助修改用户密码。
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
通过平台修改AD域账户密码，支持网页修改 或脱机更新同步（在家办公场景）

**Comment by eryajf** [comment]
您好 @dzhyw👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @dzhyw. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
@dzhyw 目前这个平台主要还是接入ldap的(也提供了网页上修改密码的能力)，对于AD这块儿还没有接触太多，以后可能会专门提供能力支持AD

**Comment by jackadam1981** [comment]
期待着适配AD，企业内网终端管理时，AD太好用了。
