### ISSUE TITLE
go-ldap-admin-server  服务启动报错了 启动不起来 前端无法登录

### ISSUE THREAD

**Issue by 370569218** [eryajf/go-ldap-admin#48]
go-ldap-admin-server  服务启动报错了 启动不起来 前端无法登录
[INFO  wait] Host [mysql:3306] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] Checking availability of host [ openldap:389]
[INFO  wait] Host [ openldap:389] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
[INFO  wait] --------------------------------------------------------
panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
	/go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb

**Comment by eryajf** [comment]
> panic: Unsupported CPU, maybe it's too old to run Sonic.
> 
> goroutine 1 [running]: github.com/bytedance/sonic/internal/native.init.0() /go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb

这是在Mac M1电脑通过docker-compose直接拉起报的错误吗？

**Comment by eryajf** [comment]
看起来应该是你的虚拟机或者主机的CPU架构不对劲 https://github.com/bytedance/sonic/issues/244，跟这个问题一样。

你是在Mac电脑上的虚拟机吗？

**Comment by eryajf** [comment]
请看 #55
