### ISSUE TITLE
docker-compose部署，go-ldap-admin-server一直提示正在restarting

### ISSUE THREAD

**Issue by calvin110** [eryajf/go-ldap-admin#55]
通过docker-compose部署，go-ldap-admin-server一直提示正在restarting，查看该容器的日志，提示：panic: Unsupported CPU, maybe it's too old to run Sonic，是物理CPU不支持吗？

**Comment by eryajf** [comment]
您好 @calvin110👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @calvin110. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
#48 有一个朋友遇到了跟你一样的问题，在这里一起交流吧

麻烦提供下你的拉起环境，比如什么电脑，什么CPU架构

**Comment by calvin110** [comment]
我是在ESXi 6.7.0上部署的CentOS 7.9 虚拟机：
ESXi的CPU：Intel(R) Xeon(R) CPU E5620 @ 2.40GHz。
Dcoker版本：Docker version 20.10.17, build 100c701
Compose版本：Docker Compose version v2.2.2

以下是容器运行状态信息：
[root@ldap docker-compose]# docker-compose ps
NAME                         COMMAND                  SERVICE                STATUS              PORTS
go-ldap-admin-mysql          "/entrypoint.sh --de…"   mysql                  running (healthy)   0.0.0.0:3307->3306/tcp, :::3307->3306/tcp
go-ldap-admin-openldap       "/container/tool/run…"   openldap               running             0.0.0.0:388->389/tcp, :::388->389/tcp
go-ldap-admin-phpldapadmin   "/container/tool/run"    phpldapadmin           running             0.0.0.0:8091->80/tcp, :::8091->80/tcp
go-ldap-admin-server         "/bin/sh -c './wait …"   go-ldap-admin-server   restarting
go-ldap-admin-ui             "/bin/sh -c 'nginx -…"   go-ldap-admin-ui       running             0.0.0.0:8090->80/tcp, :::8090->80/tcp

以下是go-ldap-admin-server 的日志信息：
go-ldap-admin-server  | goroutine 1 [running]:
go-ldap-admin-server  | github.com/bytedance/sonic/internal/native.init.0()
go-ldap-admin-server  |         /go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb
go-ldap-admin-server  | [INFO  wait] --------------------------------------------------------
go-ldap-admin-server  | [INFO  wait]  docker-compose-wait 2.9.0
go-ldap-admin-server  | [INFO  wait] ---------------------------
go-ldap-admin-server  | [DEBUG wait] Starting with configuration:
go-ldap-admin-server  | [DEBUG wait]  - Hosts to be waiting for: [mysql:3306, openldap:389]
go-ldap-admin-server  | [DEBUG wait]  - Paths to be waiting for: []
go-ldap-admin-server  | [DEBUG wait]  - Timeout before failure: 30 seconds
go-ldap-admin-server  | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds
go-ldap-admin-server  | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
go-ldap-admin-server  | [DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
go-ldap-admin-server  | [DEBUG wait]  - Sleeping time between retries: 1 seconds
go-ldap-admin-server  | [DEBUG wait] --------------------------------------------------------
go-ldap-admin-server  | [INFO  wait] Checking availability of host [mysql:3306]
go-ldap-admin-server  | [INFO  wait] Host [mysql:3306] is now available!
go-ldap-admin-server  | [INFO  wait] --------------------------------------------------------
go-ldap-admin-server  | [INFO  wait] Checking availability of host [ openldap:389]
go-ldap-admin-server  | [INFO  wait] Host [ openldap:389] is now available!
go-ldap-admin-server  | [INFO  wait] --------------------------------------------------------
go-ldap-admin-server  | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
go-ldap-admin-server  | [INFO  wait] --------------------------------------------------------
**go-ldap-admin-server  | panic: Unsupported CPU, maybe it's too old to run Sonic.**
go-ldap-admin-server  |
go-ldap-admin-server  | goroutine 1 [running]:
go-ldap-admin-server  | github.com/bytedance/sonic/internal/native.init.0()
go-ldap-admin-server  |         /go/pkg/mod/github.com/bytedance/sonic@v1.3.1/internal/native/dispatch_amd64.go:144 +0x1fb

**Comment by eryajf** [comment]
我看到sonic库有这样一个issue:  https://github.com/bytedance/sonic/issues/255#issuecomment-1173535430

又看到你的这个 Xeon 是 2010年的：https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+E5620+%40+2.40GHz

这个有点尴尬，我看看这里如何处理一下比较好吧。

**Comment by wokula99** [comment]
我的环境也和上面的差不多，ESXi 6.7.0上部署的CentOS 7.9 虚拟机
![image](https://user-images.githubusercontent.com/46983052/177234317-d3df9408-9e16-48a0-9f66-1433bfd72e40.png)
![image](https://user-images.githubusercontent.com/46983052/177234350-9ec4270c-16d0-4ef3-a696-3619bf1e61ba.png)
![image](https://user-images.githubusercontent.com/46983052/177234473-d5b79dd3-0c74-4d39-afaf-a54655cd06ab.png)

**Comment by eryajf** [comment]
@calvin110 @wokula99 我改掉了这个包，请二位把后端镜像在本地删除一下，然后重新拉起一下试试

**Comment by 370569218** [comment]
2022/07/05 13:11:40 /app/public/common/database.go:40
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused
2022-07-05 13:11:40	PANIC	common/database.go:49	github.com/eryajf/go-ldap-admin/public/common.InitMysql	初始化mysql数据库异常: dial tcp 127.0.0.1:3306: connect: connection refused
panic: 初始化mysql数据库异常: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000542000, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*SugaredLogger).log(0xc00048a5a8, 0x4, {0x1073729, 0xc000033270}, {0xc000445cb8, 0xc00007a900, 0xc0004967c8}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:159
github.com/eryajf/go-ldap-admin/public/common.InitMysql()
	/app/public/common/database.go:49 +0x5be
main.main()
	/app/main.go:30 +0x4f

**Comment by 370569218** [comment]
重新pull了镜像报数据库错误

**Comment by eryajf** [comment]
这个应该是外部配置文件挂载之后的一个问题，你执行下这两步，然后重新拉就OK了：

```
sed -i 's@host: localhost@host: mysql@g'  config/config.yml
sed -i 's@localhost:389@openldap:389@g' config/config.yml
```

随后我修复一下这个地方。

**Comment by 370569218** [comment]
执行上面两条命令可以了

**Comment by 370569218** [comment]
前端无法登录，是不是配置错了访问api是localhost
![image](https://user-images.githubusercontent.com/23556204/177260185-bc78781f-4f47-4ec9-a629-eef5d5a0b4e5.png)

**Comment by calvin110** [comment]
重新拉取镜像，并执行以下2行命令，部署成功：
sed -i 's@host: localhost@host: mysql@g'  config/config.yml
sed -i 's@localhost:389@openldap:389@g' config/config.yml

**Comment by eryajf** [comment]
> 前端无法登录，是不是配置错了访问api是localhost

前端问题看这里 #35

**Comment by 370569218** [comment]
![image](https://user-images.githubusercontent.com/23556204/177310101-1341c38d-ac9b-4f8b-b750-0c84838f7fba.png)
字段关系管理菜单报错

**Comment by eryajf** [comment]
@370569218 这个前端还没上线，要再等等

**Comment by wokula99** [comment]
还报错
![image](https://user-images.githubusercontent.com/46983052/177691934-b9c7256c-730f-40db-8c41-9414893b29ab.png)

**Comment by eryajf** [comment]
> 还报错

你拉下最新的docker-compose主配置文件，我暂时把配置文件的挂载注释了，如果要挂载的话，是需要更改两个连接的配置的。

你当前部署体验的话，可以先注释这两行。
