### ISSUE TITLE
docker 下 同步失败 

### ISSUE THREAD

**Issue by bulolo** [eryajf/go-ldap-admin#63]
```
msg: "获取企业微信部门列表失败：41001: access_token missing, hint: [1657521269365203040793615], from ip: 113.110.228.213, more info at https://open.work.weixin.qq.com/devtool/query?e=41001"
```

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/10026498/178203469-0d40e16b-d6d4-4d75-b69a-f43431ad1e8f.png">

**Comment by eryajf** [comment]
您好 @bulolo👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @bulolo. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by bulolo** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/10026498/178204780-034d8c0a-5238-4fb8-bb6d-6a38b0d5b153.png">

**Comment by bulolo** [comment]
配置了的

**Comment by bulolo** [comment]
我的操作步骤：

git clone https://github.com/eryajf/go-ldap-admin.git
拉下来后直接改 wecom配置，然后docker-compose up -d ,然后分组 同步 企业微信

**Comment by eryajf** [comment]
这一步也需要配置才可以：
<img width="877" alt="image" src="https://user-images.githubusercontent.com/33259379/178205864-f964b441-a0b9-4ec7-be18-a9a743ea5539.png">

动态字段管理文档： http://ldapdoc.eryajf.net/pages/84953d/

**Comment by bulolo** [comment]
这个报错似乎跟这个没关系吧，是拉不到企微的数据

**Comment by eryajf** [comment]
你是进入到容器里边改的配置吗，改了之后有无重启对应容器

**Comment by bulolo** [comment]
> 你是进入到容器里边改的配置吗，改了之后有无重启对应容器
步骤：
git clone https://github.com/eryajf/go-ldap-admin.git
进入 docs 下
<img width="342" alt="image" src="https://user-images.githubusercontent.com/10026498/178206419-a91a96af-2c1d-446a-9092-54483b13c37c.png">
直接修改 config.yml 文件 的wecom配置

然后  docker-compose up -d

**Comment by eryajf** [comment]
目前默认情况下，这个配置文件没有挂到容器里去：

<img width="905" alt="image" src="https://user-images.githubusercontent.com/33259379/178206736-a4c55ebf-ac95-44cb-b90d-0fcf6a18553c.png">

因为涉及到MySQL和ldap连接地址的更改。如果你想挂载出来，需要执行一下Dockerfile里边的两步：

```
sed -i 's@host: localhost@host: mysql@g'  config.yml
sed -i 's@localhost:389@openldap:389@g' config.yml
```

然后取消docker-compose.yml里边的注释，然后再次运行容器。

**Comment by eryajf** [comment]
> 我直接把config.yml的mysql和ldap连接改成非localhost,也就是 本机ip和映射的端口，但还是连接不上。

在后端server容器内看看网络端口是否通，猜测应该是这个原因。或者直接改成link过去的那个name

**Comment by bulolo** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/10026498/178209366-62246f0a-2f16-427b-8389-dcb2942ca67e.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/10026498/178209581-7dd6b0fd-5be7-4aeb-9424-0ef81a1c69fd.png">
<img width="758" alt="image" src="https://user-images.githubusercontent.com/10026498/178209608-a587f81c-4cef-4960-bd15-e8579147d719.png">

**Comment by bulolo** [comment]
我详细检查下

**Comment by bulolo** [comment]
可以了可以了。感谢指导

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/10026498/178209761-2e852971-b154-49f3-a733-23793e662bde.png">
接着即使字段的问题了，我去研究下

**Comment by eryajf** [comment]
:_onion_head_bike: 你快走出来了，字段关联也是很重要的一块儿，目前需要看看文档理解一下，后边我看看录一下说明的视频。

**Comment by bulolo** [comment]
可以了，但是有一个疑惑和2点建议


疑惑：

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/10026498/178211903-f0ddcf2a-82bf-490d-855d-4d8354e146ad.png">
这里用的custom_name_pinyin 不用name 是因为ldap不建议使用中文吗？（主要我对ldap不了解）


建议：
1.希望有一个默认的字段关系
2.我在第一次同步分组后（使用custom_name_pinyin），我把关系改成name，原以为会自动覆盖替换，结束时失败同步。我将所有分组都删了，才能再同步成功，是否可以支持覆盖同步。
