### ISSUE TITLE
只部署ldap管理界面

### ISSUE THREAD

**Issue by JosonQian** [eryajf/go-ldap-admin#64]
数据库和ldap已经部署完成，可以只部署管理界面进行管理吗，谢谢！

**Comment by eryajf** [comment]
您好 @JosonQian👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @JosonQian. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
当然可以，你可以阅读下docker-compose.yml的配置信息，后端会依赖MySQL和ldap，只需要正确更改其中的配置信息就可以连接，这块儿我正在撰写文档，随后会更新在官方文档。

你可以先自行摸索一下

**Comment by eryajf** [comment]
当然可以，你可以阅读下docker-compose.yml的配置信息，后端会依赖MySQL和ldap，只需要正确更改其中的配置信息就可以连接，这块儿我正在撰写文档，随后会更新在官方文档。

你可以先自行摸索一下

**Comment by JosonQian** [comment]
![image](https://user-images.githubusercontent.com/23549404/178219054-b4a7dc6b-b554-4068-96e3-b33f7d37da2d.png)
这个容器作用是什么呀，这个我没有看懂呢，能介绍一下吗？

**Comment by JosonQian** [comment]
那我明白了，这个容器其实不部署也可以，直接用新的管理页面就可以直接管理了，多谢。
