### ISSUE TITLE
钉钉同步，后台用户列表中部门显示错误

### ISSUE THREAD

**Issue by wokula99** [eryajf/go-ldap-admin#80]
钉钉同步，后台用户列表中部门显示错误

![3eae685d0b3c5001283ed0c6afd002f](https://user-images.githubusercontent.com/46983052/178894834-c99597bd-cc22-45ff-a723-37d430fa99d3.png)
![dc3b7f50ff4f6542dd7cb8445d6d9f3](https://user-images.githubusercontent.com/46983052/178894854-e5b4f950-012d-406e-8af7-55f43be5abdf.png)

**Comment by eryajf** [comment]
您好 @wokula99👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @wokula99. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
已 fix
