### ISSUE TITLE
后台重置密码功能无效

### ISSUE THREAD

**Issue by lemsn** [eryajf/go-ldap-admin#91]
重置密码后登录不上，试了好多次，无意中发现是后台重置密码无效，无论修改为什么，都不行。 

PS:  用户自己登录到go-ldap-admin前台页面的话，修改密码是没有问题的

![图片](https://user-images.githubusercontent.com/9290824/179903173-f1b53e93-e582-4914-89d2-5b9fc9c0d3b7.png)

**Comment by eryajf** [comment]
您好 @lemsn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lemsn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
目前不建议通过这里更改用户密码，官方文档介绍了两种改密码的方式：一个是用户登录自己的账号，用新旧账号更改，一种是在登录页面，点击忘记密码，通过用户邮箱进行密码的重置
