### ISSUE TITLE
普通用户登录出现404问题

### ISSUE THREAD

**Issue by lemsn** [eryajf/go-ldap-admin#92]
普通用户登录到出现404页面，点返回后，才可以进到个人页面

![图片](https://user-images.githubusercontent.com/9290824/179902440-cf30bf92-813e-466f-83bb-3829dbd2cab5.png)

**Comment by eryajf** [comment]
您好 @lemsn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lemsn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
恩恩，这应该是普通用户的权限配置有问题，没有给首页访问的权限，权限当中给一下就好了
