### ISSUE TITLE
"DsyncWeComDepts添加部门失败: 添加部门失败：LDAP Result Code 34 \"Invalid DN Syntax\": invalid DN"

### ISSUE THREAD

**Issue by lemsn** [eryajf/go-ldap-admin#97]
同步企业微信的架构的时候提示的，人员同步也有问题
"DsyncWeComDepts添加部门失败: 添加部门失败：LDAP Result Code 34 \"Invalid DN Syntax\": invalid DN"

刚拉的最新docker版，要如何解决呢？

**Comment by eryajf** [comment]
您好 @lemsn👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @lemsn. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
> 同步企业微信的架构的时候提示的，人员同步也有问题 "DsyncWeComDepts添加部门失败: 添加部门失败：LDAP Result Code 34 "Invalid DN Syntax": invalid DN"
> 
> 刚拉的最新docker版，要如何解决呢？

你配置的字段关系，映射给分组name的字段是哪个呢

**Comment by lemsn** [comment]
我不太会配，可不指教一下

![image](https://user-images.githubusercontent.com/9290824/181140624-f53df7f4-8dd0-4b64-9d36-fbda1afabecf.png)

**Comment by eryajf** [comment]
看起来这块儿配置没毛病，挺想知道你这会儿失败的分组是哪一个，估计是这个部门的名字比较奇怪，导致解析成dn的时候，被ldap判断为不合法

**Comment by lemsn** [comment]
我又修改了一下字段，同步分组可以了，现在用户出问题了：
SyncWeComUsers写入用户失败：AddUser向LDAP创建用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": mobile: value #0 invalid per syntax

**Comment by lemsn** [comment]
这是手机号不能为空的意思吗？

**Comment by eryajf** [comment]
是全部都失败，还是有部分已经同步成功了

**Comment by lemsn** [comment]
部分失败

**Comment by lemsn** [comment]
还有，公司存在同名同姓的情况，如果遇到同名的情况用户名的拼音能否加1呢，比如 zhangsan, zhangsan1,zhangsan2

**Comment by eryajf** [comment]
> SyncWeComUsers写入用户失败：AddUser向LDAP创建用户失败：LDAP Result Code 21 "Invalid Attribute Syntax": mobile: value #0 invalid per syntax

这个猜测应该是某个人的手机号为空，所以报错了，后边我考虑看看把对应报错的部门或者人员也打印出来，便于排查

**Comment by lemsn** [comment]
太好了，非常感谢，你这个项目很好，希望越来越好。

**Comment by eryajf** [comment]
> 还有，公司存在同名同姓的情况，如果遇到同名的情况用户名的拼音能否加1呢，比如 zhangsan, zhangsan1,zhangsan2

这个情况的话，我建议用户名使用邮箱前缀，字段关系当中也已经提供了邮箱前缀字段，详情参考官方文档：

![image_20220727_095604](https://cdn.staticaly.com/gh/eryajf/tu/main/img/image_20220727_095604.png)

**Comment by lemsn** [comment]
我把我的字段关系提供大家看看，希望对大家有帮助

![image](https://user-images.githubusercontent.com/9290824/181143715-485381a6-6a28-462a-b7f1-9bf37353cfc0.png)

![image](https://user-images.githubusercontent.com/9290824/181143737-a9afdcf6-049c-401d-af1d-1c98c4a4595d.png)

**Comment by eryajf** [comment]
> 太好了，非常感谢，你这个项目很好，希望越来越好。

感谢肯定，后续你如果在公司内部用起来了，方便的话，可以在这里帮忙做个登记：https://github.com/eryajf/go-ldap-admin/issues/18

使用过程中有其他的想法或者问题，也欢迎随时在issue中讨论！

**Comment by eryajf** [comment]
> 我把我的字段关系提供大家看看，希望对大家有帮助

👍🏻

**Comment by yunkaiOr2** [comment]
> 我把我的字段关系提供大家看看，希望对大家有帮助
> 
> ![image](https://user-images.githubusercontent.com/9290824/181143715-485381a6-6a28-462a-b7f1-9bf37353cfc0.png)
> 
> ![image](https://user-images.githubusercontent.com/9290824/181143737-a9afdcf6-049c-401d-af1d-1c98c4a4595d.png)

真的可以了，这个字段说是可以映射，实际上不配置成这样，没发用啊。不知道我理解的对不对

**Comment by eryajf** [comment]
> > 我把我的字段关系提供大家看看，希望对大家有帮助
> > ![image](https://user-images.githubusercontent.com/9290824/181143715-485381a6-6a28-462a-b7f1-9bf37353cfc0.png)
> > ![image](https://user-images.githubusercontent.com/9290824/181143737-a9afdcf6-049c-401d-af1d-1c98c4a4595d.png)
> 
> 真的可以了，这个字段说是可以映射，实际上不配置成这样，没发用啊。不知道我理解的对不对

是需要配置的，实际上现在最新的版本，我已经在初始化的时候初始化了这块儿配置，以免有的同学不会配置。主要还是看项目官方文档
